scalameta/scalameta

scalameta/src/main/scala/scala/meta/ui/ShowCode.scala, tests/src/test/scala/show/ScalaSuite.scala
Also unconvers an imprecision in parenthesization of Pat.Typed
=> fixes prettyprinting for Pat.Type

README.md
Thanks to http://derecho.elijah.cs.cmu.edu:8585/
=> fixes a broken readme link

scalameta/src/main/scala/scala/meta/semantic/Api.scala
It seems that I've overlooked this one back then.
=> introduces Scope.packageObject

scalameta/src/main/scala/scala/meta/Origin.scala, scalameta/src/main/scala/scala/meta/syntactic/Api.scala, tests/src/test/scala/parser/BootstrapSuite.scala, tests/src/test/scala/parser/LinePositionSuite.scala
- Addition of line positions to origin
- Addition of a benchmark suite to test it using Defn.Def, Defn.Class, Term.Match.
=> Adding line position to Origin

scalameta/src/main/scala/scala/meta/internal/quasiquotes/tokens/ReificationMacros.scala, scalameta/src/main/scala/scala/meta/syntactic/Token.scala
Fixes the hygiene violation pointed out in #142, and fixes a typo I made in a comment.
=> Fix hygiene violation

project/build.scala
Hacking at 5am is considered dangerous.
=> makes sbt publish the newly created tokens project

scalameta/src/main/scala/scala/meta/Trees.scala, scalameta/src/main/scala/scala/meta/internal/parsers/Parsers.scala, scalameta/src/main/scala/scala/meta/internal/quasiquotes/ast/ReificationMacros.scala, tests/src/test/scala/quasiquotes/ErrorSuite.scala, tests/src/test/scala/quasiquotes/QuasiquoteSuite.scala, tests/src/test/scala/show/TokenSuite.scala
Now Parser correctly handles all kinds of anonymous functions. That also provides support for typed tuples.
=> Correct behaviour for anonymous functions

scalameta/src/main/scala/scala/meta/internal/parsers/Parsers.scala, scalameta/src/main/scala/scala/meta/internal/quasiquotes/ast/ReificationMacros.scala, tests/src/test/scala/parser/LinePositionSuite.scala, tests/src/test/scala/parser/ParseSuite.scala, tests/src/test/scala/parser/TermSuite.scala
=> deep dive into lambda parsing

foundation/src/main/scala/org/scalameta/adt/Adt.scala, scalameta/src/main/scala/scala/meta/internal/quasiquotes/ast/ConversionMacros.scala, scalameta/src/main/scala/scala/meta/internal/quasiquotes/ast/ReificationMacros.scala, scalameta/src/main/scala/scala/meta/internal/semantic/Denotation.scala, scalameta/src/main/scala/scala/meta/internal/semantic/Expansion.scala, scalameta/src/main/scala/scala/meta/internal/semantic/Typing.scala, scalameta/src/main/scala/scala/meta/semantic/Api.scala, scalameta/src/main/scala/scala/meta/ui/ShowPositions.scala, scalameta/src/main/scala/scala/meta/ui/ShowSemantics.scala, scalameta/src/main/scala/scala/meta/ui/ShowStructure.scala, tests/src/test/scala/internal/InternalSuite.scala, tests/src/test/scala/quasiquotes/HygieneSuite.scala
The second reincarnation of the scala.reflect -> scala.meta converter is almost ready to convert the most basic program!
=> miscellaneous fixes

docs/ast.md, foundation/src/main/scala/org/scalameta/ast/ast.scala, foundation/src/main/scala/org/scalameta/ast/metadata.scala, scalameta/src/main/scala/scala/meta/Trees.scala, scalameta/src/main/scala/scala/meta/internal/parsers/Parsers.scala, tests/src/test/scala/ast/InfrastructureSuite.scala
See the diff in Parsers.scala to understand why this method is necessary.
=> introduces Quasi.become

foundation/src/main/scala/org/scalameta/ast/Reflection.scala, scalameta/parsers/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/prettyprinters/src/main/scala/scala/meta/prettyprinters/Structure.scala, scalameta/quasiquotes/src/main/scala/scala/meta/internal/quasiquotes/Flatten.scala, scalameta/quasiquotes/src/main/scala/scala/meta/internal/quasiquotes/ReificationMacros.scala, scalameta/quasiquotes/src/main/scala/scala/meta/quasiquotes/Lift.scala, scalameta/quasiquotes/src/main/scala/scala/meta/quasiquotes/Unlift.scala, scalameta/quasiquotes/src/test/scala/scala/meta/tests/quasiquotes/ErrorSuite.scala, scalameta/quasiquotes/src/test/scala/scala/meta/tests/quasiquotes/QuasiquoteSuite.scala
=> fixes #199

foundation/src/main/scala/org/scalameta/typelevel/=!=.scala, foundation/src/main/scala/org/scalameta/typelevel/Shapes.scala, project/build.scala, scalameta/parsers/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/parsers/src/test/scala/scala/meta/tests/parsers/ScalaSuite.scala, scalameta/parsers/src/test/scala/scala/meta/tests/parsers/SerializationSuite.scala, scalameta/parsers/src/test/scala/scala/meta/tests/tokens/InferSimpleSuite.scala, scalameta/quasiquotes/src/main/scala/scala/meta/internal/quasiquotes/ReificationMacros.scala, scalameta/quasiquotes/src/test/scala/scala/meta/tests/quasiquotes/QuasiquoteSuite.scala, scalameta/semantic/src/main/scala/scala/meta/semantic/Api.scala, scalameta/tokens/src/main/scala/scala/meta/inputs/Content.scala, scalameta/tokens/src/main/scala/scala/meta/inputs/Input.scala, scalameta/tql/src/main/scala/scala/meta/internal/tql/AllowedTransformation.scala, scalameta/tql/src/main/scala/scala/meta/internal/tql/CollectionLikeUI.scala, scalameta/tql/src/main/scala/scala/meta/internal/tql/Combinators.scala, scalameta/tql/src/main/scala/scala/meta/tql/Api.scala, scalameta/tql/src/main/scala/scala/meta/tql/CollectionLikeUI.scala, scalameta/trees/src/main/scala/scala/meta/Trees.scala, scalameta/trees/src/main/scala/scala/meta/internal/ast/Fresh.scala, scalameta/trees/src/main/scala/scala/meta/internal/prettyprinters/InferTokens.scala
/cc @Dveim (take a look at https://github.com/scalameta/scalameta/commit/5403dfe9e1c19da9c9931df8d0fd176bcbbd6ffc)
=> fixes for https://github.com/scalameta/tutorial

.gitignore, docs/converters.md, scalahost/src/main/scala/scala/meta/internal/hosts/scalac/contexts/Adapter.scala, scalahost/src/main/scala/scala/meta/internal/hosts/scalac/converters/ToMtree.scala, scalahost/src/main/scala/scala/meta/internal/hosts/scalac/reflect/LogicalTrees.scala, scalahost/src/test/resources/Simple6/Original.scala, scalahost/src/test/resources/Simple6/Semantic.expected, scalahost/src/test/resources/Simple6/Syntactic.expected, scalahost/src/test/scala/scala/meta/tests/semantic/SemanticSuite.scala, scalameta/trees/src/main/scala/scala/meta/internal/ast/MergeTrees.scala
Continues the trend set in https://github.com/scalameta/scalameta/pull/303. Now from the Typesafe office, courtesy of @adriaanm. Too bad I have to go out and do stuff in the city :)
=> more San Francisco goodness

foundation/src/main/scala/org/scalameta/ast/internal.scala, scalameta/parsers/src/test/scala/scala/meta/tests/ast/ChildrenSuite.scala
=> fixes #308

scalahost/src/main/scala/scala/meta/internal/hosts/scalac/converters/ToMtree.scala, scalahost/src/main/scala/scala/meta/internal/hosts/scalac/reflect/LogicalTrees.scala, scalahost/src/test/resources/Simple8/Original.scala, scalahost/src/test/resources/Simple8/Semantic.expected, scalahost/src/test/resources/Simple8/Syntactic.expected, scalameta/trees/src/main/scala/scala/meta/internal/ast/MergeTrees.scala
=> support for some imperative features

LICENSE.md
Let me know if you need this or not.
Thank you :)
=> Update License to 2016

docs/quasiquotes.md
=> Clarify double stats in template

scalameta/parsers/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/parsers/src/test/scala/scala/meta/tests/parsers/LitSuite.scala
=> fixes #344

scalameta/parsers/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/scalameta/src/test/scala/scala/meta/tests/ast/TokensSuite.scala, scalameta/scalameta/src/test/scala/scala/meta/tests/tokenizers/TokenizerSuite.scala, scalameta/tokens/src/main/scala/scala/meta/internal/tokens/InternalTokens.scala, scalameta/trees/src/main/scala/scala/meta/internal/ast/InternalTrees.scala
I don't have a strong opinion either way, but @olafurpg does :)
=> BOF/EOF are again part of Tree.tokens

project/build.scala
The days of dreaming about 0.1 are long gone, now we aspire to 1.0.
=> updates to 1.0.0-SNAPSHOT

docs/quasiquotes.md, scalameta/common/src/main/scala/scala/meta/internal/ast/Liftables.scala, scalameta/parsers/src/main/scala/scala/meta/internal/parsers/Messages.scala, scalameta/parsers/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/quasiquotes/src/main/scala/scala/meta/internal/quasiquotes/ConversionMacros.scala, scalameta/quasiquotes/src/main/scala/scala/meta/internal/quasiquotes/ReificationMacros.scala, scalameta/scalameta/src/test/scala/scala/meta/tests/quasiquotes/ErrorSuite.scala, scalameta/scalameta/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala, scalameta/trees/src/main/scala/scala/meta/internal/ast/SyntacticTrees.scala, scalameta/trees/src/main/scala/scala/meta/internal/ast/package.scala
Takes care of #277 and makes the ...$ infrastructure much more robust. Still have to fix #406 though, but that'll most likely only happen after my thesis is done.
=> improve support for ...$, add extensive tests

readme/Readme.scalatex
=> switches from google analytics to piwik

readme/Readme.scalatex
Pushing in haste = recipe for a disaster. This time it was small-scale.
=> fixes typos

scalameta/quasiquotes/src/main/scala/scala/meta/quasiquotes/Lift.scala, scalameta/scalameta/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala
=> supersedes #471

scalameta/dialects/src/main/scala/scala/meta/dialects/package.scala, scalameta/parsers/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/scalameta/src/test/scala/scala/meta/tests/parsers/DottySuite.scala
=> Fix #496: Remove view bounds support in Dotty dialect

notes/quasiquotes.md, scalameta/dialects/src/main/scala/scala/meta/dialects/package.scala, scalameta/parsers/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/scalameta/src/test/scala/scala/meta/tests/api/SurfaceSuite.scala, scalameta/scalameta/src/test/scala/scala/meta/tests/ast/ReflectionSuite.scala, scalameta/scalameta/src/test/scala/scala/meta/tests/parsers/DottySuite.scala, scalameta/scalameta/src/test/scala/scala/meta/tests/parsers/TypeSuite.scala, scalameta/scalameta/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala, scalameta/trees/src/main/scala/scala/meta/Trees.scala, scalameta/trees/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
Supersedes https://github.com/scalameta/scalameta/pull/491
=> add union types (A | B)

readme/Readme.scalatex
I'm gonna let the lassio.io domain expire.
=> Replace stats.lassie.io with stats.geirsson.com

notes/quasiquotes.md
I'm new to scalameta, but this looks like a typo. The proposed version matches fine on my class, the previous results in a MatchError
=> Fix definition for class

notes/quasiquotes.md
fixes https://github.com/scalameta/scalameta/pull/546
=> fix for ctorMods: need `..`

scalameta/trees/src/main/scala/scala/meta/internal/ast/Helpers.scala
add TermApply helper. Review @xeno-by .
=> add TermApply helper

scalameta/scalameta/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala, scalameta/trees/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
=> Extract strings from lits in Pat.Interpolate

build.sbt
The name `git` conflicts with another object from the SbtGit plugin,
which may be installed globally.
=> Rename git => GitOps.

scalameta/scalameta/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala, scalameta/trees/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
=> Fix Incorrent unquotation of type lambda trick (#565)

scalameta/common/src/main/scala/org/scalameta/logger.scala, scalameta/dialects/src/main/scala/scala/meta/dialects/package.scala, scalameta/parsers/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/scalameta/src/test/scala/scala/meta/tests/api/SurfaceSuite.scala, scalameta/scalameta/src/test/scala/scala/meta/tests/parsers/ParseSuite.scala, scalameta/scalameta/src/test/scala/scala/meta/tests/parsers/TrailingCommaSuite.scala, scalameta/scalameta/src/test/scala/scala/meta/tests/prettyprinters/PublicSuite.scala
cc/ https://github.com/scala/scala-dev/issues/299
=> Add support for trailing commas, fixes #657

scalameta/contrib/src/main/scala/scala/meta/contrib/Converters.scala, scalameta/contrib/src/test/scala/scala/meta/contrib/ConverterSuite.scala
=> asPat{VarTerm => }

scalameta/contrib/src/main/scala/scala/meta/contrib/CommentOps.scala, scalameta/contrib/src/main/scala/scala/meta/contrib/DocToken.scala, scalameta/contrib/src/main/scala/scala/meta/contrib/ScaladocParser.scala, scalameta/contrib/src/main/scala/scala/meta/contrib/implicits/CommentExtensions.scala, scalameta/contrib/src/main/scala/scala/meta/contrib/package.scala, scalameta/contrib/src/test/scala/scala/meta/contrib/ScaladocParserSuite.scala, scalameta/contrib/src/test/scala/scala/meta/contrib/ScaladocParserTest.scala
=> Parser for Scaladoc comments (#556)

CONTRIBUTING.md
=> Add ticket raising guidelines

.gitignore, scalameta/parsers/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/scalameta/src/test/scala/scala/meta/tests/parsers/ImportSuite.scala
Note that this also includes some tweaks to make the project more ScalaIDE friendly.
=> Fix for #549 from the Scalasphere Hackaton

CONTRIBUTING.md
@acjay I thought I would add guidelines here too, for future reference.
=> Add documentation guidelines for enrichments

bin/bintray.sh, build.sbt
The CI is still failing to run `./bin/bintray.sh` for some reason.
=> Update publish settings

scalameta/parsers/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/scalameta/src/test/scala/scala/meta/tests/parsers/TemplateSuite.scala
=> fix parsing of tail paramlists of case classes

.jvmopts, build.sbt, scalahost/src/test/scala/scala/meta/tests/scalahost/converters/ConverterSuite.scala
The new CI server seems to not handle the previous settings, see https://github.com/scalameta/scalameta/pull/763#issuecomment-289204164
=> Lower memory pressure in ci-slow

scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala
I want to implement a scalafix rewrite to do the migration
automatically.
=> Add deprecated constructors for source compat with 1.6.

scalameta/testkit/src/test/scala/scala/meta/testkit/ScalametaParserProperties.scala, scalameta/testkit/src/test/scala/scala/meta/tests/prettyprinters/PrettyPrinterSuite.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
Lets start the review process early, @olafurpg
=> Pretty printer

changelog/1.8.0.md, scalameta/contrib/shared/src/main/scala/scala/meta/contrib/Replace.scala, scalameta/contrib/shared/src/main/scala/scala/meta/contrib/implicits/ExtractExtensions.scala, scalameta/contrib/shared/src/main/scala/scala/meta/contrib/implicits/ReplaceExtensions.scala, scalameta/contrib/shared/src/main/scala/scala/meta/contrib/implicits/SetExtensions.scala, scalameta/contrib/shared/src/main/scala/scala/meta/contrib/implicits/implicits.scala, scalameta/contrib/shared/src/main/scala/scala/meta/contrib/instances/ReplaceModsInstances.scala, scalameta/contrib/shared/src/main/scala/scala/meta/contrib/instances/ReplaceStatInstances.scala, scalameta/contrib/shared/src/main/scala/scala/meta/contrib/instances/instances.scala, scalameta/contrib/shared/src/main/scala/scala/meta/contrib/package.scala, scalameta/contrib/shared/src/test/scala/scala/meta/contrib/ModReplacementTest.scala, scalameta/contrib/shared/src/test/scala/scala/meta/contrib/StatReplacementTest.scala
I'll tackle update later.
@ShaneDelmore you may also be interested.
=> Contrib replace

scalameta/contrib/shared/src/main/scala/scala/meta/contrib/implicits/Converters.scala, scalameta/contrib/shared/src/test/scala/scala/meta/contrib/ConverterSuite.scala
=> Close #801 by adding Type.Arg#toType

build.sbt, changelog/1.8.0.md, project/plugins.sbt
For example, I ran `sbt -Dscalameta.version=1.8.0 -Dscalameta.publish=sonatype` to
publish v1.8.0.
=> Add helpers to publish to sonatype.

scalameta/scalameta/shared/src/test/scala/scala/meta/tests/parsers/XmlSuite.scala, scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/XmlParser.scala
Now parses invalid XML that fails at runtime in scalac
=> More pervasive XML Parser

scalameta/testkit/src/main/scala/scala/meta/testkit/CorpusFile.scala, scalameta/testkit/src/main/scala/scala/meta/testkit/Observation.scala
I was running a few experiments on infix operators and hit on a few
bumps.
=> Minor tweaks in testkit syntax analysis.

scalameta/common/shared/src/main/scala/scala/meta/internal/ast/ast.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/ast/InternalTrees.scala
=> Add productFields

build.sbt, scalameta/parsers/js/src/main/scala/scala/meta/parsers/JSFacade.scala, scalameta/parsers/js/src/test/scala/scala/meta/parsers/JSFacadeSuite.scala
This allows for a nicer output that enables this:
~Also this is based on #956, I'll rebase once that one gets merged.~
=> Use productFields in parsersJS

scalameta/dialects/shared/src/main/scala/scala/meta/dialects/package.scala, scalameta/scalameta/jvm/src/test/scala/scala/meta/tests/api/SurfaceSuite.scala, scalameta/scalameta/shared/src/test/scala/scala/meta/tests/tokenizers/TokenizerSuite.scala, scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala, scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyToken.scala, scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/ScalametaTokenizer.scala, scalameta/tokens/shared/src/main/scala/scala/meta/tokens/Token.scala
This is the first step to toward #901
=> Add support for `enum` token

scalahost/nsc/src/main/scala/scala/meta/internal/semantic/AttributesOps.scala, scalameta/io/jvm/src/main/scala/scala/meta/internal/io/PlatformFileIO.scala, scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/semantic/shared/src/main/scala/scala/meta/internal/semantic/package.scala, scalameta/semantic/shared/src/main/scala/scala/meta/internal/semantic/vfs/Entry.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/InternalTrees.scala
Was gonna work on #1039 but hit on several problems that prevent us from
enabling this by default.
=> Remove unused imports.

scalameta/io/js/src/main/scala/java/io/File.scala, scalameta/io/js/src/main/scala/java/nio/file/Path.scala, scalameta/io/js/src/main/scala/scala/meta/internal/io/NodeNIOPath.scala, scalameta/io/js/src/main/scala/scala/meta/internal/io/PlatformPathIO.scala, scalameta/io/jvm/src/main/scala/scala/meta/internal/io/PlatformPathIO.scala, scalameta/io/shared/src/main/scala/scala/meta/internal/io/PathIO.scala, scalameta/scalameta/shared/src/test/scala/scala/meta/tests/io/IOFileTest.scala
Fixes the error reported in #1031 as well as a few other issues encountered.
Tested with locally published version on top of https://github.com/olafurpg/metadoc/tree/meta-v2
=> Clean up and improve the JavaScript IO implementation

langmeta/shared/src/main/scala/org/langmeta/semanticdb/Denotation.scala, scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/semanticdb/DocumentOps.scala, scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/semanticdb/PrinterOps.scala, scalameta/semanticdb-scalac/src/test/scala/scala/meta/tests/SemanticSuite.scala, scalameta/tests/jvm/src/test/resources/semanticdb.expect
I'm not sure if this solution is acceptable, but it seems to handle the problematic case I could come up with.
=> Fix #1106.

appveyor.yml, build.sbt, scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/semanticdb/DocumentOps.scala, scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/semanticdb/PrinterOps.scala, scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/semanticdb/SymbolOps.scala, scalameta/semanticdb-scalac/src/test/scala/scala/meta/tests/DatabaseSuite.scala, scalameta/semanticdb-scalac/src/test/scala/scala/meta/tests/SemanticSuite.scala
I'm still hitting on some problems with singleton types on companion objects. Will investigate tomorrow. This PR is ready for merge, regardless.
=> Several type printer fixes

scalameta/parsers/shared/src/main/scala/scala/meta/parsers/Errors.scala, scalameta/tokenizers/shared/src/main/scala/scala/meta/tokenizers/Errors.scala
This adds `fold`, `toOption`, and `toEither` methods to `Parsed`.
Additionally, all methods were updated to be implemented in terms of `fold`.
I haven't added any new tests for `toOption` and `toEither` as I'm still getting familiar with the codebase's organization.
=> Add .fold, .toOption, and .toEither to Parsed and Tokenized ADTs

langmeta/shared/src/main/scala/org/langmeta/internal/inputs/package.scala
=> Prevent Position.formatMessage from removing leading whitespace.

scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/HijackAnalyzer.scala
semanticdb-scalac hijacks the typechecking analyzer to attach important
metadata to tree nodes during typechecking. Previously, the hijacked
version of the analyzer would discard the existing macroPlugins from the
old analyzer. This caused semanticdb-scalac to be incompatible with
other compiler plugins like scalamacros/paradise. This commit changes
the hijacking step to copy over the macro plugins from the old analyzer
into the new analyzer.
Fixes #1135. This patch has only been manually tested.
=> Restore macro plugins from old analyzer.

scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/semanticdb/DocumentOps.scala, scalameta/semanticdb-scalac/src/test/scala/scala/meta/tests/SemanticSuite.scala
=> Skip anonymous classes, fixes #1153

project/Mima.scala, scalameta/contrib/shared/src/main/scala/scala/meta/contrib/implicits/ExtractExtensions.scala, scalameta/contrib/shared/src/main/scala/scala/meta/contrib/implicits/ReplaceExtensions.scala, scalameta/contrib/shared/src/main/scala/scala/meta/contrib/instances/ExtractModsInstances.scala, scalameta/contrib/shared/src/main/scala/scala/meta/contrib/instances/ReplaceModsInstances.scala
Pushing some scalagen code upstream.
More changes in this area will probably come.
=> Contrib more instances

scalameta/semanticdb-scalac-core/src/main/scala/scala/meta/internal/semanticdb/PrinterOps.scala
This is a pure refactoring, no functional difference.
=> Remove unused code in pretty printer

bin/bench, build.sbt, project/Build.scala
For simpler comparison between master and #1218
=> Add quickLSP bench command

build.sbt
I failed to update this setting in the last PR.
=> Fix publishTo setting for snapshot releases.

build.sbt, langmeta/langmeta/shared/src/main/scala/org/langmeta/semanticdb/Denotation.scala, langmeta/langmeta/shared/src/main/scala/org/langmeta/semanticdb/internal/package.scala, scalameta/semanticdb-integration/src/main/scala/example/Overrides.scala, scalameta/semanticdb-scalac-core/src/main/scala/scala/meta/internal/semanticdb/DenotationOps.scala, scalameta/semanticdb-scalac-core/src/main/scala/scala/meta/internal/semanticdb/DocumentOps.scala, tests/jvm/src/test/resources/semanticdb.expect, tests/jvm/src/test/scala-2.12/scala/meta/tests/semanticdb/OverridesSuite.scala
Supersedes https://github.com/scalameta/scalameta/pull/1235.
=> Fixup for https://github.com/scalameta/scalameta/pull/1235

build.sbt, langmeta/langmeta/shared/src/main/scala/org/langmeta/semanticdb/internal/package.scala, semanticdb/metap/src/main/scala/scala/meta/cli/Metap.scala, semanticdb/semanticdb3/semanticdb3.md, semanticdb/semanticdb3/semanticdb3.proto, tests/jvm/src/test/resources/semanticdb.expect
Supersedes https://github.com/scalameta/scalameta/pull/1252, fixes https://github.com/scalacenter/scalafix/issues/596.
=> Explain uniqueness guarantees for symbols

semanticdb/semanticdb3/semanticdb3.md
Inspired by https://github.com/scalameta/scalameta/pull/1241. /cc @mberndt123
=> Synchronize the spec and the implementation of global symbol format

langmeta/langmeta/shared/src/main/scala/org/langmeta/semanticdb/Flags.scala, langmeta/langmeta/shared/src/main/scala/org/langmeta/semanticdb/internal/package.scala, semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/DenotationOps.scala, tests/jvm/src/test/resources/semanticdb.expect, tests/jvm/src/test/scala-2.12/scala/meta/tests/semanticdb/OverridesSuite.scala, tests/jvm/src/test/scala/scala/meta/tests/semanticdb/TargetedSuite.scala
Fixed https://github.com/scalameta/scalameta/issues/1256.
=> Fix handling of JAVADEFINED

build.sbt, semanticdb/metac/src/main/scala/scala/meta/cli/Metac.scala, semanticdb/metac/src/main/scala/scala/meta/internal/metac/Main.scala, semanticdb/metacp/src/main/scala/scala/meta/cli/Metacp.scala, semanticdb/metacp/src/main/scala/scala/meta/internal/metacp/Main.scala, semanticdb/metacp/src/main/scala/scala/meta/internal/metacp/Settings.scala, semanticdb/metap/src/main/scala/scala/meta/cli/Metap.scala, semanticdb/metap/src/main/scala/scala/meta/internal/metap/Main.scala, tests/jvm/src/test/scala/scala/meta/tests/api/SurfaceSuite.scala, tests/jvm/src/test/scala/scala/meta/tests/cli/CliSuite.scala, tests/jvm/src/test/scala/scala/meta/tests/semanticdb/ExpectSuite.scala, tests/jvm/src/test/scala/scala/meta/tests/semanticdb/MetacScalaLibrary.scala, tests/shared/src/test/scala/scala/meta/tests/prettyprinters/PublicSuite.scala
Having these guys in a non-internal package was an oversight.
=> Remove metac/metap/metacp from the public API

notes/quasiquotes.md
source: https://github.github.com/gfm/#example-193
=> Escape | in markdown table

tests/jvm/src/test/scala/scala/meta/tests/metacp/BaseMetacpSuite.scala, tests/jvm/src/test/scala/scala/meta/tests/metacp/MetacpCrashSuite.scala
No crashes :tada:
I've looked (well, stared) at the output of `metap` for a while and I didn't notice anything crazy, although it's my first time taking a close look to that output, so I may have easily missed some bad things.
=> Add Play framework to MetacpCrashSuite

langmeta/langmeta/shared/src/main/scala/org/langmeta/semanticdb/Symbol.scala, tests/jvm/src/test/scala/scala/meta/tests/semanticdb/SymbolSuite.scala
=> Fail when parsing multi symbols

semanticdb/metacp/src/main/scala/scala/meta/internal/metacp/Main.scala
Once processing completes, the jar files are atomically moved to the
destination cache jar. This prevents concurrent clients from reading
half-processed cached jars.
=> Make metacp write to temporary files during processing.

semanticdb/metacp/src/main/scala/scala/meta/internal/metacp/Main.scala, semanticdb/metacp/src/main/scala/scala/meta/internal/scalacp/Scalalib.scala, tests/jvm/src/test/resources/scalalib.expect, tests/jvm/src/test/scala/scala/meta/tests/metacp/MetacpCacheSuite.scala
=> Add scala.Singleton trait to synthesized definitions

RELEASING.md, bin/test-release.sh, semanticdb/semanticdb/guide.md
- Update guide to latest output
- Update release instructions
- Update test-release to use full cross-version metac
Fixes #1613
=> Post 4.0.0-M4 cleanups [ci skip]

semanticdb/semanticdb3/semanticdb3.md
Looks like I forgot to update the spec when implementing singleton types 😅
=> Update the spec regarding singleton types

CONTRIBUTING.md, build.sbt, project/Build.scala, semanticdb/metacp/src/main/scala/scala/meta/internal/javacp/Javacp.scala, semanticdb/metacp/src/main/scala/scala/meta/internal/metacp/Main.scala, semanticdb/metacp/src/main/scala/scala/meta/internal/scalacp/MissingSymbolException.scala, semanticdb/metacp/src/main/scala/scala/meta/internal/scalacp/Scalalib.scala, semanticdb/metacp/src/main/scala/scala/meta/internal/scalacp/SymbolInformationOps.scala, semanticdb/metacp/src/main/scala/scala/meta/internal/scalacp/SymbolOps.scala, semanticdb/metacp/src/main/scala/scala/meta/internal/scalacp/TypeOps.scala, semanticdb/metacp/src/main/scala/scala/meta/metacp/Settings.scala, semanticdb/semanticdb/src/main/scala/scala/meta/internal/semanticdb/Scala.scala, semanticdb/semanticdb3/guide.md, tests/jvm/src/main/scala/scala/meta/tests/metacp/Jars.scala, tests/jvm/src/main/scala/scala/meta/tests/metacp/Libraries.scala, tests/jvm/src/test/resources/metac-metacp.diff, tests/jvm/src/test/resources/metacp.expect, tests/jvm/src/test/resources/metacp.undefined, tests/jvm/src/test/resources/scalalib.expect, tests/jvm/src/test/scala/scala/meta/tests/cli/CliSuite.scala, tests/jvm/src/test/scala/scala/meta/tests/metacp/ConvertSuite.scala, tests/jvm/src/test/scala/scala/meta/tests/metacp/MetacpErrorSuite.scala, tests/jvm/src/test/scala/scala/meta/tests/metacp/MetacpOps.scala, tests/jvm/src/test/scala/scala/meta/tests/semanticdb/ExpectSuite.scala, tests/jvm/src/test/scala/scala/meta/tests/semanticdb/SymbolSuite.scala
See commit messages for details.
=> Several followup fixes from #1660

build.sbt, semanticdb/metacp/src/main/scala/scala/meta/internal/classpath/ClasspathIndex.scala, semanticdb/symtab/src/main/scala/scala/meta/internal/symtab/GlobalSymbolTable.scala, tests/jvm/src/test/scala/scala/meta/tests/symtab/SymbolTableSuite.scala
- handle multiple directory entries with the same package name
- handle lookups for members in `_empty_/` package
=> Fix two symtab bugs

semanticdb/integration/src/main/scala/example/Selfs.scala, semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/SymbolOps.scala, tests/jvm/src/test/resources/metac.expect, tests/jvm/src/test/resources/metacp.expect, tests/jvm/src/test/resources/metai.expect
=> Don't persist wildcard self parameters

build.sbt, semanticdb/semanticdb3/guide.md
=> Prepare build for v4.0.0-M6

semanticdb/semanticdb3/semanticdb3.md
=> A few specification cleanups

bench/suite/src/main/scala/scala/meta/internal/bench/Metacp.scala, semanticdb/cli/src/main/scala/scala/meta/cli/Reporter.scala, semanticdb/cli/src/main/scala/scala/meta/internal/cli/Args.scala, semanticdb/cli/src/main/scala/scala/meta/internal/cli/Job.scala, semanticdb/cli/src/main/scala/scala/meta/internal/cli/package.scala, semanticdb/metac/src/main/scala/scala/meta/cli/Metac.scala, semanticdb/metacp/src/main/scala/scala/meta/cli/Metacp.scala, semanticdb/metacp/src/main/scala/scala/meta/internal/metacp/Main.scala, semanticdb/metacp/src/main/scala/scala/meta/metacp/Result.scala, semanticdb/metacp/src/main/scala/scala/meta/metacp/Settings.scala, semanticdb/metai/src/main/scala/scala/meta/cli/Metai.scala, semanticdb/metai/src/main/scala/scala/meta/internal/metai/Main.scala, semanticdb/metai/src/main/scala/scala/meta/metai/Result.scala, semanticdb/metai/src/main/scala/scala/meta/metai/Settings.scala, semanticdb/metap/src/main/scala/scala/meta/cli/Metap.scala, semanticdb/metap/src/main/scala/scala/meta/internal/metap/Main.scala, semanticdb/metap/src/main/scala/scala/meta/metap/Settings.scala, semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/SemanticdbPipeline.scala, tests/jvm/src/test/scala/scala/meta/tests/api/SurfaceSuite.scala, tests/jvm/src/test/scala/scala/meta/tests/metacp/ConvertSuite.scala, tests/jvm/src/test/scala/scala/meta/tests/metacp/MetacpErrorSuite.scala, tests/jvm/src/test/scala/scala/meta/tests/metai/MetaiErrorSuite.scala, tests/jvm/src/test/scala/scala/meta/tests/semanticdb/ExpectSuite.scala, tests/shared/src/test/scala/scala/meta/tests/prettyprinters/PublicSuite.scala
@olafurpg This is the most significant of the pull requests that I merged while you were away. You'll want to take a look at this one, since I imagine there may be a few controversial decisions in here.
=> Assorted improvements to metacp and metai that make everything work on a case study project

project/plugins.sbt
=> upgrade sbt-jdi-tools to a JDK 9+ friendly version

appveyor.yml, semanticdb/semanticdb3/guide.md
=> Update guide for latest milestone

notes/trees.md
See https://github.com/scalameta/scalameta/pull/1380
=> Add documentation for Trees.scala

scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
See scalameta#1848. CLA signed.
=> Refactored internal.prettyprinters.TreeSyntax to avoid name convention warnings from Graal

scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala, tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala
=> #1864: Quote terms with leading numerics

scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala, tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala
=> Prettyprint Term.Eta as postfix expression

project/plugins.sbt
Super tiny change, but I've noticed 0.9.0 final is out.
=> Update scalapb version

semanticdb/semanticdb/src/main/scala/scala/meta/internal/semanticdb/package.scala
in the course of working on https://github.com/scala/community-builds/issues/935
I happened to run into this
=> improve an error message

.travis.yml, build.sbt, project/Versions.scala, sbt
I've tested this locally against 2.13.1-bin-a3791d4 (the current release candidate) and tests work.
I'll leave this here for when 2.13.1 is out (supposedly, next week)
=> Add support for 2.13.1

semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/TextDocumentOps.scala, tests/jvm/src/test/resources/example/Advanced.scala, tests/jvm/src/test/resources/example/Traits.scala, tests/jvm/src/test/resources/example/Types.scala, tests/jvm/src/test/resources/metac.expect
Not entirely sure it's the way to go, but the occurrence is saved for sure, the only problem is that it looks to be saved as reference and not definition.
@olafurpg Is this the way to go? Will try to look at how to make it def tomorrow.
Edit: Ok, added it to `binders` set - that's seems to define what is a definition
=> Save occurence of anonymous class symbol

.github/workflows/ci.yml, .github/workflows/release-drafter.yml
Fixes deprecated release drafter bot
=> Release Drafter workflow

semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/InputOps.scala
After upgrading to a recent Scalameta version we started seeing the
following error in CI on Windows
```
[error] java.lang.RuntimeException: 'D:\a\scalafix\scalafix\scalafix-tests\output\src\main\scala\tests\testpkg\package.scala' is not located within sourceroot 'd:\a\scalafix\scalafix'.
```
This commit should fix that issue by changing the logic for detecting if
a path is inside another directory.
=> Make URI logic for relative paths work on Windows

.scalasteward.conf
This pr adds in the scala steward conf file and allows for updates monthly
=> Add in scala steward conf

website/core/Footer.js
=> List Scalameta projects in the scalameta.org footer

build.sbt
Should be fixed now by scalatest guys :crossed_fingers:
=> Remove scalacheck dependency - no longer needed

semanticdb/integration/src/main/scala/example/Issue2040.scala, semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/TextDocumentOps.scala, tests/jvm/src/test/resources/example/Issue2040.scala, tests/jvm/src/test/resources/metac.expect, tests/jvm/src/test/resources/metacp.expect
=> Fix #2040 Lost SymbolOccurrence info when produce semanticdb for implicit conversion with implicit params

.github/workflows/ci.yml, project/Versions.scala
=> Update to Scala 2.13.3

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/Scala213Suite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/TypeSuite.scala
=> Fix parsing minus in number literals

build.sbt
There's only one @gabro :wink:
=> Fix maxov developer id

scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/package.scala, tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala
=> Add "macro" as a keyword

scalameta/dialects/shared/src/main/scala/scala/meta/Dialect.scala, scalameta/dialects/shared/src/main/scala/scala/meta/dialects/package.scala, scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala
Fix "Type.Param with Name.Anonymous is not supported in Dotty"
=> Fix #1119 (Type.Param with Name.Anonymous is not supported in Dotty)

community-test/src/test/scala/CommunityDottySuite.scala, scalameta/dialects/shared/src/main/scala/scala/meta/Dialect.scala, scalameta/dialects/shared/src/main/scala/scala/meta/dialects/package.scala, scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/VarargParameterSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/EndMarkerSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala
=> Dotty support for lazy abstract values

semanticdb/integration/src/main/scala/example/Issue2144.scala, semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/TextDocumentOps.scala, tests/jvm/src/test/resources/example/Issue2144.scala, tests/jvm/src/test/resources/metac-metacp.diff, tests/jvm/src/test/resources/metac.expect, tests/jvm/src/test/resources/metacp.expect
Fixes https://github.com/scalameta/scalameta/issues/2144
=> Fix missing constructor named arguments

community-test/src/test/scala/CommunityDottySuite.scala, scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ExtensionMethodsSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala
- fix issue with operators with literal on the next line
- fix parsing of extension methods with a comment and no `:`
=> Fix remaining issues in Dotty codebase

community-test/src/test/scala/CommunityDottySuite.scala, scalameta/dialects/shared/src/main/scala/scala/meta/Dialect.scala, scalameta/dialects/shared/src/main/scala/scala/meta/dialects/package.scala, scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ControlSyntaxSuite.scala
This adds an ability to chain matches and use match with a dot.
=> Allow match to be used as operator

project/plugins.sbt
It should be fixed according to issue in sbt-assembly
=> Remove sbt-assembly workaround - fixed upstream

community-test/src/test/scala/CommunityDottySuite.scala
- bump dotty hash commit to contain scala3doc
- remove scala3doc as separate community-build
=> Remove scala3doc community build - merged into dotty

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala, scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyToken.scala, scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/ScalametaTokenizer.scala, scalameta/tokens/shared/src/main/scala/scala/meta/tokens/Api.scala, scalameta/tokens/shared/src/main/scala/scala/meta/tokens/Token.scala, tests/jvm/src/test/scala-2.12/scala/meta/tests/api/SurfaceSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/Scala213Suite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ExtensionMethodsSuite.scala
Based on https://github.com/lampepfl/dotty/issues/10076#issuecomment-723095528
=> Add extension as a keyword for Dotty

.dependabot.yml, .github/workflows/ci.yml, .github/workflows/release.yml, community-test/src/test/scala/CommunityDottySuite.scala, project/Mima.scala, scalameta/dialects/shared/src/main/scala/scala/meta/Dialect.scala, scalameta/dialects/shared/src/main/scala/scala/meta/dialects/package.scala, scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/package.scala, tests/jvm/src/test/scala-2.12/scala/meta/tests/api/SurfaceSuite.scala, tests/jvm/src/test/scala-2.12/scala/meta/tests/trees/ReflectionSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MatchTypeSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala
http://dotty.epfl.ch/docs/reference/new-types/match-types.html
=> Add type match

scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/ScalametaTokenizer.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/UnclosedTokenSuite.scala
Fixes https://github.com/scalameta/scalameta/issues/2169
=> Fix error reporting of unclosed slice interpolation

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
Because autoPos was now done inside `{}` this caused a regression in scalafmt and most likely parser positions changed.
=> Fix regression with positions in blocks

project/Mima.scala, scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala, tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala, tests/jvm/src/test/scala-2.13/scala/meta/tests/trees/ReflectionSuite.scala
- add common branch for import and export
- add fields for CaseTree
=> Update branches for scalameta trees

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/InlineSuite.scala
Transparent traits are described here: https://dotty.epfl.ch/docs/reference/other-new-features/transparent-traits.html
=> [Scala 3] Fix transparent traits

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/NewFunctionsSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/SignificantIndentationSuite.scala
The issues were found when using optional braces for scalafmt.
=> Fix issues with wrongly detected blocks

scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala
Fixes https://github.com/scalameta/scalameta/issues/2287
=> Allow typed tuple patterns

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala
Related to https://github.com/scalameta/scalafmt/issues/2216#issuecomment-821828519
=> Fix given tree position to include modifiers

scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/package.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ExportImportSuite.scala
Found while testing https://gitlab.com/heksesang/scala3-derivation.git
=> Allow Export to be a top level statement

build.sbt
Step towards fixing https://github.com/scalameta/scalameta/issues/2294
and https://github.com/com-lihaoyi/Ammonite/issues/1177
=> Move auto-generated ScalaPB classes to common module.

project/plugins.sbt
Succeds https://github.com/scalameta/scalameta/pull/2307
=> Update compiler plugin to 0.11.1

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, tests/shared/src/test/scala-2.13/scala/meta/tests/tokenizers/TokensPositionSuite.scala
=> Fix position for anonymous trait ctor

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala
Connected to https://github.com/scalameta/scalafmt/issues/2478
=> [Scala 3] Include inline in Term.Match tree position

scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala
Fixes https://github.com/scalameta/scalameta/issues/2317
=> Always add () for constructor invocations when printing

.github/workflows/ci.yml, .github/workflows/release-drafter.yml, .github/workflows/release.yml, README.md, RELEASING.md, build.sbt, docs/semanticdb/guide.md, docs/semanticdb/specification.md, semanticdb/semanticdb3/guide.md, semanticdb/semanticdb3/semanticdb3.md, website/siteConfig.js
This requires also changing the primary branch in the repo.
=> Update master to main branch

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala
=> Parser: allow partial function in implicit closuse

tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/Scala3SyntaxSuite.scala, tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala
Also, add class/trait/etc tests with modifiers.
=> SyntacticSuite: use assertEquals, to show errors

scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
They have many components, some frequently missing.
=> TreeSyntax: use Show.repeat with template types

scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/package.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/Scala3SyntaxSuite.scala, tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala
Fixes https://github.com/scalameta/scalameta/issues/2372
=> Make sure the new Scala 3 keywords are backticked

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ControlSyntaxSuite.scala
=> [Scala3] While condition - accept multiply exprs in parens

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala
=> [Scala3] Trimmed pos - handle case with single Trivia token

scalameta/trees/shared/src/main/scala/scala/meta/internal/Scaladoc.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/ScaladocParserSuite.scala
=> Scaladoc: fix label/desc for throws/version/since

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala
Fixes https://github.com/scalameta/scalameta/issues/2406
=> Fix implicit closures inside match cases

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/GivenUsingSuite.scala
Follow up from https://github.com/lampepfl/dotty/pull/12107
=> [Scala 3] Add support for streamlined givens

project/plugins.sbt
This should unblock the other PRs from Scala Steward.
=> Update ScalaJS to 1.6.0

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
Addresses [this comment](https://github.com/scalameta/scalameta/pull/2426#discussion_r673581130)
=> [Scala3] Count indentation - minor fix

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/SignificantIndentationSuite.scala
=> Fix multiline comments + significant-indentation processing

scalameta/common/shared/src/main/scala/org/scalameta/data/data.scala, scalameta/common/shared/src/main/scala/scala/meta/internal/transversers/transformer.scala, scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, semanticdb/metacp/src/main/scala/scala/meta/internal/scalacp/SymbolOps.scala, semanticdb/metacp/src/main/scala/scala/meta/internal/scalacp/Synthetics.scala, semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/SymbolOps.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/BaseDottySuite.scala
follow advice issued by `-Xsource:3`
(this came up at https://github.com/scala/scala-dev/issues/769)
=> minor code improvement

semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/TypeOps.scala
Fixes https://github.com/scalameta/scalameta/issues/2475
=> Ignore wildcard type for semanticdb

.scalafmt.conf, semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/TextDocumentOps.scala
Until https://github.com/scalameta/scalameta/pull/2468 is merged
=> Revert scalafmt to 2.7.5 to be able to format code

scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/CharArrayReader.scala, scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MacroSuite.scala, tests/shared/src/test/scala/scala/meta/tests/tokenizers/TokenizerSuite.scala
Fixes https://github.com/scalameta/scalameta/issues/2482
=> Allow space betwen macro splice/quote and braces

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala
Fixes https://github.com/scalameta/scalameta/issues/2498
=> Allow type apply to follow Term.Interpolation

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala
=> [Scala3] Fix PolyFunction type in match type

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ControlSyntaxSuite.scala
=> ScalametaParser: handle indented scala3 TryWithHandler

.scalafmt.conf
Reverts scalameta/scalameta#2525
=> Revert "Update scalafmt-core to 3.2.1"

scalameta/trees/shared/src/main/scala/scala/meta/internal/Scaladoc.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/ScaladocParserSuite.scala
=> Scaladoc: rename sequence parameters in plural

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/testkit/jvm/src/main/scala/scala/meta/testkit/Corpus.scala, scalameta/testkit/jvm/src/test/scala/scala/meta/testkit/ScalametaParserProperties.scala, scalameta/testkit/shared/src/main/scala/scala/meta/testkit/StructurallyEqual.scala, scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/Chars.scala, scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/XmlParser.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/BasePositionSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/AndOrTypesSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/EnumSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ExtensionMethodsSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/GivenUsingSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/InlineSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MacroSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala
=> Scaladoc: edit manually, to prepare for formatting

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
=> ScalametaParser: various refactoring to prepare for indented comments

scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/ScalametaTokenizer.scala
=> ScalametaTokenizer: refactor pushing tokens

project/Mima.scala, scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/ScalametaTokenizer.scala, scalameta/tokens/shared/src/main/scala/scala/meta/tokens/Token.scala
=> Tokens: accept custom BOF/EOF start offset

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
=> ScalametaParser: simplify parseRule invocations

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
That will cover zero-width tokens such as BOF/EOF. Helps with #2155.
=> ScannerTokens: always cache the token start

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
There is an outer autoPos which would override anyway.
=> ScalametaParser.simpleType: don't set pos twice

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
Because of parameter shadowing, it was setting position using an inner Option[Type] rather than the outer type as all the other cases (and the original Type.Compound code which preceded this implementation). Also, use copyPos for entire patternTyp.loop.
=> ScalametaParser: fix bug with Type.Refine position

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/PlaceholderChecks.scala, tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala, tests/jvm/src/test/scala-2.13/scala/meta/tests/trees/ReflectionSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/DefnSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/GivenUsingSuite.scala, tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala
=> ScalametaParser: wrap in AnonymousFunction if need

scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala
=> LegacyScanner: refactor getLitChars

scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala
Also inline into it the no longer needed getIdentOrOperatorRest.
=> LegacyScanner: refactor getIdentRest

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/package.scala
=> Trees: merge implicit extensions for Name trees

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
=> ScalametaParser: make UnfinishedInfix custom

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
=> ScalametaParser: rename infixTypeXxx methods

scalameta/dialects/shared/src/main/scala/scala/meta/Dialect.scala, scalameta/dialects/shared/src/main/scala/scala/meta/dialects/package.scala, scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/PatSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/TypeSuite.scala
=> Dialect: add useInfixTypePrecedence flag in scala3

build.sbt
https://www.scala-lang.org/blog/2021/02/16/preventing-version-conflicts-with-versionscheme.html
=> advertize version scheme defined in COMPATIBILITY.md

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
Instead of trying to get a statement and then pivoting to a self, do the opposite. That way, parsing for first and later statements will be consistent. Fixes #1776 and similar.
=> ScalametaParser: try parse self in template first

scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala, tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala
=> Fix pretty-printing of 'using' param list in primary ctor

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/ParentChecks.scala, tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala
=> ScalametaParser: allow repeated in `apply { ... }`

scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/InternalTrees.scala, tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala
=> InternalTrees: in tokens, handle Lit.String

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
We will similarly implement an updated version of toLhs so let's have some consistency.
=> ScalametaParser: inline the unTuple invocations

scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/PlaceholderChecks.scala, tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala
=> PlaceholderChecks: include ApplyUnary

scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala, tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala
=> LegacyScanner: make sure no line breaks in CHARLIT

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/TemplateSuite.scala
Fixes https://github.com/scalameta/scalameta/issues/2741
=> Don't throw Invariant exception when extending .type

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
=> ScalametaParser: no double autopos in modifier

.jvmopts
The release job keeps timing out due to GC issues, not sure exactly what is going on.
=> chore: Try and tweak CI opts

tests/shared/src/test/scala/scala/meta/tests/parsers/PatSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/TypeSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/PatSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/TypeSuite.scala
=> Use assert rather than unapply in tests

scalameta/dialects/shared/src/main/scala/scala/meta/Dialect.scala, scalameta/dialects/shared/src/main/scala/scala/meta/dialects/package.scala, scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
It replaces misnamed allowQuestionMarkPlaceholder. Helps with #2807.
=> Dialect: add allowQuestionMarkAsTypeWildcard

scalameta/dialects/shared/src/main/scala/scala/meta/Dialect.scala, scalameta/dialects/shared/src/main/scala/scala/meta/dialects/package.scala, tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala, tests/shared/src/test/scala/scala/meta/tests/prettyprinters/PublicSuite.scala
=> Dialect: add intermediate scala3 dialects

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, tests/shared/src/test/scala/scala/meta/tests/quasiquotes/ErrorSuite.scala
=> ScalametaParser: minor refactor in params parsing

tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MatchTypeSuite.scala
It demonstrates the current bug in placeholder-vs-wildcard handling.
=> Add test with underscores in match type

notes/quasiquotes.md, tests/shared/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala
=> Add test with quasiquote template matching

scalameta/dialects/shared/src/main/scala/scala/meta/Dialect.scala, scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/FeverBracesSuite.scala, tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala, tests/shared/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala
More information: https://dotty.epfl.ch/docs/reference/other-new-features/indentation.html#variant-indentation-marker--for-arguments
=> feature: Add support for fewer braces

semanticdb/metap/src/main/scala/scala/meta/internal/metap/SymbolInformationPrinter.scala, semanticdb/semanticdb/semanticdb.proto
Close https://github.com/scalameta/scalameta/issues/2403
Originally discussed in https://github.com/scalameta/scalameta/pull/2414 https://github.com/scalameta/scalameta/issues/2403
---
for scala3 https://github.com/lampepfl/dotty/pull/16056
=> feat: Add support for LambdaType (corresponds to Scala3 HKTypeLambda)

.github/workflows/ci.yml, bin/test-release.sh, project/Versions.scala, semanticdb/scalac/library/src/main/scala-2.11/scala/meta/internal/semanticdb/scalac/CommandLineParser.scala, semanticdb/scalac/library/src/main/scala-2.12/scala/meta/internal/semanticdb/scalac/CommandLineParser.scala, semanticdb/scalac/library/src/main/scala-2.13.9/scala/meta/internal/semanticdb/scalac/SemanticdbReporter.scala, semanticdb/scalac/library/src/main/scala-2.13.9/scala/meta/internal/semanticdb/scalac/VersionCompilerOps.scala, semanticdb/scalac/library/src/main/scala-2.13/scala/meta/internal/semanticdb/scalac/CommandLineParser.scala, tests/jvm/src/test/scala/scala/meta/tests/semanticdb/SemanticdbSuite.scala
For now just a draft with snapshot version to check that everything is fine
=> Add Scala 2.13.9 support

scalameta/dialects/shared/src/main/scala/scala/meta/Dialect.scala, scalameta/dialects/shared/src/main/scala/scala/meta/dialects/package.scala, tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala, tests/jvm/src/test/scala/scala/meta/tests/prettyprinters/RegressionSyntaxSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MatchTypeSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/PatSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/TypeSuite.scala, tests/shared/src/test/scala/scala/meta/tests/prettyprinters/PublicSuite.scala, tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala
=> Dialect: add scala3x, move type placeholder there

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/PlaceholderChecks.scala, tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala, tests/jvm/src/test/scala-2.13/scala/meta/tests/trees/ReflectionSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MatchTypeSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/TypeSuite.scala
Wraps types referring to AnonymousParam. Helps with #2807.
=> Trees: add AnonymousLambda

scalameta/common/shared/src/main/scala/scala/meta/internal/trees/ast.scala
=> ast: refactor unapply, copy and privateCopy

scalameta/common/shared/src/main/scala/scala/meta/internal/trees/NamerMacros.scala, scalameta/common/shared/src/main/scala/scala/meta/internal/trees/ast.scala, scalameta/common/shared/src/main/scala/scala/meta/internal/trees/branch.scala, scalameta/common/shared/src/main/scala/scala/meta/internal/trees/root.scala
=> ast: allow extra copy methods to be defined

scalameta/common/shared/src/main/scala/scala/meta/internal/trees/ast.scala
=> ast: refactor getting and setting fields

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/LazyTokenIterator.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/FeverBracesSuite.scala
It's not an ideal solution, but regions are a bit of black magic unfortunately. The other solutions might be more complex then this.
Fixes https://github.com/scalameta/scalameta/issues/2900
=> bugfix: Fix issues with fewer braces and partial functions

scalameta/common/shared/src/main/scala/scala/meta/internal/trees/ast.scala
This way, we'll remember to remove older field annotations before a major version release (which allows binary non-compatibility).
=> ast: check annotations use current major version

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/ParentChecks.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/PlaceholderChecks.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/package.scala, scalameta/trees/shared/src/main/scala/scala/meta/trees/Api.scala, tests/js/src/test/scala/scala/meta/tests/parsers/JSFacadeSuite.scala, tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala, tests/jvm/src/test/scala-2.13/scala/meta/tests/trees/ReflectionSuite.scala, tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala, tests/shared/src/test/scala-2.13/scala/meta/tests/tokenizers/TokensPositionSuite.scala, tests/shared/src/test/scala/scala/meta/tests/contrib/TreeOpsSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/BasicPositionSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/PatSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/SbtSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/TypeSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/XmlSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/PatSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/TypeSuite.scala, tests/shared/src/test/scala/scala/meta/tests/quasiquotes/ErrorSuite.scala, tests/shared/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala, tests/shared/src/test/scala/scala/meta/tests/transversers/SimpleTraverserSuite.scala, tests/shared/src/test/scala/scala/meta/tests/transversers/TraverserSuite.scala
=> Trees: use Type.ArgClause, not List[Type]

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
Some allow `using` and some do not.
=> ScalametaParser: refactor argument expr parsing

scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
The introduction of `Name.Placeholder` has made it possible.
=> TreeSyntax: simplify Term.FunctionTerm

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/ParentChecks.scala, scalameta/trees/shared/src/main/scala/scala/meta/trees/Api.scala, tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala, tests/jvm/src/test/scala-2.13/scala/meta/tests/trees/ReflectionSuite.scala, tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala, tests/shared/src/test/scala-2.13/scala/meta/tests/tokenizers/TokensPositionSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/BaseDottySuite.scala, tests/shared/src/test/scala/scala/meta/tests/quasiquotes/DottySuccessSuite.scala, tests/shared/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala
=> Trees: use Type.FuncParamClause in Type.FunctionType

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala, tests/jvm/src/test/scala-2.13/scala/meta/tests/trees/ReflectionSuite.scala, tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala, tests/shared/src/test/scala-2.13/scala/meta/tests/tokenizers/TokensPositionSuite.scala, tests/shared/src/test/scala/scala/meta/tests/prettyprinters/TreeStructureSuite.scala, tests/shared/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala
=> Trees: use Term.ParamClause in Term.FunctionTerm

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
Invoke it while parsing rather than after. Needed by #2929.
=> ScalametaParser: Repeated check of ParamClause

semanticdb/scalac/library/src/main/scala-2.13/scala/meta/internal/semanticdb/scalac/SemanticdbReporter.scala
In https://github.com/scalameta/scalameta/pull/2903 I somehow used the wrong SemanticdbReporter instead of the one needed for the newest Scala 2.13.x versions I used the one for 2.13.0.
Fixes https://github.com/scalameta/scalameta/issues/2993
=> bugfix: Save warnings to semanticdb

tests/shared/src/test/scala/scala/meta/tests/parsers/Scala213Suite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/BaseDottySuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ControlSyntaxSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/InfixSuite.scala
=> Add tests with leading infix operators

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
=> ScalametaParser: refactor InfixContext.reduceStack

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/package.scala
=> Trees: refactor Name tree implicit extensions

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ControlSyntaxSuite.scala
Also, a minor refactor splitting isLeadingInfixOperator into several methods checking various requirements. For #2880.
=> ScannerTokens: include backquoted as leading infix

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
Extract some logic for later reuse, clean up the code. For #2880.
=> ScalametaParser: refactor postfixExpr

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
=> ScalametaParser: use tryParse, no explicit forking

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/LazyTokenIterator.scala
That way, nextToken no longer depends on any instance variables except tokens. This will allow us to move this method to ScannerTokens next. For #3031.
=> LazyTokenIterator: pass current token to nextToken

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
=> ScalametaParser: slightly rewrite atPosWithBody

scalameta/common/shared/src/main/scala/scala/meta/classifiers/Api.scala, scalameta/contrib/shared/src/main/scala/scala/meta/contrib/TokenClasses.scala, scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/LazyTokenIterator.scala, scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala, tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala
=> Token API: extend .is to check multiple

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/LazyTokenIterator.scala
=> LazyTokenIterator: refactor nextToken.nonTrivial

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/LazyTokenIterator.scala, scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala, scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/TokenIterator.scala
=> LazyTokenIterator: keep previous TokenRef

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
Rather than requiring a separate call to nextToken which will in reality repeat the same calculations but with remaining SepRegions, let's add those subsequent token refs via `.next` field. For #3031.
=> ScannerTokens: for outdent, precompute next tokens

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala, tests/shared/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala
Do not hide placeholder assignment.
=> Trees: turn Defn.Var into proper Tree.WithBody

project/Mima.scala, scalameta/common/shared/src/main/scala/org/scalameta/adt/Liftables.scala, scalameta/common/shared/src/main/scala/scala/meta/internal/trees/ast.scala
This is an internal type, and we are going to introduce more types for each changed version. Helps with #3067.
=> ast: rename `internal.Impl` as `Latest`

scalameta/common/shared/src/main/scala/scala/meta/internal/trees/ast.scala
=> ast: move Version into ReplacedField, sort

scalameta/common/shared/src/main/scala/scala/meta/internal/trees/Version.scala, scalameta/common/shared/src/main/scala/scala/meta/internal/trees/ast.scala
=> ast: make version and its parsing public

tests/shared/src/test/scala/scala/meta/tests/parsers/ModSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/ParseSuite.scala
It will return the intercepted exception error message.
=> ParseSuite: implement interceptParseError

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
This will allow us to differentiate the first parameter from subsequent ones, to ensure `implicit` is handled properly and is not duplicated.
=> ScalametaParser: pass index to commaSeparated

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
Subsequently, we will modify the `sepRegion` list and will then need to provide the modified list to various method instead.
=> ScannerTokens: pass regions as parameter

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
When encountering a closing delimiter, remove any regions which came after we saw the opening delimiter, as a garbage collection step.
=> ScannerTokens: remove regions before closing delim

scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala, tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala
=> Fixed .syntax on ifs with an inner if without an else

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/ModSuite.scala
=> ScalametaParser: relax modifier check in param

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala, scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/SepRegion.scala
=> SepRegion: add a new trait CanProduceLF

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
=> ScannerTokens: skip regions when outdenting

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
=> ScannerTokens: group match tokens, left w/ right

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ControlSyntaxSuite.scala, tests/shared/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala
=> ScalametaParser: allow block as catch handler

tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/FewerBracesSuite.scala
=> Add fewer-braces tests with empty argument

tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ErasedDefsSuite.scala
=> Add initial tests for erased defs

scalameta/common/shared/src/main/scala/scala/meta/internal/trees/ast.scala
Even though in the current version there might be multiple params, in a previous version we might be trying to output with no params, and in that case the unapply should return a boolean, just like in case when there are no parameters to start with.
=> ast: bugfix, correct unapply with empty params

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/AndOrTypesSuite.scala
=> ScalametaParser: allow leading infix in types

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
- change convertToParam, to make sure that type is only parsed in one place, and that not just `using` is allowed as a possible Mod
- also, return Option[] in convertToParam, to avoid checking that it looks like lambda before parsing it as lamda parameter
For #2774.
=> ScalametaParser: change like-lambda param parsing

tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ErasedDefsSuite.scala
=> ErasedDefsSuite: add a test with dependent func

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
Add attribute methods to TemplateOwner.
=> ScalametaParser: use TemplateOwner in parsing

scalameta/dialects/shared/src/main/scala/scala/meta/Dialect.scala, scalameta/dialects/shared/src/main/scala/scala/meta/dialects/package.scala, tests/shared/src/test/scala/scala/meta/tests/prettyprinters/PublicSuite.scala
=> Dialect: add `allowErasedDefs`

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/SoftKeywords.scala, scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala, tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala, tests/jvm/src/test/scala-2.13/scala/meta/tests/trees/ReflectionSuite.scala, tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala
=> Trees: define KwErased, Mod.Erased, Type.FuncParam

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ErasedDefsSuite.scala
=> ScalametaParser: allow `erased` keyword in params

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ErasedDefsSuite.scala
=> ScalametaParser: allow `erased` as defn modifier

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala, scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/SepRegion.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/SignificantIndentationSuite.scala
=> ScannerTokens: infer "fewer braces" indent

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, tests/shared/src/test/scala/scala/meta/tests/quasiquotes/ErrorSuite.scala
Possibly helps with debugging #3063.
=> ScalametaParser: expand "pattern must be a value"

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/LazyTokenIterator.scala, scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/TokenIterator.scala
=> TokenIterator: remove unused observeIndented()

community-test/src/test/scala/CommunityDottySuite.scala
=> CommunityDottySuite: remove excluded dotty paths

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala
=> ScalametaParser: recurse on annotation/ascription

community-test/src/test/scala/CommunityDottySuite.scala
=> CommunityDottySuite: test all last patch versions

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ExtensionMethodsSuite.scala
=> ScannerTokens: extension could follow self type

build.sbt, project/plugins.sbt, scalameta/contrib/shared/src/main/scala/scala/meta/contrib/DocToken.scala, scalameta/contrib/shared/src/main/scala/scala/meta/contrib/ScaladocParser.scala, scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScaladocParser.scala, scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala, scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/XmlParser.scala
=> SBT: shade geny and fastparse modules

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala
=> ScalametaParser: copy AnonymousLambda type, too

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/CommonTrees.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/SignificantIndentationSuite.scala
=> ScannerTokens: terminate template on comma

docs/trees/quasiquotes.md
=> Rm stale comment

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
This way, we will have explicit versions for LeftBrace and Indent.
=> ScalametaParser: refactor block() and blockExpr()

tests/jvm/src/test/scala-2.13/scala/meta/tests/semanticdb/ConfigSuite.scala, tests/jvm/src/test/scala-2.13/scala/meta/tests/semanticdb/JavacpSuite.scala, tests/jvm/src/test/scala-2.13/scala/meta/tests/semanticdb/PrintSuite.scala
=> SemanticDB tests: copy 2.12 to 2.13

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
This will allow us to add more specific syntax error messages later.
=> ScalametaParser: return Either in self()

build.sbt
Should solve https://github.com/scalameta/scalameta/issues/3314
=> improvement: Publish semanticdb generated sources

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/FewerBracesSuite.scala
=> ScalametaParser: allow fewer-braces in infix arg

tests/shared/src/test/scala/scala/meta/tests/tokenizers/BaseTokenizerSuite.scala, tests/shared/src/test/scala/scala/meta/tests/tokenizers/TokenizerSuite.scala
=> TokenizerSuite: refactor, add convenience methods

scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala, scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyTokenData.scala
It will later allow us to append unicode codepoints (multi-char). Helps with #3328.
=> tokenizers.LegacyScanner: use lang.StringBuilder

scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala
=> tokenizers.LegacyScanner: look ahead only if need

scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/Chars.scala, scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala
=> tokenizers.Chars: check using int codepoints

scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/CharArrayReader.scala, scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala
Instead of clumsy lastUnicodeOffset and isUnicodeEscape, to signify that the codepoint actually spanned several character positions, let's just preserve the range of positions. Helps with #3328.
=> tokenizers.CharArrayReader: replace charOffset with range

scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/CharArrayReader.scala
- Do not mutate internal state when reading it
- Handle possible unicode escapes
- do not throw exceptions since we are catching them anyway
This approach will allow us to handle surrogate characters in the next commit, by reading a second character if the first requires it.
Helps with #3328.
=> tokenizers.CharArrayReader: read a char at offset

scalameta/inputs/shared/src/main/scala/scala/meta/internal/inputs/InternalInput.scala
connected to: https://github.com/scalameta/metals/issues/5369
=> bugfix: support carriage return

scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/CharArrayReader.scala, scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala, tests/shared/src/test/scala/scala/meta/tests/tokenizers/TokenizerSuite.scala
=> tokenizers.CharArrayReader: allow surrogate pairs

scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/PlaceholderChecks.scala, tests/shared/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala
=> PlaceholderChecks: don't access field if Quasi

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/FewerBracesSuite.scala
=> ScannerTokens: fix leading infix with fewer braces

scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/CharArrayReader.scala
To guarantee that the method doesn't mutate internal state. Helps with #3402.
=> CharArrayReader: move readUnicodeChar to companion

scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/CharArrayReader.scala, tests/shared/src/test/scala/scala/meta/tests/tokenizers/TokenizerSuite.scala
=> CharArrayReader: allow high-surrogate in squotes

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
=> ScalametaParser: in refinementInBraces, simplify

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
In the next commit, matching will happen sometimes on a shorter list. Helps with scalameta/scalafmt#3720.
=> ScannerTokens: use original regions, not matched

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
Scan the comment string from the end, until a newline is found, instead of doing a full scan from the beginning and resetting the indent upon every newline. Helps with scalameta/scalafmt#3720.
=> ScannerTokens: reimplement multilineCommentIndent

semanticdb/integration/src/main/scala/example/Issue5939Metals.scala, semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/TextDocumentOps.scala, tests/jvm/src/test/resources/example/Issue5939Metals.scala, tests/jvm/src/test/resources/metac.expect_2.12, tests/jvm/src/test/resources/metac.expect_2.13, tests/jvm/src/test/resources/metacp.expect_2.12, tests/jvm/src/test/resources/metacp.expect_2.13
https://github.com/scalameta/metals/issues/5939
=> fix: don't emit implicit conversion occurrence when qualifier in synthetic apply

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
- recurse over regions in case multiple can be removed
- remove unnecessary token match for `RegionDefType`
=> ScannerTokens: improve `getIfCanProduceLF`

tests/shared/src/test/scala/scala/meta/tests/parsers/PatSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/GivenUsingSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/PatSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/Scala3SyntaxSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/SignificantIndentationSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/TypeSuite.scala
I finally managed to get the tests running, I still need to tidy it up, but I am close to getting Scala 3 scalameta parser out.
=> refactor: Fix some of the remaining warnings and errors for Scala 3

tests/shared/src/test/scala/scala/meta/tests/parsers/ModSuite.scala
=> ModSuite: no implicit ParamClauseGroup conversion

scalameta/quasiquotes/shared/src/main/scala/scala/meta/internal/quasiquotes/ReificationMacros.scala
=> ReificationMacros: move extensions to class level

scalameta/common/shared/src/main/scala/scala/meta/internal/trees/ast.scala
=> ast: extract getDeferredModifiers method

scalameta/common/shared/src/main/scala/scala/meta/internal/trees/ast.scala
=> ast: define annotation for astField as val

scalameta/quasiquotes/shared/src/main/scala/scala/meta/internal/quasiquotes/ReificationMacros.scala
=> ReificationMacros: save `Hole.isTerm` as val

scalameta/common/shared/src/main/scala/scala/meta/internal/trees/ast.scala
=> ast: remove intermediate variable in method return

scalameta/common/shared/src/main/scala/org/scalameta/adt/Reflection.scala
=> adt.Reflection: remove unnecessary methods

scalameta/dialects/shared/src/main/scala/scala/meta/Dialect.scala
=> Dialect: improve isEquivalentTo

scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/InternalTrees.scala
=> InternalTree: clean up handling of origin

scalameta/common/shared/src/main/scala/scala/meta/internal/trees/ast.scala
=> ast: exclude the final apply call from apply body

scalameta/common/shared/src/main/scala/org/scalameta/adt/Reflection.scala
=> adt.Reflection: refactor `isField` extension

scalameta/quasiquotes/shared/src/main/scala/scala/meta/internal/quasiquotes/ReificationMacros.scala
=> ReificationMacros: extract methods creating holes

scalameta/quasiquotes/shared/src/main/scala/scala/meta/internal/quasiquotes/ReificationMacros.scala
=> ReificationMacros: simplify `metaInput`

scalameta/common/shared/src/main/scala/scala/meta/internal/trees/NamerMacros.scala, scalameta/common/shared/src/main/scala/scala/meta/internal/trees/ast.scala, tests/shared/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala
=> ast: define private fields with initial values

scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/InternalTrees.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/Origin.scala
=> Origin: add `position` method

scalameta/quasiquotes/shared/src/main/scala/scala/meta/internal/quasiquotes/ReificationMacros.scala
=> ReificationMacros: refactor instantiating dialect

scalameta/common/shared/src/main/scala/org/scalameta/adt/Reflection.scala
=> adt.Reflection: no `isPayload/isAuxiliary` methods

scalameta/quasiquotes/shared/src/main/scala/scala/meta/internal/quasiquotes/ReificationMacros.scala
This is one of key changes enabling storing of origin for quasiquotes. Helps with #3425.
=> ReificationMacros: lift origin, dialect and input

scalameta/common/shared/src/main/scala/org/scalameta/adt/Liftables.scala, scalameta/common/shared/src/main/scala/org/scalameta/adt/Reflection.scala
=> adt.Liftables: obtain latest version only for ast

scalameta/common/shared/src/main/scala/org/scalameta/adt/Reflection.scala
=> adt.Reflection: refactor prefix generation

tests/shared/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala
=> SuccessSuite: test origin of interp quasiquotes

tests/jvm/src/test/scala-2.13/scala/meta/tests/trees/ReflectionSuite.scala, tests/shared/src/test/scala/scala/meta/tests/TreeSuiteBase.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/SbtSuite.scala, tests/shared/src/test/scala/scala/meta/tests/prettyprinters/PublicSuite.scala, tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala, tests/shared/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala
=> Add more detailed test syntax comparisons

scalameta/dialects/shared/src/main/scala/scala/meta/Dialect.scala, scalameta/quasiquotes/shared/src/main/scala/scala/meta/internal/quasiquotes/ReificationMacros.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/Origin.scala, tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala
=> Origin: add flag enabling unquotes to ParsedSource

scalameta/quasiquotes/shared/src/main/scala/scala/meta/internal/quasiquotes/ReificationMacros.scala
=> ReificationMacros: construct sourceName if needed

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala, tests/shared/src/test/scala/scala/meta/tests/TreeSuiteBase.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/ParseSuite.scala, tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala
=> TreeSyntax: fix bug in interpolate syntax

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
The method implements common logic frequently used with another method, getFewerBracesArgOnColon.
=> ScalametaParser: add getFewerBracesApplyOnColon

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
Add OutdentInfo class which explicitly provides outdent instructions.
=> ScannerTokens: improve generating outdents

scalameta/common/shared/src/main/scala-2.11/scala/annotation/nowarn.scala, scalameta/quasiquotes/shared/src/main/scala/scala/meta/internal/quasiquotes/ReificationMacros.scala
=> ReificationMacros: nowarn if dialectOnly is unused

scalameta/common/shared/src/main/scala-2.11/scala/annotation/nowarn.scala, scalameta/quasiquotes/shared/src/main/scala/scala/meta/internal/quasiquotes/ReificationMacros.scala
Reverts scalameta/scalameta#3549
=> Revert "ReificationMacros: nowarn if dialectOnly is unused"

scalameta/quasiquotes/shared/src/main/scala/scala/meta/internal/quasiquotes/ReificationMacros.scala
Follow-up to #3549. Fixes #3546.
I do not remember why I made it `implicit`, and that's the only thing that I am still not sure about; if it was important, have to keep it and, perhaps, use that gpt4 suggestion of adding `val _ = dialectOnly` to avoid unused warnings.
=> ReificationMacros: no `dialectOnly` if use source

scalameta/quasiquotes/shared/src/main/scala/scala/meta/internal/quasiquotes/ReificationMacros.scala
=> ReificationMacros: dialect is implicit, use that

.github/workflows/release.yml
Otherwise we get failures https://github.com/scalameta/scalameta/actions/runs/8004989604
=> bugfix: Don't release Native nad Js when releasing semanticdb

tests/shared/src/test/scala/scala/meta/tests/parsers/DefnSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/SignificantIndentationSuite.scala
=> Test backquoted "leading infix" lookalike

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
=> ScalametaParser: add extra `expect[]` methods

scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
=> TreeSyntax: isEscapableSoftKeyword as map of Class

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/Keywords.scala, scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/SoftKeywords.scala
=> Keywords: extract common base for all SoftKeywords

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/VarargParameterSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala
=> ScalametaParser: define VarArgTypeParam matcher

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/Keywords.scala, scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/SoftKeywords.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/ModSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/TypeSuite.scala
=> Keywords: match for allowStarAsTypePlaceholder

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/Keywords.scala, scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/PatSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/PatSuite.scala
=> Keywords: match for pattern alternatives, or not

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/SoftKeywords.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala, tests/jvm/src/test/scala/scala/meta/tests/prettyprinters/RegressionSyntaxSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala
=> Keywords: match allowQuestionMarkAsTypeWildcard

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/Keywords.scala, scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala
=> Keywords: match star identifier

tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MacroSuite.scala
=> MacroSuite: split as separate tests, use shortcuts

scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
=> TreeSyntax: add methods to print a name backquoted

scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/InternalTrees.scala, scalameta/trees/shared/src/main/scala/scala/meta/trees/Origin.scala
In reality, they are non-trivial only for Origin.Parsed.
=> Origin: add {text,tokens}Opt methods

scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/InternalTrees.scala
=> InternalTrees: text/tokens lazy only if non-parsed

scalameta/contrib/shared/src/main/scala/scala/meta/contrib/DocToken.scala
=> contrib/DocToken: fix the label of a tag

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
=> ScalametaParser: group soft keywords in simpleType

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/SoftKeywords.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/TypeSuite.scala
=> SoftKeywords: fix bug in StarAsTypePlaceholder

.scalafmt.conf
=> scalafmt: group parameters, add an excludeFilter

.scalafmt.conf
=> scalafmt: upgrade version v3.8.1

.scalafmt.conf, semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/ReflectionToolkit.scala, tests/shared/src/test/scala/scala/meta/tests/prettyprinters/TreeSyntaxSuite.scala
=> scalafmt: avoid simple overflow

.scalafmt.conf, scalameta/parsers/js/src/main/scala/scala/meta/parsers/JSFacade.scala, scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala, semanticdb/metacp/src/main/scala/scala/meta/internal/javacp/JavaTypeSignature.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/InterleavedDeclSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/InterleavedDefnSuite.scala
=> scalafmt: enable SortModifiers with `styleGuide`

.scalafmt.conf, scalameta/common/shared/src/main/scala/scala/meta/internal/trees/quasiquote.scala, scalameta/quasiquotes/shared/src/main/scala/scala/meta/internal/quasiquotes/ReificationMacros.scala, tests/shared/src/test/scala/scala/meta/tests/classifiers/ClassifierSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/FewerBracesSuite.scala, tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala, tests/shared/src/test/scala/scala/meta/tests/quasiquotes/ErrorSuite.scala
=> scalafmt: don't ignore newlines in syntax

.scalafmt.conf, build.sbt, scalameta/common/shared/src/main/scala/org/scalameta/data/data.scala, scalameta/common/shared/src/main/scala/org/scalameta/invariants/package.scala, scalameta/common/shared/src/main/scala/scala/meta/internal/tokens/Chars.scala, scalameta/io/js/src/main/scala/java/nio/file/Paths.scala, scalameta/quasiquotes/shared/src/main/scala/scala/meta/internal/quasiquotes/ReificationMacros.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreePositions.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala, semanticdb/metacp/src/main/scala/scala/meta/internal/javacp/Javacp.scala, semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/ReflectionToolkit.scala, semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/TextDocumentOps.scala, tests/jvm/src/test/scala/scala/meta/tests/semanticdb/TargetedSuite.scala, tests/shared/src/test/scala/scala/meta/tests/inputs/FormatMessageSuite.scala, tests/shared/src/test/scala/scala/meta/tests/inputs/OffsetLineColumnSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala, tests/shared/src/test/scala/scala/meta/tests/tokenizers/TokenizerSuite.scala, tests/shared/src/test/scala/scala/meta/tests/transversers/TransformerSuite.scala
=> scalafmt: enable RedundantParens rewrite

.scalafmt.conf, build.sbt, scalameta/common/shared/src/main/scala/org/scalameta/internal/ImplTransformers.scala, scalameta/common/shared/src/main/scala/scala/meta/internal/tokens/Chars.scala, scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala, scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/XmlParser.scala, tests/shared/src/test/scala/scala/meta/tests/contrib/AnnotationExtractionTests.scala, tests/shared/src/test/scala/scala/meta/tests/contrib/ModExtractionTest.scala, tests/shared/src/test/scala/scala/meta/tests/contrib/StatExtractionTest.scala, tests/shared/src/test/scala/scala/meta/tests/contrib/StatReplacementTest.scala, tests/shared/src/test/scala/scala/meta/tests/contrib/StatSubtypeExtractionTest.scala
=> scalafmt: enable AvoidInfix rewrite

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
Also add a static method `toBlockRaw`.
=> ScalametaParser: rename block{WithinDelims,Raw}

.github/workflows/ci.yml, project/Versions.scala, project/plugins.sbt, semanticdb/scalac/library/src/main/scala-2.13.14/scala/meta/internal/semanticdb/scalac/SemanticdbReporter.scala
Fixes https://github.com/scalameta/scalameta/issues/3711
=> chore: Add support for Scala 2.13.14

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala, scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/SepRegion.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ControlSyntaxSuite.scala
=> ScannerTokens: use RegionForParens on LeftArrow

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MacroSuite.scala
resolves: https://github.com/scalameta/metals/issues/6483
=> fix: allow for type apply after splice

scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeStructure.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/CommonTrees.scala, tests/shared/src/test/scala/scala/meta/tests/prettyprinters/TreeStructureSuite.scala
=> TreeStructure: fix Lit.Char and Symbol

build.sbt, project/Mima.scala, scalameta/inputs/shared/src/main/scala/scala/meta/internal/inputs/package.scala, scalameta/io/js/src/main/scala/scala/meta/internal/io/PlatformFileIO.scala, scalameta/io/jvm/src/main/scala/scala/meta/internal/io/PlatformFileIO.scala, scalameta/io/native/src/main/scala/scala/meta/internal/io/PlatformFileIO.scala, scalameta/io/shared/src/main/scala/scala/meta/internal/io/FileIO.scala, scalameta/io/shared/src/main/scala/scala/meta/internal/io/InputStreamIO.scala, scalameta/io/shared/src/main/scala/scala/meta/internal/io/OutputStreamIO.scala, semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/package.scala, semanticdb/semanticdb/src/main/scala/scala/meta/internal/semanticdb/package.scala
=> Move protobuf code into semanticdb, from scalameta

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
Rather than starting next iteration from `curPos + 1`, again concluding that there's no non-trivial token nor meaningful whitespace, only then to recurse and call with `nextPos` anyway, let's do it right away.
=> ScannerTokens: set `nextPos` for NL/indent

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
Instead, use the equivalent `acceptIfAfterOptNL`. Helps with scalameta/metals#6552.
=> ScalametaParser: remove `tryAcceptWithOptLF`

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
That is, before assuming `(cond)` may be starting a more complex scala3 conditional expression.
Also, process scala2 fork first, as the other one is larger.
Helps with scalameta/metals#6552.
=> ScalametaParser: check `then`, `do` after `(cond)`

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
Helps with scalameta/metals#6552.
=> ScalametaParser: combine getting ctrl cond, body

scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala, scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/ScalametaTokenizer.scala, scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/package.scala
Move it from ScalametaTokenizer.
=> LegacyScanner: throw UnexpectedInputEndException

scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala, scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyTokenData.scala, scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/Reporter.scala, scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/ScalametaTokenizer.scala, scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/XmlParser.scala
Also, remove reporter and input from LegacyTokenData.
=> LegacyScanner: take an implicit Reporter parameter

scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala, scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyTokenData.scala, scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/ScalametaTokenizer.scala
Use strval instead of name, and lastOffset is unused.
=> LegacyTokenData: remove lastOffset, name

scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala
However, user must set at least one of them.
=> LegacyScanner: set curr/next endOffset if not set

scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala, scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/ScalametaTokenizer.scala
Currently, legacy string literal (STRINGLIT) tokens are emitted together with the quotes around them, as those are also included in the resulting Token.Constant.String.
On the other hand, when it comes to interpolation strings, the quotes are instead included in the Interpolation.Start and .End tokens, but there's an inconsistency in implementation.
The opening quotes are derived from the gap between INTERPOLATIONID and STRINGPART, the first two legacy tokens of an interpolation. The final legacy token of an interpolation is a STRINGLIT, which, however, does include the closing quotes, which later need to be adjusted for using a crude approximation which doesn't take into account possible escaping or unicode literals used to represent those quotes.
Let's change the implementation to …
=> LegacyScanner: no quotes in interpolation tokens

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/Keywords.scala, scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
=> ScannerTokens: turn StatSep etc. into a Function

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
=> ScalametaParser: use StatSeqEnd in more places

tests/shared/src/test/scala/scala/meta/tests/parsers/BasePositionSuite.scala
=> BasePositionSuite: fail so that location is shown

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
=> ScalametaParser: refactor checks for Defn.Def

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
=> ScannerTokens: don't match BOF/EOF in StatSep

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
=> ScalametaParser: use StatSep in additional places

tests/shared/src/test/scala/scala/meta/tests/parsers/BasePositionSuite.scala
=> BasePositionSuite: use `.text`, not `.syntax`

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/LazyTokenIterator.scala, scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala, scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/TokenIterator.scala
Emit a null token and detect in TokenIterator. Helps with #3856.
=> ScannerTokens: stop iterating in nextToken

tests/shared/src/test/scala/scala/meta/tests/TestHelpers.scala, tests/shared/src/test/scala/scala/meta/tests/TreeSuiteBase.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/BasePositionSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/ParseSuite.scala, tests/shared/src/test/scala/scala/meta/tests/tokenizers/BaseTokenizerSuite.scala
=> ParseSuite: assert over scanned tokens

tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/SignificantIndentationSuite.scala
=> SignificantIndentationSuite: leading-infix tests

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
=> ScannerTokens: derive maxPointPos in mkOutdentAt

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
Others will soon have an additional check. Helps with #3856.
=> ScalametaParser: check leading infix first

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/FewerBracesSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/NewFunctionsSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/TypeSuite.scala
=> ScalametaParser: Outdent can be stat separator

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
If we had only one Outdent, we didn't set a `next` token reference for it, unlike cases when we had multiple Outdents. Rectify this oversight. Helps with #3856.
=> ScannerTokens: non-trivial next after all Outdents

.scalafmt.conf, build.sbt, semanticdb/integration/src/main/scala-2.13/example/LeadingInfix.scala, tests/jvm/src/test/resources/example/LeadingInfix.scala, tests/jvm/src/test/resources/metac.expect_2.13, tests/jvm/src/test/resources/metacp.expect_2.13, tests/jvm/src/test/scala/scala/meta/tests/semanticdb/OccurrenceSuite.scala
=> Add semanticDB leading-infix tests with comments

build.sbt
Follow-up of https://github.com/scalameta/scalameta/pull/3747#discussion_r1651329969
=> publish semanticdb-shared only with binary version

tests/jvm/src/test/scala/scala/meta/tests/parsers/BootstrapSuite.scala, tests/shared/src/test/scala-2.12/meta/tests/dialects/DialectSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/BasicPositionSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/DeclSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/DefnSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/ImportSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/LitSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/MoreHelpers.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/PackageSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/PatSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/Scala210Suite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/Scala211Suite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/TemplateSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/UnclosedTokenSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/VarargParameterSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/WhitespaceSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/XmlSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/PatSuite.scala, tests/shared/src/test/scala/scala/meta/tests/prettyprinters/TreeSyntaxSuite.scala, tests/shared/src/test/scala/scala/meta/tests/tokenizers/BaseTokenizerSuite.scala, tests/shared/src/test/scala/scala/meta/tests/tokenizers/TokenizerSuite.scala, tests/shared/src/test/scala/scala/meta/tests/tokens/TokensSuite.scala, tests/shared/src/test/scala/scala/meta/tests/trees/InfrastructureSuite.scala, tests/shared/src/test/scala/scala/meta/tests/trees/TokensSuite.scala
=> Tests: define implicit dialect val, don't import

tests/shared/src/test/scala/scala/meta/tests/TreeSuiteBase.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/ImportSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/LitSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/ParseSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/TypeSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/XmlSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ExtensionMethodsSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/TypeSuite.scala, tests/shared/src/test/scala/scala/meta/tests/tokenizers/BaseTokenizerSuite.scala, tests/shared/src/test/scala/scala/meta/tests/tokenizers/TokenizerSuite.scala
=> Tests: convert explicit parameters to implicit

tests/shared/src/test/scala/scala/meta/tests/parsers/LitSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/ParseSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/TypeSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ControlSyntaxSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/EndMarkerSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/FewerBracesSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/GivenUsingSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/TypeSuite.scala, tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala
=> ParseSuite: parser takes dialect as implicit only

tests/shared/src/test/scala/scala/meta/tests/prettyprinters/QuasiSyntacticSuite.scala, tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala, tests/shared/src/test/scala/scala/meta/tests/prettyprinters/dotty/QuasiSyntacticSuite.scala, tests/shared/src/test/scala/scala/meta/tests/prettyprinters/dotty/SyntacticSuite.scala
=> SyntacticSuite: split by whether quasi or dotty

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/InternalTrees.scala, tests/shared/src/test/scala/scala/meta/tests/tokenizers/TokenizerSuite.scala
=> InternalTrees: prepare for additional changes

scalameta/inputs/shared/src/main/scala/scala/meta/inputs/Input.scala, tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala, tests/shared/src/test/scala/scala/meta/tests/prettyprinters/PublicSuite.scala
=> Input: refactor, add Proxy and Text traits

scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/ScalametaTokenizer.scala, scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/WhitespaceTokenizer.scala
=> ScalametaTokenizer: extract whitespace handling

scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/ScalametaTokenizer.scala, scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/WhitespaceTokenizer.scala, scalameta/tokenizers/shared/src/main/scala/scala/meta/tokenizers/TokenizerOptions.scala, tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala, tests/shared/src/test/scala/scala/meta/tests/TreeSuiteBase.scala, tests/shared/src/test/scala/scala/meta/tests/prettyprinters/PublicSuite.scala
=> ScalametaTokenizer: add tokenizer options

scalameta/inputs/shared/src/main/scala/scala/meta/internal/inputs/package.scala
Follows https://github.com/scalameta/scalameta/pull/3895
=> Input.Proxy: delegate syntax

tests/shared/src/test/scala/scala/meta/tests/contrib/StatReplacementTest.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/CommonTrees.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/DefnSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/ModSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/PackageSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/TemplateSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ControlSyntaxSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ErasedDefsSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/GivenUsingSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/InfixSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/InlineSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/NewFunctionsSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/SignificantIndentationSuite.scala, tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala, tests/shared/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala, tests/shared/src/test/scala/scala/meta/tests/trees/TokensSuite.scala
=> CommonTrees: add more shortcuts, like tplNoBody

scalameta/inputs/shared/src/main/scala/scala/meta/inputs/Input.scala
=> Input: add overload with actual TokenizerOptions

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/ParentChecks.scala, tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala, tests/jvm/src/test/scala-2.13/scala/meta/tests/trees/ReflectionSuite.scala, tests/shared/src/test/scala-2.13/scala/meta/tests/tokenizers/TokensPositionSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/SignificantIndentationSuite.scala, tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala
=> Trees: define secondary ctor body tree

scalameta/common/shared/src/main/scala/scala/meta/prettyprinters/Show.scala
=> Show: revise the `toString` method, don't unapply

scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
=> TreeSyntax: rewrite Template handling slightly

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/quasiquotes/shared/src/main/scala/scala/meta/internal/quasiquotes/ReificationMacros.scala, scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala, scalameta/trees/shared/src/main/scala/scala/meta/trees/Api.scala, tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala, tests/jvm/src/test/scala-2.13/scala/meta/tests/trees/ReflectionSuite.scala, tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala, tests/shared/src/test/scala-2.13/scala/meta/tests/tokenizers/TokensPositionSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/BasicPositionSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ControlSyntaxSuite.scala
=> Trees: define a group of case clauses

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala, scalameta/trees/shared/src/main/scala/scala/meta/trees/Api.scala, tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala, tests/jvm/src/test/scala-2.13/scala/meta/tests/trees/ReflectionSuite.scala, tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala, tests/shared/src/test/scala-2.13/scala/meta/tests/tokenizers/TokensPositionSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/BasicPositionSuite.scala
=> Trees: define a group of enumerator clauses

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala, scalameta/trees/shared/src/main/scala/scala/meta/trees/Api.scala, tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala, tests/jvm/src/test/scala-2.13/scala/meta/tests/trees/ReflectionSuite.scala, tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala
=> Trees: define a group of type case clauses

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/ParentChecks.scala, tests/js/src/test/scala/scala/meta/tests/parsers/JSFacadeSuite.scala, tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala, tests/jvm/src/test/scala-2.13/scala/meta/tests/trees/ReflectionSuite.scala, tests/shared/src/test/scala-2.13/scala/meta/tests/contrib/AssociatedCommentsTest.scala, tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala, tests/shared/src/test/scala-2.13/scala/meta/tests/tokenizers/TokensPositionSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/BasicPositionSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/CommonTrees.scala, tests/shared/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala, tests/shared/src/test/scala/scala/meta/tests/transversers/SimpleTraverserSuite.scala, tests/shared/src/test/scala/scala/meta/tests/transversers/TraverserSuite.scala
=> Trees: define template body tree

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala, scalameta/trees/shared/src/main/scala/scala/meta/trees/Api.scala, tests/js/src/test/scala/scala/meta/tests/parsers/JSFacadeSuite.scala, tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala, tests/jvm/src/test/scala-2.13/scala/meta/tests/trees/ReflectionSuite.scala, tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala, tests/shared/src/test/scala-2.13/scala/meta/tests/tokenizers/TokensPositionSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/CommonTrees.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/SignificantIndentationSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/TypeSuite.scala, tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala, tests/shared/src/test/scala/scala/meta/tests/prettyprinters/TreeSyntaxSuite.scala, tests/shared/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala
=> Trees: define a group of stats

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScaladocParser.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/Scaladoc.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/ScaladocParserSuite.scala
=> Scaladoc: define and parse markdown code span

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala, scalameta/trees/shared/src/main/scala/scala/meta/trees/Api.scala, tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala, tests/jvm/src/test/scala-2.13/scala/meta/tests/trees/ReflectionSuite.scala, tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala, tests/shared/src/test/scala-2.13/scala/meta/tests/tokenizers/TokensPositionSuite.scala, tests/shared/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala
This will improve detection and error checking. Helps with #3913.
=> Trees: add a special Pkg.Body tree

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
=> ScalametaParser: minor refactor with match parsing

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala, scalameta/trees/shared/src/main/scala/scala/meta/trees/Api.scala, tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala, tests/jvm/src/test/scala-2.13/scala/meta/tests/trees/ReflectionSuite.scala, tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala, tests/shared/src/test/scala-2.13/scala/meta/tests/tokenizers/TokensPositionSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/BasicPositionSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/CommonTrees.scala
=> Trees: add branches, rename Clauses as XxxBlock

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala, tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ControlSyntaxSuite.scala
=> ScannerTokens: outdent before blank-sep'd comment

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/XmlSuite.scala
=> ScalametaParser: allow NL after SeqWildcard

scalameta/common/shared/src/main/scala/org/scalameta/logger.scala
=> FileLine: extend Ordered

scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala, tests/shared/src/test/scala/scala/meta/tests/tokenizers/TokenizerSuite.scala
Fixes https://github.com/scalameta/metals-vscode/issues/1540
=> bugfix: Fix infinite loop when invalid character was used

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/ImportSuite.scala
=> ScalametaParser: no wildcard-import validity check

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala, tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala, tests/jvm/src/test/scala-2.13/scala/meta/tests/trees/ReflectionSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/NamedTuplesSuite.scala
Fixes https://github.com/scalameta/scalameta/issues/3993
=> feature: Add support for named tuples

.github/workflows/ci.yml, .github/workflows/release-js.yml, .github/workflows/release-website.yml, .github/workflows/release.yml
* use `sbt/setup-sbt` to be sure `sbt` is present
* for the windows build switch to `actions/setup-java` and `sbt`
=> GHA updates

scalameta/dialects/shared/src/main/scala/scala/meta/Dialect.scala, scalameta/dialects/shared/src/main/scala/scala/meta/dialects/package.scala, scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/tokens/shared/src/main/scala/scala/meta/tokens/Token.scala, scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala, tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala, tests/jvm/src/test/scala-2.13/scala/meta/tests/trees/ReflectionSuite.scala, tests/shared/src/test/scala/scala/meta/tests/DialectSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/AndOrTypesSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/GivenSyntax36Suite.scala, tests/shared/src/test/scala/scala/meta/tests/prettyprinters/PublicSuite.scala
Fixes https://github.com/scalameta/scalameta/issues/3994
Fortunately, the changed given syntax is working without an issue.
=> feature: Add improved bounds syntax

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
Also, ignore explicit quasiquote tokens as Ellipsis is checked in `commaSeparated` and Unquote in `typ`.
=> ScalametaParser: move checks in tupleInfixType

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala, tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ControlSyntaxSuite.scala
=> ScannerTokens: preserve blanks after outdent

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MatchTypeSuite.scala
=> ScannerTokens: outdent before closing bracket, too

scalameta/dialects/shared/src/main/scala/scala/meta/Dialect.scala, scalameta/dialects/shared/src/main/scala/scala/meta/dialects/package.scala, scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/SoftKeywords.scala, scalameta/tokens/shared/src/main/scala/scala/meta/tokens/Token.scala, scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/ParentChecks.scala, tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala, tests/jvm/src/test/scala-2.13/scala/meta/tests/trees/ReflectionSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/CommonTrees.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/NewFunctionsSuite.scala
=> ScalametaParser: parse pure function types

scalameta/dialects/shared/src/main/scala/scala/meta/Dialect.scala, scalameta/dialects/shared/src/main/scala/scala/meta/dialects/package.scala, scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/ParentChecks.scala, tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala, tests/jvm/src/test/scala-2.13/scala/meta/tests/trees/ReflectionSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/NewFunctionsSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/TypeSuite.scala
=> ScalametaParser: parse type capability captures

docs/semanticdb/guide.md
=> Guide: update name of shared semanticdb library

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/CommonTrees.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/FewerBracesSuite.scala
=> ScalametaParser: blank then dot OK in simple expr

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
=> ScalametaParser: add overloads for at[], peek[]

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
=> ScalametaParser: refactor parsing modifiers

tests/shared/src/test/scala/scala/meta/tests/parsers/CommonTrees.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/GivenSyntax36Suite.scala
=> GivenSyntax36Suite: use CommonTrees shortcuts

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
=> ScalametaParser: refactor initRest()

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
`GivenType` possible infix of AnnotTypes and does not include `with`, unlike regular compound types. Helps with #4047.
=> ScalametaParser: pass `inGivenSig` to type methods

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
=> ScalametaParser: define `atCurPosEmpty`

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
=> ScalametaParser: define `unquoteOpt`

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala, tests-semanticdb/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/ModSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/ParseSuite.scala
=> ScalametaParser: refactor parsing Term.Param

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
It allows anonymous names in parameters. Helps with #4047.
=> ScalametaParser: add `GivenSigContext`

semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/TypeOps.scala
Seems to fix #4084 though I haven't figured out a way to unit test this yet--suggestions welcome!
=> Account for ClassInfoType within toSemanticTpe

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
=> ScalametaParser: check Ellipsis with context bound

semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/TextDocumentOps.scala, tests-semanticdb/src/test/resources/example/Methods_2.13.scala, tests-semanticdb/src/test/resources/metac.expect_2.13
=> TextDocumentOps: fix handling of context bounds

semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/TextDocumentOps.scala, tests-semanticdb/src/test/resources/example/Synthetic_2.13.scala, tests-semanticdb/src/test/resources/metac.expect_2.13
=> TestDocumentOps: handle Template context bounds

semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/TextDocumentOps.scala
Use Mod.WithWithin instead of Mod.{Private,Protected}, and Tree.WithPats instead of Defn.{Val,Var}.
Also move the special-case handling of single Pat.Var within Defn.Val.
=> TextDocumentOps: refactor registering meta trees

semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/ConfigOps.scala, semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/RemoveOrphanSemanticdbFiles.scala
=> Semanticdb ConfigOps: add a ":cleanup:" section

scalameta/inputs/shared/src/main/scala/scala/meta/internal/inputs/package.scala, semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/SyntheticOps.scala, semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/TextDocumentOps.scala, semanticdb/semanticdb/src/main/scala/scala/meta/internal/semanticdb/Implicits.scala
Also, refactor `.toSemanticOriginal`.
=> SyntheticOps: add implicits `.toMeta`, `.toRange`

.github/workflows/ci.yml, build.sbt, project/Versions.scala, semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/TextDocumentOps.scala, tests-semanticdb/src/test/resources/metac.expect_2.13, tests-semanticdb/src/test/scala/scala/meta/tests/semanticdb/TargetedSuite.scala
Fixes https://github.com/scalameta/scalameta/issues/4128
=> chore: Add support for Scala 2.13.16

semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/TextDocumentOps.scala
We don't need to "index RHS" since that would be done anyway, so this removes unnecessary traversal. Also, we don't need to recurse to obtain named fields as those would not apply in given context.
=> TextDocumentOps: detect named args differently

semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/TextDocumentOps.scala, tests-semanticdb/src/test/scala/scala/meta/tests/semanticdb/TargetedSuite.scala
=> TextDocumentOps: skip occurrence for empty range

scalameta/trees/shared/src/main/scala/scala/meta/internal/Scaladoc.scala, scalameta/trees/shared/src/main/scala/scala/meta/internal/parsers/ScaladocParser.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/ScaladocParserSuite.scala
Previously, we would include the no-space suffix in Link, CodePart etc, but that has its limitations (not all punctuation marks were supported, no way to represent no-space before a Link -- such as in parentheses).
Instead, let's include an indicator in every TextPart whether there's a space (or, rather, no space) before it.
Helps with scalameta/scalafmt#4716.
=> Scaladoc: move no-space indicator around TextPart

docs/misc/built-with-scalameta.md
=> Add Regenesca

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala, scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/SepRegion.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/DefnSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ControlSyntaxSuite.scala
=> ScannerTokens: Region{Paren,Bracket} need indent

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/GivenSyntax36Suite.scala
=> ScannerTokens: strip RegionGivenDecl on newline

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala, scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/InterleavedDeclSuite.scala, tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/NewFunctionsSuite.scala
=> ScannerTokens: left bracket can start statement

.github/workflows/release.yml, CONTRIBUTING.md, build.sbt
=> improvement: Explain how to back publish a version

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
This includes removing unused `wrap` parameter in makeTupleType.
=> ScalametaParser: revise logic to make Type tuples
