scalameta/scalameta

scalameta/src/main/scala/scala/meta/syntactic/parsers/Parsers.scala

If we use a unicode character instead of a unicode escape to represent
the rightward double arrow in Parsers.scala, then our scanner refuses
to tokenize the file, which fails our tests. I've no time to debug this,
so I'm just working around.

workaround for a scanner bug

---

scalameta/src/main/scala/scala/meta/semantic/package.scala

Once we have an idea how to handle bindings, I'll add stuff here
(maybe will even reinstate something).
However, for now, these stubs will just slow us down, especially given
that now when I intend to replace all ???'s in semantic/package.scala
with real implementations.

removes wishful thinking in semantic/package.scala

---

scalameta/src/main/scala/scala/meta/internal/hygiene/Denotation.scala
scalameta/src/main/scala/scala/meta/semantic/Api.scala
scalameta/src/main/scala/scala/meta/ui/ShowSemantics.scala

An owner can have term/type members and term/type parameters with the same name,
so just Type/Term/Method distinction doesn't cut it.

h.Signature needs to distinguish term/type members and term/type parameters

---

docs/quasiquotes.md
foundation/src/main/scala/org/scalameta/ast/ast.scala
scalameta/src/main/scala/scala/meta/Trees.scala
scalameta/src/main/scala/scala/meta/internal/hygiene/Equality.scala
scalameta/src/main/scala/scala/meta/semantic/Api.scala
scalameta/src/main/scala/scala/meta/syntactic/parsers/Parsers.scala
scalameta/src/main/scala/scala/meta/ui/ShowCode.scala
tests/src/test/scala/parser/DeclSuite.scala
tests/src/test/scala/parser/DefnSuite.scala
tests/src/test/scala/parser/PatSuite.scala
tests/src/test/scala/parser/TemplateSuite.scala
tests/src/test/scala/parser/TermSuite.scala
tests/src/test/scala/parser/TypeSuite.scala
tests/src/test/scala/quasiquotes/JoinSuite.scala
tests/src/test/scala/show/DottySuite.scala
tests/src/test/scala/show/ScalaSuite.scala

Now I remember why we didn't introduce Pat.Var a year ago.
Because it would require a symmetric change to express type variable patterns,
and that would make it impossible to use meta.Type types for type patterns.
That was deemed too inconvenient and rejected.
Now I think that we should've followed that through, because pattern types
seem to form a distinct syntactic group, with their own peculiarities.
An argument that types and pattern types look the same syntactically
is compelling and seductive, but Term.Apply and Pat.Extract also look
the same, and we didn't unify them, so I think that there is more to
tree unification that just syntactic likeness.
Even though this change creates an inconvenience (it's no longer possible
to use Type and Pat.Type interchangeably), that inconvenience …

introduces meta.Pat.Type

---

foundation/src/main/scala/org/scalameta/algebra/Monoid.scala
foundation/src/main/scala/org/scalameta/algebra/package.scala
foundation/src/main/scala/org/scalameta/tql/TraverserBuilder.scala
foundation/src/main/scala/org/scalameta/typelevel/=!=.scala
project/build.scala
scalameta/src/main/scala/scala/meta/internal/tql/AllowedTransformation.scala
scalameta/src/main/scala/scala/meta/internal/tql/CollectionLikeUI.scala
scalameta/src/main/scala/scala/meta/internal/tql/Combinators.scala
scalameta/src/main/scala/scala/meta/internal/tql/TraverserBuilder.scala
scalameta/src/main/scala/scala/meta/internal/tql/TraverserHelper.scala
scalameta/src/main/scala/scala/meta/package.scala
scalameta/src/main/scala/scala/meta/tql/AllowedTransformation.scala
scalameta/src/main/scala/scala/meta/tql/Api.scala
scalameta/src/main/scala/scala/meta/tql/CollectionLikeUI.scala
scalameta/src/main/scala/scala/meta/tql/Combinators.scala
scalameta/src/main/scala/scala/meta/tql/SyntaxEnhancer.scala
scalameta/src/main/scala/scala/meta/tql/Traverser.scala
scalameta/src/main/scala/scala/meta/tql/package.scala
tests/src/test/scala/tql/CollectionLikeUISuite.scala
tests/src/test/scala/tql/ObeyRuleSuite.scala

Big thanks to @begeric for designing/implementing TQL during his semester
project at LAMP (https://infoscience.epfl.ch/record/204789)!
Also special thanks to @mdemarne for porting TQL based on 0.0.0-M0
to the ever-changing 0.1.0-SNAPSHOT!
This commit takes most of the code in the aforementioned github repository,
except for:
1) Things that relate to optimizations, i.e. MapOptimized.scala,
SetOptimized.scala, Fusion.scala, ScalaMetaFusionTraverser.scala,
ScalametaTraverserHelperMacros.scala.
2) Scala.reflect-like Traverser and Transformer.
3) Some tests and benchmarks.
1 looks very interesting, but for now I'd like to keep things as simple as possible.
We'll get back to 1 and 3 when the time comes to optimize scala.meta.
2 looks useful, but I'm not sure whether I'd like to have it in …

absorbs https://github.com/begeric/TQL-scalameta

---

README.md

1) jvmSig of singleton module types is now "Foo$" instead of "Foo.type".
2) jvmField/jvmMethod/intrinsic now take multiple arguments to denote
different parts of their signature (class name, member name, signature proper).
This should make it easier to process those calls.

improves jvmField/jvmMethod/intrinsic emitter

---

README.md
scalameta/src/main/scala/scala/meta/Trees.scala
scalameta/src/main/scala/scala/meta/semantic/Api.scala
scalameta/src/main/scala/scala/meta/ui/ShowCode.scala
tests/src/test/scala/adt/ReflectionSuite.scala

I can't say I like this idea very much, but we need an immediate solution,
so that scalahost can represent abstract methods that originate from bytecode.
In the case of concrete methods, we could replace their bodies with stubs that carry
all the necessary info, but with abstract methods there's not much that we can do.
We will need to revise this decision later on when the dust settles.

introduces Mod.Ffi

---

foundation/src/main/scala/org/scalameta/tql/TraverserBuilder.scala
scalameta/src/main/scala/scala/meta/internal/tql/TraverserHelper.scala
tests/src/test/scala/tql/ObeyRuleSuite.scala

1. The TQL TraverserBuilder prevented any traversal of Templates. This was due to the way stats are setup into templates as Option[Seq[Stat]], which was not handled by the previous version of TQL. This is now corrected and the Obey test case passes as usual.
2. Correcting ObeyRuleSuite for TQL: we can't compare source code as strings directly, due to formatting differences between the source code and the prettyprinter output. The test now checks if the raw of the trees are equals. A small case was also added for testing purposes.
This is the continuation of https://github.com/begeric/TQL-scalameta/pull/2.

TQL: bug fix in TraverserBuilder

---

scalameta/src/main/scala/scala/meta/Origin.scala

Changing endLine and startLine to lazy vals for performance improvement.

endLine and startLine as lazy vals for performance improvement

---

scalameta/src/main/scala/scala/meta/syntactic/Tokens.scala

I think it makes sense to allow deconstruction of `Tokens` just like other `Seq`s (after all, it is a `Seq`).
```scala
tokens match { case Tokens(first, second, rest @ _*) => ??? }
```

Add sequence deconstruction to `Tokens`

---

foundation/src/main/scala/org/scalameta/adt/Adt.scala
foundation/src/main/scala/org/scalameta/ast/root.scala
foundation/src/main/scala/org/scalameta/tokens/root.scala
scalameta/src/main/scala/scala/meta/Trees.scala
scalameta/src/main/scala/scala/meta/dialects/package.scala
scalameta/src/main/scala/scala/meta/syntactic/Input.scala
scalameta/src/main/scala/scala/meta/syntactic/Token.scala
tests/src/test/scala/ast/SerializationSuite.scala

Using Java serialization is, of course, quite low-tech, but it's dead simple and works as a partial proof that our trees are now platform-independent. Now I'd like to do the same to converted trees in scalahost. Fixes https://github.com/scalameta/scalameta/issues/73.

makes everything Serializable

---

project/build.scala
scalameta/src/main/scala/scala/meta/internal/quasiquotes/ast/ReificationMacros.scala
tests/src/test/scala/quasiquotes/QuasiquoteSuite.scala

Apparently the pattern matcher is unhappy if we generate code that looks like:
`... match { case <freshname> => Some(...); case _ => None }`, therefore I had to tune
the reification macro to avoid such codegen in rare edge cases.

fixes #175

---

docs/quasiquotes.md

The optional part of the return is no longer optional, so I'm just updating the doc,
not coming up with something crazy/new.

return $expropt => return $expr

---

scalameta/src/main/scala/scala/meta/Trees.scala
scalameta/src/main/scala/scala/meta/internal/ui/InferTokens.scala
tests/src/test/scala/show/QuasiSuite.scala

These trees are used as an intermediate representation that only exists
in implementation of quasiquotes. Therefore, the bug wasn't that bad and
was only found recently.

fixes prettyprinting for internal Quasi trees

---

scalameta/src/main/scala/scala/meta/internal/semantic/Denotation.scala
scalameta/src/main/scala/scala/meta/semantic/Api.scala
scalameta/src/main/scala/scala/meta/ui/ShowSemantics.scala

Not sure whether it's better to merge Denotation.Single and Multi or
to keep them separate, so let's go for the route that doesn't break
pre-existing code that already uses denotations (e.g. Intellij).

introduces Denotation.Multi

---

scalameta/src/main/scala/scala/meta/Trees.scala
scalameta/src/main/scala/scala/meta/internal/parsers/Parsers.scala
scalameta/src/main/scala/scala/meta/internal/ui/InferTokens.scala
scalameta/src/main/scala/scala/meta/semantic/Api.scala
tests/src/test/scala/ast/ReflectionSuite.scala

1) Adds Pat.Type.Placeholder, because Pat.Type.Placeholder with empty bounds
becomes Pat.Type.Wildcard (super weird pattern type rules).
2) The only place where Pat.Var.Type and Pat.Type.Wildcard are allowed
is type arguments, so we require that they appear only there.

more precise modelling of pattern types

---

scalameta/trees/src/main/scala/scala/meta/parsers/common/Api.scala

The `dialect` parameter to `parse[U]` was only necessary because we wanted
to display better error messages if a dialect was not in scope
(not `no Parse[U] found`, but `no dialect found).
Now that there's a fallback implicit dialect in Dialect, this parameter
is no longer useful.

final touches before 0.0.4

---

scalameta/parsers/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/parsers/src/test/scala/scala/meta/tests/parsers/LitSuite.scala

The implementation is quite naive. We should look at the standard scalac
parser more closely, and see what it does.
See https://github.com/scalameta/scalameta/issues/312 for more info.

fixes 0xCAFEBABE

---

scalameta/inputs/src/main/scala/scala/meta/inputs/Content.scala
scalameta/inputs/src/main/scala/scala/meta/inputs/Position.scala
scalameta/inputs/src/main/scala/scala/meta/internal/inputs/package.scala
scalameta/parsers/src/main/scala/scala/meta/parsers/Errors.scala
scalameta/scalameta/src/test/scala/scala/meta/tests/inputs/FormatMessageSuite.scala
scalameta/scalameta/src/test/scala/scala/meta/tests/inputs/OffsetLineColumnSuite.scala
scalameta/scalameta/src/test/scala/scala/meta/tests/inputs/PositionSuite.scala
scalameta/tokenizers/src/main/scala/scala/meta/tokenizers/Errors.scala

Reproduces error messages emitted by the Scala compiler - including an offending line and a caret. Some examples can be found below:
```
16:14 ~/Projects/core/sandbox1 (master)$ parse 'foo + class'
// Scala source: /var/folders/n4/39sn1y_d1hn3qjx6h1z3jk8m0000gn/T/tmpyyRWlx
tmpyyRWlx:1: error: ; expected but class found
foo + class
^
at scala.meta.internal.parsers.Reporter$class.syntaxError(Reporter.scala:17)
at scala.meta.internal.parsers.Reporter$$anon$1.syntaxError(Reporter.scala:23)
at scala.meta.internal.parsers.Reporter$class.syntaxError(Reporter.scala:18)
at scala.meta.internal.parsers.Reporter$$anon$1.syntaxError(Reporter.scala:23)
at scala.meta.internal.parsers.ScalametaParser.syntaxErrorExpected(ScalametaParser.scala:504)
...
```
```
16:16 ~/Projects/core/sandbox1 (master)$ scala …
```

better error messages for parse errors

---

project/build.scala

It seems that using `Defaults.defaultSettings` is deprecated and causes problems with `ensime-sbt` causing the build to fail.

removed Default.defaultSettings so the project builds

---

project/build.scala

By the advice of @fommil and @lihaoyi, I've stopped aggregating readme in root.
Now I explicitly aggregate readme to include it in the most important tasks.
Naturally, I don't feel like copy/pasting code, so I'm only doing this
for `test` and `publish`, but I've already wasted too much time on SBT.

sbt publish-signed no longer exits with an error

---

scalameta/common/src/main/scala/org/scalameta/internal/MacroHelpers.scala
scalameta/common/src/main/scala/scala/meta/internal/classifiers/Macros.scala
scalameta/common/src/main/scala/scala/meta/internal/prettyprinters/ShowMacros.scala
scalameta/quasiquotes/src/main/scala/scala/meta/internal/quasiquotes/ConversionMacros.scala
scalameta/quasiquotes/src/main/scala/scala/meta/internal/quasiquotes/ReificationMacros.scala
scalameta/tokens/src/main/scala/scala/meta/internal/tokens/TokenInfo.scala

typeOf/symbolOf/hygienicRef for existential types have been replaced
with equivalent constructs that don't involve reification. To see why
that's necessary, refer to the aforementioned issue.
I don't like the fact that I can't test this in an automated fashion
(well, at least I can't come up with a way of doing that at the moment).

attempt to fix https://github.com/scalameta/paradise/issues/10

---

scalameta/parsers/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/quasiquotes/src/main/scala/scala/meta/internal/quasiquotes/ConversionMacros.scala
scalameta/quasiquotes/src/main/scala/scala/meta/quasiquotes/QuasiquoteParsers.scala
scalameta/scalameta/src/test/scala/scala/meta/tests/quasiquotes/ErrorSuite.scala
scalameta/scalameta/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala

We can't fully fix #448 at the moment because of the syntactic ambiguity
described in #223.
When the user writes q"class C extends $foo", we can't really know whether
they meant to insert/extract a constructor or a template.
Therefore, what we expect people to do now is to write q"class C extends $foo {}",
in which case they unambiguously point out that they want to work with a parent.
It turns out that this didn't work before, and now I fixed that.
I also improved the error message to clearly explain what needs to be done.
I hope that in the future we'll be able to do better here.

work around #448

---

scalameta/parsers/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/scalameta/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala

When parsing quasiquotes, the internal structure of the tree changes. The
previous ascribe case defs were not accounting for the fact that the name and
the type could be quasi.

Fix #458: Recognize quasiquotes-generated lambda functions

---

notes/quasiquotes.md
scalameta/dialects/src/main/scala/scala/meta/dialects/package.scala
scalameta/parsers/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/scalameta/src/test/scala/scala/meta/tests/api/SurfaceSuite.scala
scalameta/scalameta/src/test/scala/scala/meta/tests/ast/ReflectionSuite.scala
scalameta/scalameta/src/test/scala/scala/meta/tests/ast/TokensSuite.scala
scalameta/scalameta/src/test/scala/scala/meta/tests/parsers/DefnSuite.scala
scalameta/scalameta/src/test/scala/scala/meta/tests/parsers/DottySuite.scala
scalameta/scalameta/src/test/scala/scala/meta/tests/prettyprinters/PublicSuite.scala
scalameta/tokenizers/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala
scalameta/tokenizers/src/main/scala/scala/meta/internal/tokenizers/LegacyToken.scala
scalameta/tokenizers/src/main/scala/scala/meta/internal/tokenizers/ScalametaTokenizer.scala
scalameta/tokens/src/main/scala/scala/meta/tokens/Token.scala
scalameta/trees/src/main/scala/scala/meta/Trees.scala
scalameta/trees/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala

- A new Dialect for Paradise, which allows inline, has been created.
- Defined inline modifier only, valid only for Dotty and Paradise. Other dialects work as before.

Allows for inline modifier. Fixes #466.

---

scalameta/dialects/src/main/scala/scala/meta/dialects/package.scala
scalameta/parsers/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/scalameta/src/test/scala/scala/meta/tests/parsers/DottySuite.scala
scalameta/trees/src/main/scala/scala/meta/Trees.scala

Fixes #493
* Add a flag to `Dialect`
* Update logic in `ScalametaParser` to look at the flag
* Comment out an invariant check in AST class because it's no longer an invariant
* Add a test
Commenting out the invariant check is a shame, but it was unavoidable because it's not currently possible to access the parser's dialect in order to check the appropriate flag.

Allow trait parameters in Dotty dialect

---

scalameta/parsers/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/scalameta/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala

Quasiquotes can now pattern match on a single parameter in a primary constructor or function parameter list.

Fix #468: Add support for single parameter quasiquote

---

scalameta/common/src/main/scala/scala/meta/internal/ast/Liftables.scala
scalameta/scalameta/src/test/scala/scala/meta/tests/quasiquotes/ErrorSuite.scala

I was doing some like:
```scala
private def instrument(source: Source, output: Term.Name): Source = {
val main = 
q"""
object Main {
val $output = scala.collection.mutable.Map.empty[(Int, Int), (String, String)]
}
"""
}
```
and I ran into the following error:
```
[error] /home/gui/center/scastie/instumentation/src/main/scala/instumentation/Instument.scala:49: can't unquote a name here, use a pattern instead
[error]       val $output = scala.collection.mutable.Map.empty[(Int, Int), (String, String)]
[error]           ^
```
I want to make obvious that a pattern is a `scala.meta.Pat` in my case `scala.meta.Pat.Var(output)`
solved like this:
```scala
private def instrument(source: Source, output: Term.Name): Source = {
val pat = Pat.Val.Term(output)
val main = 
q"""
object Main {
val $pat = …
```

make it obvious what a pattern is

---

scalameta/parsers/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/scalameta/src/test/scala/scala/meta/tests/parsers/DefnSuite.scala

Parser should not accept the following:
```
@ var x = _
cmd4.sc:160: unbound placeholder parameter
var x = _
^
Compilation Failed
```
```
@ val x: Int = _
cmd4.sc:160: unbound placeholder parameter
val x: Int = _
^
Compilation Failed
```

Reject invalid var/val definitions (fixes #529)

---

scalameta/parsers/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/scalameta/src/test/scala/scala/meta/tests/parsers/DefnSuite.scala

This is a fix for #561, the regression in parsing `val f: Int => String = _.toString` which was introduced in #541.
It also fixes parsing of `var f: Int => String = _.toString`, which was broken even before #541.
The underlying problem was that the decision on whether a statement had an RHS was based on whether the first token after the `=` was an underscore. But this is not sufficient, because an RHS expression can start with an underscore.
My solution is to first parse the RHS as an expression, then check if the resulting tree is `Placeholder`. Happy to take expert advice on whether this is a reasonable strategy.
@xeno-by @olafurpg review please
@liufengyun Sorry for the regression

Fix parsing wildcard functions

---

scalameta/trees/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala

While working on building a scala.meta testkit, I noticed that the
pretty-printer would get stuck in an infnite loop. I can't find an
example that triggered the infinite loop, but this commit fixes it.
All tests still pass.

Fix infinite recursion.

---

scalameta/quasiquotes/src/main/scala/scala/meta/quasiquotes/Unlift.scala

Unlift.unapply is required in order to implement Quasiquotes in Dotty. Review @xeno-by .

support Unlift.unapply

---

scalameta/scalameta/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala
scalameta/trees/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala

Term.Apply with function as its arg is printed using braces instead of parenthesis.
solves #572

fix "foo { i: Int => () }".toString

---

scalameta/inline/src/main/scala/meta/inline/Api.scala

I think it makes more sense to have `meta: Any => Nothing`, so that user can any meaningful type annotations of def macros.

change signature of meta

---

scalameta/scalameta/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala
scalameta/trees/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala

Before: `a.{ b => c }`
After:  `a.{b => c}`

Importee.rename

---

README.md

@DavidDudson has been very a active community member for quite a while.
He has contributed to a lot of valuable discussions on Gitter,
project issue trackers and pull requests. We are honored to work with David!
Thanks a bunch, @DavidDudson. Please give a 👍 if you'd like
to be added as a maintainer.

add David Dudson as a maintainer

---

build.sbt
scalameta/common/src/main/scala/org/scalameta/logger.scala

When hacking on scala.meta I've desperately missed being able to println a variable during development and see the file name + line numer + variable name + variable value
```scala
val x = 1
logger.elem(x)
// Foo.scala:10 [x]: 1
```
The macros are copied from lihaoyi/sourcecode to avoid adding a new dependency. The library is really small however so I personally don't really mind adding it as a dependency.

Add logger utility

---

README.md

@mutcianm has been part of scala.meta from the very beginning.
He’s been responsible for IntelliJ integration, single-handedly implementing
support for new-style macro annotations and contributing a lot to all
phases of the design process. We’ve been very lucky to have Mikhail with us!

add Mikhail Mutcianko as a maintainer

---

build.sbt

I was unable to build due to 
`Corpus.scala:7: object io is not a member of package org.apache.commons
[error] import org.apache.commons.io.FileUtils`
When troubleshooting resolution I noticed scalameta depended on the old location of commons-io was using an old version.  This change is just an update to the latest version of commons-io.  All tests pass locally for me now.

Updated commons.io dependency

---

build.sbt

It turns out that addCompilerPlugin works differently for maven-based (sonatype)
and ivy-based (bintray) artifacts. We’ve been using the former for ages,
and today I tried the latter.
What I’ve found out is that, in ivy mode, addCompilerPlugin behaves weirdly.
First, it fetches all compiler plugin artifacts, as if in libraryDependencies mode.
But then, it puts both -sources.jar and the actual jar on -Xplugin leading
to nonsensical scalac invocations like:
[debug] Calling Scala compiler with arguments  (CompilerInterface):
[debug]     -Yrangepos
[debug]     -Xplugin-require:scalahost
[debug]     -Xplugin:.../srcs/scalahost_2.11.8-1.6.0-641-sources.jar
[debug]     -Xplugin:.../jars/scalahost_2.11.8-1.6.0-641.jar
Therefore, I’m disabling publishing sources for scalahost when targeting …

workaround for an sbt issue

---

build.sbt

Fix a breakage introduced by a hasty merge of https://github.com/scalameta/scalameta/pull/643.

fix broken build

---

.scalafmt.conf
scalahost/src/main/scala/scala/meta/internal/scalahost/HijackAnalyzer.scala
scalahost/src/main/scala/scala/meta/internal/scalahost/ReflectionToolkit.scala
scalahost/src/main/scala/scala/meta/internal/scalahost/ScalahostPipeline.scala
scalahost/src/main/scala/scala/meta/internal/scalahost/ScalahostPlugin.scala
scalahost/src/main/scala/scala/meta/internal/scalahost/converters/LogicalTrees.scala
scalahost/src/main/scala/scala/meta/internal/scalahost/converters/ReflectToolkit.scala
scalahost/src/main/scala/scala/meta/internal/scalahost/converters/ToMtree.scala
scalahost/src/main/scala/scala/meta/internal/scalahost/v1/LocationOps.scala
scalahost/src/main/scala/scala/meta/internal/scalahost/v1/Mirror.scala
scalahost/src/main/scala/scala/meta/internal/scalahost/v1/offline/Mirror.scala
scalahost/src/main/scala/scala/meta/internal/scalahost/v1/offline/PathOps.scala
scalahost/src/main/scala/scala/meta/internal/scalahost/v1/online/DatabaseOps.scala
scalahost/src/main/scala/scala/meta/internal/scalahost/v1/online/Mirror.scala
scalahost/src/main/scala/scala/meta/internal/scalahost/v1/online/ParseOps.scala
scalahost/src/main/scala/scala/meta/internal/scalahost/v1/online/SymbolOps.scala
scalahost/src/test/scala/scala/meta/tests/scalahost/converters/ConverterSuite.scala
scalahost/src/test/scala/scala/meta/tests/scalahost/v1/OnlineMirrorSuite.scala
scalameta/contrib/src/main/scala/scala/meta/contrib/AssociatedComments.scala
scalameta/contrib/src/main/scala/scala/meta/contrib/Structurally.scala
scalameta/contrib/src/main/scala/scala/meta/contrib/Syntactically.scala
scalameta/contrib/src/main/scala/scala/meta/contrib/TreeOps.scala
scalameta/contrib/src/test/scala/scala/meta/contrib/AssociatedCommentsTest.scala
scalameta/contrib/src/test/scala/scala/meta/contrib/EqualSuite.scala

Vertical alignment is now disabled. From personal experience, it was too much
of a disruption with little benefit.
stripMargin is now assumed to be String.stripMargin from scala-library.jar.
Allegedly, this should lead to better-looking multiline strings with margins.

change scalafmt config

---

bin/bintray.sh

Drone uses a specific directory for cache, the publish step has kept
failing because drone hasn't used that cache directory when publishing,
resulting in
[error] (*:update) sbt.ResolveException: unresolved dependency: me.lessis#bintray-sbt;0.3.0: not found
errors.

Fix bintray publish script.

---

build.sbt
project/os.scala

We no longer use PR numbers to derive prerelease versions, because
such versions aren’t guaranteed to be ordered lexicographically.
Earlier pull requests can be merged later, and vice versa,
which brings significant confusion.
The new versioning scheme is very similar to git-describe.
A typical prerelease version looks like 1.6.0-344-a9f6f83e,
where the first number after the dash is the number of commits between
HEAD and v1.0.0, and the second number is the sha of HEAD.
This is a little bit more verbose than the old scheme, which only featured
one number, but that’s what it takes to be (almost) lexicographic and unique.
Finally, if an artifact is built from a dirty repository, i.e.
if the sources aren’t uniquely identified by the current sha, then we
append a timestamp, e.g. …

change versioning scheme

---

build.sbt

These two lines were blocking a sonatype release, so I disabled them.
No idea why we needed them in the past.

enable scaladocs for sbt-scalahost

---

changelog/1.6.0.md

See https://gitter.im/scalameta/scalameta?at=58b406971465c46a56bd6e87
for a question about upgrading to 1.6 causing paradise macros to fail.

Add upgrade guide to changelog.

---

build.sbt
scalameta/contrib/src/test/scala/scala/meta/contrib/ScaladocParserSuite.scala

```
The outer reference in this type test cannot be checked at run time.
[error]         case c: Token.Comment => c
[error]              ^
```
cc @xavier-fernandez

Fix compilation error in CI.

---

bin/run-benchmarks.sh
build.sbt
project/plugins.sbt
scalameta/benchmarks/src/main/resources/Endpoint.scala
scalameta/benchmarks/src/main/resources/EventSerializers.scala
scalameta/benchmarks/src/main/resources/GenJSCode.scala
scalameta/benchmarks/src/main/resources/HiveMetastoreCatalog.scala
scalameta/benchmarks/src/main/resources/PrintStreamTest.scala
scalameta/benchmarks/src/main/scala/org/scalameta/benchmarks/MicroBenchmark.scala
scalameta/benchmarks/src/test/scala/org/scalameta/benchmarks/BenchmarkOK.scala

The benchmarks can be run against 4 files of different sizes (small,
medium, large and extra large).  The files are taken from Scala.js and
Spark, to get a representative sample of "real-world" scala code.
Output from running `./bin/run-benchmarks.sh` is something like this
```
[info] Benchmark                   Mode  Cnt    Score     Error  Units
[info] Micro.ExtraLarge.transform  avgt    3  396.557 ± 596.512  ms/op
[info] Micro.Large.transform       avgt    3   92.412 ± 102.961  ms/op
[info] Micro.Medium.transform      avgt    3   23.696 ±  50.019  ms/op
[info] Micro.Small.transform       avgt    3    2.649 ±   5.275  ms/op
```
cc/ @rorygraves

Setup JMH benchmarks to test optimizations.

---

readme/Readme.scalatex

Thank you @bertrandkang!
See https://github.com/scalameta/scalameta.github.com/pull/15
for the original issue report and a suggested fix.

fix typo in Readme.scalatex

---

changelog/1.6.0.md

Switching "pimp" terminology for "enrich", per https://groups.google.com/forum/#!topic/scala-internals/kVWg7HKldjs. Many prefer the latter because the former has the potential to offend, and at the very least isn't self-explanatory to people unfamiliar with the decade-old TV show "Pimp My Ride". I hope this is uncontroversial!

Small terminology change in docs

---

bin/bintray.sh
build.sbt

- bintray script was using old cache dir.
- bintray script was using wrong environment variable.
- build was not using cached resolution, slowing down ci.

Fix build.

---

build.sbt

While publishing a snapshot to bintray, I noticed that benchmarks was publishing to sonatype, because it uses the default publish settings.

Explicitly disable publishing for readme+benchmarks

---

bin/bintray.sh
build.sbt

The bintray.sh script runs 'sbt very' instead of 'sbt "very publish"',
for some reason, causing the publish step to fail after merge into
master. This commit moves the "very publish" part into a ci-publish
command.

Fix publishing.

---

scalahost-sbt/src/main/scala/scala/meta/scalahost/sbt/ScalahostSbtPlugin.scala

I want to use this setting in scalafix to rewrite all projects.

Make scalametaDependencies taskKey public.

---

build.sbt
scalameta/semantic/src/main/protobuf/semanticdb.proto

Apparently, those two lines added a dependency on the protobuf compiler and a whole boatload of other stuff that we don't need. Now, the scalahost assembly is 14mb instead of 24mb.

Shrink scalahost/assembly by 10mb

---

bin/bintray.sh

The `sbt` script on the docker image runs a few custom steps before
passing the command to the actual sbt. Maybe this change will
eventually fix the cryptic bintray publish errors.

Use regular sbt to fix ci-publish.

---

scalameta/contrib/shared/src/main/scala/scala/meta/contrib/Extract.scala
scalameta/contrib/shared/src/main/scala/scala/meta/contrib/implicits/ExtractExtensions.scala
scalameta/contrib/shared/src/main/scala/scala/meta/contrib/instances/ExtractAnnotationInstances.scala

Due to a rebase error, the immutable.Seq imports were dropped.
This reintroduces them

Make sure extract uses immutable.Seq

---

changelog/1.7.0.md
scalameta/contrib/shared/src/main/scala/scala/meta/contrib/equality/Structurally.scala
scalameta/contrib/shared/src/main/scala/scala/meta/contrib/equality/Syntactically.scala
scalameta/contrib/shared/src/main/scala/scala/meta/contrib/implicits/SetExtensions.scala
scalameta/contrib/shared/src/main/scala/scala/meta/contrib/package.scala
scalameta/contrib/shared/src/test/scala/scala/meta/contrib/SetExtensionsTest.scala

For https://github.com/scalameta/scalameta/issues/745.
I cannot remember exactly who it was that wanted this functionality. It surfaced from gitter chat.

Support syntactically and structurally for Set[Tree]

---

scalameta/contrib/shared/src/main/scala/scala/meta/contrib/TreeExtractors.scala
scalameta/contrib/shared/src/main/scala/scala/meta/contrib/package.scala
scalameta/contrib/shared/src/test/scala/scala/meta/contrib/TreeExtractorsSuite.scala
scalameta/scalameta/shared/src/test/scala/scala/meta/tests/ast/TreeSuite.scala
scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala

Motivation, make this answer simpler: http://stackoverflow.com/a/43415867/1469245
- Name.unapply is added for consistency with other tree unapply extractors.
- Select.unapply is put in contrib because otherwise it would conflict
with existing code that does `import scala.meta._, Type._/Type._`.

Add Select.unapply and Name.unapply.

---

scalameta/io/shared/src/main/scala/scala/meta/io/AbsolutePath.scala

Removing the method makes it hard to use pre-releases from scalafix.
Note, we should add mima checks to our CI.

Add back .absolute method.

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/scalameta/shared/src/test/scala/scala/meta/tests/parsers/XmlSuite.scala
scalameta/scalameta/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala

Parses "unquote Xml expression" similarly to "unquote expression".
This fixes a bug with empty expression (e.g. <a>{}</a>).

Parses empty unquote Xml expression

---

scalahost/nsc/src/main/scala/scala/meta/internal/semantic/AttributesOps.scala
scalahost/nsc/src/test/scala/scala/meta/tests/scalahost/mirrors/SemanticSuite.scala

Until #822 is implemented, this PR is just a sanity check that the strings in Denotation.info and Database.sugars are usable for scalafix with the v1.8 release.

Make sugars and denotations safer to insert into code.

---

scalahost/nsc/src/main/scala/scala/meta/internal/semantic/AttributesOps.scala
scalahost/nsc/src/test/scala/scala/meta/tests/scalahost/mirrors/SemanticSuite.scala

The synthetic apply belongs to Database.sugars, see
https://github.com/scalameta/scalameta/issues/846
Review @gabro

Handle synthetic .apply in Database.names, fixes #837

---

scalahost/nsc/src/main/scala/scala/meta/internal/semantic/InputOps.scala

Before this commit, when we encountered a non-range positions we would
fail with an AssertionError. After this commit, we create a m.Position
with start and end using the same offset: point.
I was unable to minimize a test-case for this error, but I confirmed manually that this change fixes the error by running sbt-scalahost on acyclic that crashed before the fix and no longer crashes

Gracefully handle non-range positions, fixes #836.

---

build.sbt

Currently, it's not possible to depend on sbt-scalahost pre-releases
with addSbtPlugin or libraryDependencies because it's published
maven-style to bintray.

Publish sbt-scalahost ivy style.

---

build.sbt
project/plugins.sbt
scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/XmlParser.scala

I believe this can improve the performances of the xml parser.
We instantiate a new parser for every single xml literal we parse. I believe
most of the time is spent during initialization since our xml parsers are
short lived and not reusable. These changes reduce initialization time
and memory consumption as it avoids pre-computing the lookup tables.
A better solution would be to have a reusable parser. But we would need
to remove the parser dependency on `Dialect`.

Improve Xml parser performances

---

scalameta/scalameta/shared/src/test/scala/scala/meta/tests/parsers/XmlSuite.scala
scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/XmlParser.scala

- Both `{`and `}` must be protected
- Block parser now fail if it reaches EOF

Fix bugs in Xml Parser

---

project/plugins.sbt

My experiments show a drop from ~17s to ~3s for scalametaJS/test, see
https://github.com/scala-js/scala-js/issues/2827#issuecomment-306063974

Upgrade to Scala.js 0.6.17 for faster link times.

---

scalameta/scalameta/shared/src/test/scala/scala/meta/tests/parsers/XmlSuite.scala
scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/ScalametaTokenizer.scala

This is not a fix for #945. I don't see an easy solution.
Now Scalameta will crash instead of emitting wrong tokens

Expose issue #945

---

scalahost/nsc/src/main/scala/scala/meta/internal/semantic/SymbolOps.scala

I struggled to find a minimal repro, but the fix seems logical to me. I
tested the fix manually by re-compiling the original reported issue from
twitter/scalding and confirmed that the ResolvedName with symbol
"<none>" no longer appears in the .semanticdb file.

Return Symbol.None instead of Symbol.Local for no position, fixes #959.

---

scalameta/parsers/js/npm/package.json
scalameta/parsers/js/src/main/scala/scala/meta/parsers/JSFacade.scala
scalameta/parsers/js/src/test/scala/scala/meta/parsers/JSFacadeSuite.scala

This PR allows specifying a dialect through the JS api.
Here's an example of usage from ASTExplorer:
This PR is based on #957 (which in turn is based on #956). I'll rebase as soon as the parent PRs get merged.

Allow specifying dialect through parsers facade

---

scalameta/parsers/js/npm/package.json
scalameta/parsers/js/src/main/scala/scala/meta/parsers/JSFacade.scala
scalameta/parsers/js/src/test/scala/scala/meta/parsers/JSFacadeSuite.scala

These are useful for highlighting parse errors in AST explorer. Here's an example:

Add lineNumber and columnNumber to parser errors

---

scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/ScalametaTokenizer.scala

I forgot to add `XMLLITEND` in #963. `STRINGPART` seemed to be missing too.

Add missing unreachable tokens to token conversion

---

build.sbt
scalahost/nsc/src/test/scala/scala/meta/tests/scalahost/mirrors/DatabaseSuite.scala
scalameta/testkit/src/main/scala/scala/meta/testkit/DiffAssertions.scala

The default multiline diff reports in ScalaTest are very unclear. This
commit adds proper diffing on multiline comparions. Example:
```
// before
[info] - object First {   def main(args: Array[String]): Un... *** FAILED ***
"...)V.(args)
[32..37): [List => _root_.scala.Array#
[38..44): String => _root_.scala.Predef.String#
[48..52): Unit => _root_.scala.Unit#
[65..69): banana => <...>@61..85
[72..76): List => _root_.scala.collection.immutable.List.
[90..97): println => _root_.scala.Predef.println(Ljava/lang/Object;)V.
[98..102): list => <...>@60]..85" did not equal "...)V.(args)
[32..37): [Array => _root_.scala.Array#
[38..44): String => _root_.scala.Predef.String#
[48..52): Unit => _root_.scala.Unit#
[65..69): list => <...>@61..85
[72..76): List => _root_.scala.collection.immutable.List. …
```

Emit proper diffs for multiline string comparison.

---

scalameta/contrib/shared/src/main/scala/scala/meta/contrib/DocToken.scala
scalameta/contrib/shared/src/main/scala/scala/meta/contrib/ScaladocParser.scala
scalameta/contrib/shared/src/test/scala/scala/meta/contrib/ScaladocParserSuite.scala

This commit changes the 'DocToken' AST, including the heading level on `Heading` directly. I should use another approach, or I need to add the change to the changelog?

Issue-#896 - Fix ScaladocParser not parsing multilevel headings

---

scalameta/semantic/shared/src/main/scala/scala/meta/semantic/Flags.scala

rename isPARAM to isParam, fixes #980

---

project/plugins.sbt
project/project/plugins.sbt

Most notably, use the latest sbt-scalatex unblocking us from wiping out
the scalameta/maven bintray repository.

Upgrade sbt plugins.

---

build.sbt
scalameta/testkit/src/test/scala/scala/meta/testkit/ScalametaParserProperties.scala

I was nervous to find out if the recent fixes in the parser introduced regression. We stopped running these tests on every PR after moving to Travis CI. Turns out there are no regressions, and some bugs have been fixed along the way 🎉

Update parser property tests to latest changes in trees.

---

bin/ci-publish.sh
build.sbt

If this turns out to work well, then I propose we ditch the bintray
pre-releases altogether and more regularly publish milestone releases
by demand.

Setup build to publish to sonatype on tag push #677

---

bin/ci-publish.sh
build.sbt

- Use custom pgp passphrase.
- Handle the case when TRAVIS_TAG exists sys.env but is empty.
- Only run pgp setup for sonatype release.

Fix publish on tag push, try 2.

---

build.sbt
project/os.scala
project/plugins.sbt
readme/Readme.scala

The first attempt to publish on push tag failed due to a bug in
os.version. This commit removes os.version in favor of using
sbt-dynver, shrinking the scalameta build.

Remove os.version in favor of sbt-dynver.

---

bin/ci-publish.sh
build.sbt

Just to be sure, we setup ~/.bintray/.credentials even if we shouldn't
need it when publishing on tag push.

Disable bintrayRelease on publish from tag push.

---

scalameta/scalameta/shared/src/test/scala/scala/meta/tests/io/IOFileTest.scala
scalameta/scalameta/shared/src/test/scala/scala/meta/tests/io/NIOPathTest.scala

Several IO tests asserted that the top-level target directory existed,
which is not the case when running sbt in batch mode. Switch to use the
sbt project directory for such assertions since it is ensured to exist.
Reproducible with: sbt --batch scalametaJVM/test
Refs: #1050

Fix #1050: Use the top-level sbt project directory as test subject

---

build.sbt
project/plugins.sbt
scalameta/io/js/src/main/scala/java/io/File.scala
scalameta/io/js/src/main/scala/java/nio/file/Path.scala
scalameta/io/js/src/main/scala/java/nio/file/Paths.scala
scalameta/io/js/src/main/scala/scala/meta/internal/io/JSIO.scala
scalameta/io/js/src/main/scala/scala/meta/internal/io/NodeNIOPath.scala
scalameta/io/js/src/main/scala/scala/meta/internal/io/PlatformFileIO.scala
scalameta/io/js/src/main/scala/scala/meta/internal/io/PlatformPathIO.scala
scalameta/io/jvm/src/main/scala/scala/meta/internal/io/PlatformPathIO.scala
scalameta/io/shared/src/main/scala/scala/meta/internal/io/PathIO.scala
scalameta/io/shared/src/main/scala/scala/meta/io/Multipath.scala
scalameta/scalameta/shared/src/test/scala/scala/meta/tests/io/IOFileTest.scala
scalameta/scalameta/shared/src/test/scala/scala/meta/tests/io/IOSuite.scala
scalameta/scalameta/shared/src/test/scala/scala/meta/tests/io/NIOPathTest.scala

Extend on #1056 by loading Node.js modules used for I/O lazily.
Tested with locally published version against [metadoc](https://github.com/jonas/metadoc/commit/5d1f4ed9bf27f771722a71a23cb400ed0f4b98cf), which shows that the [JSIO](https://github.com/scalameta/metadoc/blob/196c002a5cb40368c45d78bdaef457be711e15b1/metadoc-js/src/main/scala/scala/meta/internal/io/JSIO.scala) workaround can be deleted.

Lazy JavaScript I/O

---

.travis.yml
build.sbt
langmeta/semanticdb/shared/src/main/scala/star/meta/semanticdb/Symbol.scala
project/Versions.scala

This allows semanticdb-sbt (previously sbthost) to depend on it directly
instead of duplicating protobuf generation.

Cross-build langmeta to 2.10.

---

langmeta/io/shared/src/main/scala/star/meta/internal/io/FileIO.scala
scalameta/tests/jvm/src/test/scala/scala/meta/tests/SemanticdbExpectSuite.scala

Assuming UTF-8 is a dangerous game that often depends on local setup.
The convenience it brings rarely outweighs the bugs that go along with
it

remove UTF-8 only overload of slurp

---

langmeta/inputs/shared/src/main/scala/star/meta/inputs/Api.scala
langmeta/inputs/shared/src/main/scala/star/meta/inputs/Input.scala
langmeta/semanticdb/shared/src/main/protobuf/semanticdb.proto
langmeta/semanticdb/shared/src/main/scala/star/meta/semanticdb/Denotation.scala
langmeta/semanticdb/shared/src/main/scala/star/meta/semanticdb/ResolvedName.scala
langmeta/semanticdb/shared/src/main/scala/star/meta/semanticdb/Sugar.scala
langmeta/semanticdb/shared/src/main/scala/star/meta/semanticdb/internal/package.scala
scalameta/scalameta/shared/src/test/scala/scala/meta/tests/prettyprinters/PublicSuite.scala
scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/semanticdb/AttributesOps.scala
scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/semanticdb/DenotationOps.scala
scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/semanticdb/PrinterOps.scala
scalameta/semanticdb-scalac/src/test/scala/scala/meta/tests/SemanticSuite.scala
scalameta/tests/jvm/src/test/resources/semanticdb.expect
scalameta/tests/shared/src/test/scala/scala/meta/tests/SugarSuite.scala

Fixes #1015. Note, this PR does not add Type.Method since it's not necessary for me at the moment in scalafix. Type.Method can be added separately to make Denotation.info parseable.

Add semantic information for denotations

---

langmeta/io/js/src/main/scala/java/io/File.scala
langmeta/io/js/src/main/scala/star/meta/internal/io/JSIO.scala
scalameta/common/shared/src/main/scala/org/scalameta/invariants/Exceptions.scala
scalameta/scalameta/jvm/src/test/scala/scala/meta/tests/api/SurfaceSuite.scala
scalameta/scalameta/jvm/src/test/scala/scala/meta/tests/io/MultipathSuite.scala
scalameta/scalameta/jvm/src/test/scala/scala/meta/tests/tokens/ReflectionSuite.scala
scalameta/scalameta/jvm/src/test/scala/scala/meta/tests/trees/ReflectionSuite.scala
scalameta/scalameta/shared/src/test/scala/scala/meta/tests/inputs/FormatMessageSuite.scala
scalameta/scalameta/shared/src/test/scala/scala/meta/tests/inputs/OffsetLineColumnSuite.scala
scalameta/scalameta/shared/src/test/scala/scala/meta/tests/invariants/InvariantSuite.scala
scalameta/scalameta/shared/src/test/scala/scala/meta/tests/io/NIOPathTest.scala
scalameta/scalameta/shared/src/test/scala/scala/meta/tests/parsers/SbtSuite.scala
scalameta/scalameta/shared/src/test/scala/scala/meta/tests/prettyprinters/PublicSuite.scala
scalameta/scalameta/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala
scalameta/scalameta/shared/src/test/scala/scala/meta/tests/quasiquotes/ErrorSuite.scala
scalameta/scalameta/shared/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala
scalameta/scalameta/shared/src/test/scala/scala/meta/tests/transversers/TransverserSuite.scala

Mostly newline funny business. Multiline strings are as-is and don't
aquire different line endings on Windows.
It also seems like the platform-specific line endings in
Position.format aren't actually being expanded to platform specific line
endings.
That shouldn't be causing any actual harm, so the tests just plaster
over it in an "whichever way makes it succeed" kind of way - (almost?)
all Windows tooling doesn't care much about whether newlines are \r\n or
\n
Other than that, "\foo\bar" is not an absolute path on Windows
Leaves two tests failing, of which I'm not actually sure the failures
are spurious.

Make tests succeed on Windows

---

scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/HijackAnalyzer.scala

Manually verified that this works, tested on the scalafix repo.
We can add a test for this in the semanticdbIntegration project,
if we want to.

Disable hijacking under ScaladocGlobal, fix #1072.

---

appveyor.yml
langmeta/js/src/main/scala/java/io/File.scala
langmeta/js/src/main/scala/java/nio/file/Paths.scala
langmeta/js/src/main/scala/org/langmeta/internal/io/NodeNIOPath.scala
langmeta/js/src/main/scala/org/langmeta/internal/io/PlatformFileIO.scala
scalameta/scalameta/shared/src/test/scala/scala/meta/tests/io/NIOPathTest.scala
scalameta/scalameta/shared/src/test/scala/scala/meta/tests/parsers/ParseSuite.scala
scalameta/scalameta/shared/src/test/scala/scala/meta/tests/prettyprinters/PublicSuite.scala
scalameta/scalameta/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala
scalameta/tests/shared/src/test/scala/scala/meta/tests/MirrorConstructionSuite.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala

This is an "actual" change (even if it pertains only to pretty-printing) rather than a test change, bringing the windows implementation in line with the *nix implementation.
Also expanding the appveyor tests - all tests should now pass.
Review requested on the actual bug fix, whether assertSameLines is in the right place, and whether cleaning up the rest of the tests in terms of assertSameLines should be in this PR or in a separate one.

Show triple-quoted string on all line endings

---

langmeta/shared/src/main/scala/org/langmeta/internal/inputs/package.scala
langmeta/shared/src/main/scala/org/langmeta/semanticdb/ResolvedSymbol.scala
scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/semanticdb/PrinterOps.scala
scalameta/semanticdb-scalac/src/test/scala/scala/meta/tests/DatabaseSuite.scala
scalameta/semanticdb-scalac/src/test/scala/scala/meta/tests/SemanticSuite.scala
scalameta/tests/jvm/src/test/resources/semanticdb.expect
scalameta/tests/shared/src/test/scala/scala/meta/tests/SyntheticSuite.scala

- `def x[T](e: Int): T`.signature is `[T] => (e: Int): T`
- Denotation.signature no longer include redundant fully qualified paths,
to fully qualify use the resolved symbols instead.

Adapt semanticdb-scalac to new Type.Lambda/Type.Method syntax.

---

.travis.yml
bin/ci-publish.sh
build.sbt

- Handle timeout by publishing by scala version in individual jobs
- Remove org.langmeta to please sbt-sonatype. @xeno-by We'll have to figure this out later, but I don't have time to deal with it right now.

Fix CI publish infrastructure

---

scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/semanticdb/DocumentOps.scala
scalameta/semanticdb-scalac/src/test/scala/scala/meta/tests/SemanticSuite.scala

It turns out that we can use the same approach as with synthetic
.apply/.unapply as with .foreach/.flatMap in for comprehensions.
Supersedes #1123 
Review @cb372 @yilinwei

Fix #1037.

---

.travis.yml
build.sbt
project/Mima.scala
project/plugins.sbt

The changes in #1121 broke binary compatibility in 2.11 for potential
users who implement the sealed Tokenized/Parsed traits. Those should not
be extended, so we ignore the errors.

Enable MiMa checks on every PR.

---

scalameta/parsers/js/npm/package.json

Published as 2.0.0-RC3 on https://www.npmjs.com/package/scalameta-parsers

Bump npm version

---

scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/semanticdb/DocumentOps.scala
scalameta/semanticdb-scalac/src/test/scala/scala/meta/tests/SemanticSuite.scala

This is a possible fix to #1133. 
For
```scala
import scala.concurrent.ExecutionContext.Implicits.global
val f1 = scala.concurrent.Future {1}
val f2 = scala.concurrent.Future {2}
for (v1 <- f1; v2 <- f2 if v1 > v2) yield v1+v2
```
it generates:
```
[169..169): *.flatMap[Int](*)(scala.concurrent.ExecutionContext.Implicits.global)
...
[179..179): *.withFilter(*)(scala.concurrent.ExecutionContext.Implicits.global)
...
[190..190): *.map[Int](*)(scala.concurrent.ExecutionContext.Implicits.global)
...
```

Merging inferred args with calls to synthetics

---

README.md
build.sbt

Gabriele Petronella has many valuable contributions to Scalafix and
Scalameta via PRs, issue discussions and presenting awesome talks about
it at conferences. It is long overdue that we officially recognize his
contributions to Scalameta!

Welcome Gabriele Petronella to the team!

---

.scalafmt.conf
appveyor.yml
project/Versions.scala
project/build.properties
project/plugins.sbt
scalameta/semanticdb-scalac/src/main/scala-2.12.4/scala/meta/internal/SemanticdbAnalyzer.scala

There were a lot of changes in typer between 2.12.3 and 2.12.4, which made this upgrade quite painful. Thanks to @jvican 's work in https://github.com/scala/scala/pull/6013/files we should consider contributing the attachments we use in semanticdb-scalac to scala/scala to avoid hijacking analyzer and maintaining this large chunk of copy-pasted code from typer. Going through such a painful upgrade on every patch upgrade is not sustainable for semanticdb-scalac.

Upgrade semanticdb-scalac to 2.12.4

---

langmeta/shared/src/main/scala/org/langmeta/semanticdb/Denotation.scala
langmeta/shared/src/main/scala/org/langmeta/semanticdb/internal/package.scala
scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/semanticdb/DocumentOps.scala
scalameta/semanticdb-scalac/src/test/scala/scala/meta/tests/DatabaseSuite.scala

The original idea with Option[_] was that
- None indicated members were not stored in the semanticdb
- Some(Nil) indicated members were stored in the semanticdb but this
denotation had no members.
However, after some thinking how this would affect downstream users I
realized it's better to provide that bit of information (members are
persisted/not persisted) in a different place like
`Document.settings.members = all` (related https://github.com/scalameta/scalameta/issues/1151). By using Option[_], we open a can of
worms related to validating consistency, what happens for example if
one Denotation.member is Some(Nil) and another one in the same file is
None? Additionally, in protobuf, it's possible to distinguish None from
Some(Nil).

Make Denotation.members List[Signature] instead of Option[List[_]]

---

build.sbt

This PR is very important for scalameta/language-server where we want to try and build semanticdbs on the fly with the presentation compiler.

Fix #1152, split semanticdb-scalac into library and plugin artifacts

---

.travis.yml
build.sbt
langmeta/shared/src/main/scala/org/langmeta/semanticdb/Database.scala
langmeta/shared/src/main/scala/org/langmeta/semanticdb/internal/package.scala
langmeta/shared/src/main/scala/org/langmeta/semanticdb/internal/vfs/Database.scala
project/Versions.scala
scalameta/dialects/shared/src/main/scala/scala/meta/dialects/package.scala
scalameta/semanticdb-integration/src/main/scala/example/Exclude.scala
scalameta/semanticdb-scalac/src/main/scala-2.11.12/scala/meta/internal/SemanticdbAnalyzer.scala
scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/SemanticdbPipeline.scala
scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/SemanticdbPlugin.scala
scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/semanticdb/ConfigOps.scala
scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/semanticdb/DocumentOps.scala
scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/semanticdb/MessageOps.scala
scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/semanticdb/ParseOps.scala
scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/semanticdb/ReporterOps.scala
scalameta/semanticdb-scalac/src/test/scala/scala/meta/tests/DatabaseSuite.scala

This PR supersedes  #1129. The biggest change is that semanticdbs are persisted immediately after typer, significantly reducing memory pressure for large projects. This change introduces a lot of complexity because some messages like deprecations are reported after typer. The solution in this PR is to append the messages reported after typer into the same .semanticdb file but as a separate m.Database and merge the two databases on m.Database.load. This is not an optimal solution, but it's the best we can do without compromising memory usage.
Fixes #1067

Finish remaining pieces from hackweek

---

build.sbt

Hotfix, 2.1.0 is broken since `addCompilerPlugin(semanticdb-scalac)` causes "Ignoring duplicate plugin semanticdb (scala.meta.internal.SemanticdbPlugin)" warnings at best and InvocationTargetExceptions at work. The pomPostProcess no longer worked after #1159. This change was manually tested locally and the .pom now correctly excludes the semanticdb dependency.

Exclude semanticdb-scalac-core from semanticdb-scalac.

---

bin/ci-publish.sh
bin/test-release.sh

v2.1.1 is broken, see https://github.com/scalameta/scalameta/pull/1160#issuecomment-343679764. This PR addresses it by
1. not running sonatypeRelease from travis, this will need to be done manually from either sbt or from the sonatype ui
2. adding test scripts to ensure a release is complete

Make release infrastructure more robust

---

scalameta/semanticdb-scalac/src/main/scala/scala/meta/interactive/InteractiveSemanticdb.scala
scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/HijackAnalyzer.scala
scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/HijackReporter.scala
scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/ReflectionToolkit.scala
scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/SemanticdbPipeline.scala
scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/SemanticdbPlugin.scala
scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/semanticdb/DocumentOps.scala
scalameta/semanticdb-scalac/src/main/scala/scala/meta/internal/semanticdb/InputOps.scala
scalameta/semanticdb-scalac/src/test/scala/scala/meta/tests/InteractiveSemanticdbSuite.scala

This commit adds a utility to build semanticdb files from a string.
This can be useful both for testing as well as for language-server.

Add InteractiveSemanticdb utility.

---

scalameta/semanticdb-scalac-core/src/main/scala/scala/meta/internal/ReflectionToolkit.scala

It has taken me close to a full day to track down an infinite loop
in the pc to this change. Lesson learned, the presentation compiler
is a fragile beast.
I've manually verified that this patch fixes the infinite loop in language-server

Disable semanticdb-scalac in presentation compiler

---

scalameta/semanticdb-scalac-core/src/main/scala/scala/meta/internal/semanticdb/SymbolOps.scala
tests/jvm/src/test/scala/scala/meta/tests/semanticdb/InteractiveSuite.scala

Previously, semanticdb-scalac would crash when the presentation compiler
emitted erroneous symbols. Now, the plugin returns Symbol.None while
running in interactive mode. The plugin keeps the fail-fast mode for
batch compilation.

Fix #1194, gracefully handle errors for broken code in interactive mode

---

scalameta/contrib/shared/src/main/scala/scala/meta/contrib/implicits/Equality.scala

This will prevent repeated structural equality checks in scalagen

Short circuit equality

---

scalameta/tokens/shared/src/main/scala/scala/meta/tokens/Tokens.scala
tests/shared/src/test/scala/scala/meta/tests/tokens/TokensSuite.scala

```scala
val tokens = "foo".tokenize.get
tokens.slice(1, 0).length
res0: Int = -1
tokens.slice(1, 0).isEmpty
res1: Boolean = false
tokens.slice(100, 200).length
res5: Int = -97
```
/cc @olafurpg

Fix bug in Tokens.slice causing incorrect length

---

scalameta/semanticdb-scalac-core/src/main/scala/scala/meta/internal/semanticdb/PrinterOps.scala
tests/jvm/src/test/scala/scala/meta/tests/semanticdb/TargetedSuite.scala

Fixes #324. The motivation for this commit is to enable scalafix
ExplicitResultTypes to emit accurate path dependent types.

Print this type for abstract prefix.

---

bin/ci-publish.sh
build.sbt

To make it easier to consume latest fixes without triggering a stable
release. We should still be unafraid to cut stable releases, but this
is a nice way to give a pre-release a try before pushing the tag.

Setup publish -SNAPSHOT on merge to master.

---

scalameta/semanticdb-scalac-core/src/main/scala/scala/meta/internal/semanticdb/PrinterOps.scala
tests/jvm/src/test/scala/scala/meta/tests/semanticdb/TargetedSuite.scala

Fixes #1222, unblocking a bug in scalafix ExplicitResultTypes.

Print type ref prefix with type arguments.

---

build.sbt
langmeta/langmeta/shared/src/main/scala/org/langmeta/semanticdb/internal/package.scala
semanticdb/integration/src/main/scala/example/Flags.scala
semanticdb/semanticdb3/semanticdb3.md
semanticdb/semanticdb3/semanticdb3.proto
tests/jvm/src/test/resources/semanticdb.expect

This is something that we lost when migrating from SemanticDB v2 to SemanticDB v3.

Add SymbolInformation.Property.{VALPARAM/VARPARAM}

---

langmeta/langmeta/shared/src/main/scala/org/langmeta/semanticdb/internal/package.scala
semanticdb/integration/src/main/scala/example/local-file.scala
tests/jvm/src/test/resources/semanticdb.expect
tests/jvm/src/test/scala/scala/meta/tests/semanticdb/ExpectSuite.scala

- replace all non-alphanumeric characters with underscore handle
filenames like `foo-bar.scala`.
- strip the suffix when converting from high-level API to low-level
schema to make toDb/toSchema bijective.

Make local symbol suffix more robust.

---

.travis.yml
bin/travis_before_install
build.sbt
project/plugins.sbt

This is a follow-up from https://github.com/scalameta/scalameta/pull/1243 that is limited to just the crosscompilable projects in `semanticdb/`.

Crosscompile semanticdb/ to Scala Native

---

.travis.yml

To speed up non-native entries, native installation is kind of slow.

Update travis script to only run native install on native entry

---

build.sbt

While testing semanticdb-scalac on the ammonite build I hit on binary
incompatibility issues.

Upgrade to fastparse 1.0

---

semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/DocumentOps.scala

This assert triggered several dozen times while compiling ammonite with
latest semanticdb-scalac. Fixes #1272.

Replace assert with guard.

---

.travis.yml
build.sbt
tests/jvm/src/test/scala/scala/meta/tests/semanticdb/MetacScalaLibrary.scala

Fixes #1279. This commit adds a new entry to our matrix build that runs
metac with -P:semanticdb:failures:error on all of scala-library.
The test currently fails due to several bugs in semanticdb-scalac.

Add real-world integration test for metac.

---

COMPATIBILITY.md
build.sbt
project/Mima.scala

We should strive for the compatibility policy to be enforced
completely automatically - without easy-to-reach blanket overrides
like ignoreMimaSettings.

Fully automate enforcement of the compatibility policy

---

build.sbt
langmeta/langmeta/shared/src/main/scala/org/langmeta/io/Fragment.scala
semanticdb/metacp/src/main/scala/scala/meta/internal/metacp/Main.scala
tests/jvm/src/test/scala/scala/meta/tests/cli/BaseCliSuite.scala
tests/jvm/src/test/scala/scala/meta/tests/cli/CliSuite.scala
tests/jvm/src/test/scala/scala/meta/tests/metacp/Jars.scala
tests/jvm/src/test/scala/scala/meta/tests/metacp/MetacpSuite.scala

This commit adds a test suite for running metacp on scala-library and
fixes the following two crashes
- Fix #1303 Fix IndexOutOfBounds
- Fix #1302 Handle NoSymbol

Run metacp on scala-library

---

semanticdb/integration/src/main/scala/example/Types.scala
semanticdb/metacp/src/main/scala/scala/meta/internal/metacp/Main.scala
semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/TypeOps.scala
tests/jvm/src/test/resources/highlevel.expect
tests/jvm/src/test/resources/lowlevel.expect
tests/jvm/src/test/resources/metacp.expect
tests/jvm/src/test/scala/scala/meta/tests/metacp/BaseMetacpSuite.scala
tests/jvm/src/test/scala/scala/meta/tests/metacp/MetacpSuite.scala

Scalac encoded `classOf[T]` singleton types as `ConstantType(Type)`.
This commit adds custom handling for this type in metacp and metac
encoding them instead their widened representation `Class[T]`.
Fixes #1306

Handle constant classOf types.

---

build.sbt

```
~;cls;testsJVM/testOnly scala.meta.tests.trees.ParentSuite
print("+") in `transformer.scala`
[info] Compiling 1 Scala source to /home/gui/scalameta/scalameta/common/jvm/target/scala-2.12/classes...
[info] Compiling 4 Scala sources to /home/gui/scalameta/scalameta/transversers/jvm/target/scala-2.12/classes...
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++[info] ParentSuite:
[info] - Tree.transform does not preserve parent chain origins *** FAILED ***
[info]   5 did not equal 1 (ParentSuite.scala:24)
[info] Run completed in 252 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 0, failed 1, canceled 0, ignored 0, pending 0
[info] *** 1 TEST FAILED ***
[error] Failed tests: …
```

Trigger compilation when a macro change. (fix #1347)

---

semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/SemanticdbPipeline.scala

Fix NPE in SemanticdbPipeline happening when loading the semanticdb
plugin in ammonite
Fixes https://github.com/scalameta/scalameta/issues/1387

Fix NPE in SemanticdbPipeline

---

semanticdb/metacp/src/main/scala/scala/meta/internal/metacp/Main.scala

This reverts commit 7eb7ce8567ea801d06eb7499268a8cc52bd7b0e3. The version number was apparently already included in `defaultCacheDir`.

Revert "Prefix cache file by metacp version."

---

.scalafmt.conf
semanticdb/metacp/src/main/scala/scala/meta/internal/javacp/JavaTypeSignature.scala

It was excluding everything in the `javacp` package due to the `.java`
rule.

Refine Scalafmt project.excludeFilters.

---

langmeta/langmeta/shared/src/main/scala/org/langmeta/semanticdb/internal/vfs/SemanticdbPaths.scala
semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/ConfigOps.scala
semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/DocumentOps.scala
semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/HijackAnalyzer.scala
semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/SemanticdbPipeline.scala
semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/SemanticdbPlugin.scala

* Added custom targetroot that checks whether the compilation is occurring in an ammonite context. If it's the case, targetroot is now set to $pwd/out (to keep consistency with mill)
* Added various checks to allow `sc` files in addition to `scala files`
This PR, combined with the following `~/.ammonite/predefScript.sc`, results in semanticdb outputting something under `$pwd/out` when running `amm` on a script. 
```
import $plugin.$ivy.`org.spire-math::kind-projector:0.9.4`
import $plugin.$ivy.`org.scalameta:semanticdb-scalac_2.12.4:3.4.0-5-86720f75-20180307-2220`
val scalacOptions = List(
"-Yrangepos:true",
"-Xplugin:semanticdb",
"-Xplugin-require:semanticdb"
)
interp.configureCompiler(_.settings.processArguments(scalacOptions, true))
```
The content of the semanticdb is far from perfect …

Progress towards ammonite support

---

build.sbt

pprint is indispensable for my productivity, it's a small module that
deserves inclusion in the standard library. This commit adds an explicit
dependency on pprint because I'm tired of adding this dependency in my
private local setup causing compilation errors when other people try my
WIP branches.

Add a dependency on pprint.

---

langmeta/langmeta/shared/src/main/scala/org/langmeta/semanticdb/internal/package.scala

These methods are useful for scalafix to convert Denotation to
SymbolInformation.

Extract SymbolInformation.{Kind,Properties} conversion logic.

---

tests/jvm/src/test/scala/scala/meta/tests/semanticdb/SymbolSuite.scala

While working on fixing #1424 I discovered that the symbol parser
already works as I expected. A `_root_.` prefix is discarded.  This
commit introduces no functional changes to the symbol parser, just adds
test to validate the current existing behavior. Fixes #1424

Add tests to validate symbol parser behavior for _root_. prefix.

---

langmeta/langmeta/shared/src/main/scala/org/langmeta/semanticdb/Denotation.scala
langmeta/langmeta/shared/src/main/scala/org/langmeta/semanticdb/internal/package.scala
semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/DocumentOps.scala

We do not want to expose these fields in the Scalameta/Scalafix public API.

Make Denotation.{tpe, accessibility, annotations} package private.

---

semanticdb/metacp/src/main/scala/scala/meta/internal/metacp/Main.scala

Closes #1398 
I've essentially reverted 1cd839e462a7cf9ac1414d9dc553d2e220d44e86, plus I've refactored it to use an `AtomicBoolean` instead of a `Boolean` to prevent ghost writes (i.e. using a `Boolean` a thread could accidentally override a `false` value written by another thread with a `true`)
On my machine, this leads to a speedup of about 1.4x when running `testsJVM/testOnly scala.meta.tests.metacp.*`.
I'm unsure on how to test this further: I wasn't able to reproduce the deadlock, so I don't really know what I'm looking for here.
Thoughts, @olafurpg / @xeno-by?

Re-enable par on metacp

---

langmeta/langmeta/jvm/src/main/scala/org/langmeta/internal/io/PlatformFileIO.scala

Files.createDirectories doesn't throw if a parent exists and is a dir,
but it does throw if a parent exists and is a symlink.

Fix an oversight in newJarFileSystem

---

semanticdb/metacp/src/main/scala/scala/meta/internal/metacp/Main.scala
semanticdb/metacp/src/main/scala/scala/meta/metacp/Settings.scala
tests/jvm/src/test/scala/scala/meta/tests/metacp/BaseMetacpSuite.scala

This commit replaces the usage of `.par.flatMap` with `.par.foreach` as
an attempt to prevent a difficult-to-reproduce deadlock problem in
parallel collections.  The parallel behavior is disabled by default and
can be enabled with the --par option.
Using --par seems to yield ~40-50% faster performance in
MetacpCrashSuite on my Macbook. It takes ~36s to run with --par and ~57s
without --par.
The theory for why `.par.foreach` is better than `.par.flatMap` is based
on the experience in scalafmt/scalafix where I've used that same pattern
for over two years and have not seen reports of deadlock behavior.
I have never used `.par.flatMap` in my applications.
Fixes #1398

Use `.par.foreach` and introduce metacp --par option.

---

langmeta/langmeta/jvm/src/main/scala/org/langmeta/internal/io/PlatformFileIO.scala
semanticdb/metacp/src/main/scala/scala/meta/internal/metacp/Main.scala
tests/jvm/src/test/scala/scala/meta/tests/metacp/MetacpCacheSuite.scala

While testing metacp in scalafix I encountered frequent flaky test
failures due to "writing to closed file system" errors caused by
`FileSystems.getFileSystem` reusing open file systems.  This leaks
resources, but I see no alternative that does not involve refactoring
everything to java.io or global mutable state for reference counting
open file systems per zip file.

Don't close nio.FileSystem.

---

scalameta/contrib/shared/src/main/scala/scala/meta/contrib/AssociatedComments.scala
tests/shared/src/test/scala/scala/meta/tests/contrib/AssociatedCommentsTest.scala

Fixes https://github.com/scalacenter/scalafix/issues/627
This issue is similar to #897, but affecting comments at the bottom of a file (== ignored).
/cc. @olafurpg

Fix: handle comments before EOF

---

semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/ReporterOps.scala
tests/jvm/src/test/scala-2.11/scala/meta/tests/semanticdb/TargetedSuite2_11.scala
tests/jvm/src/test/scala-2.12/scala/meta/tests/semanticdb/TargetedSuite2_12.scala
tests/jvm/src/test/scala/scala/meta/tests/semanticdb/SemanticdbSuite.scala
tests/jvm/src/test/scala/scala/meta/tests/semanticdb/TargetedSuite.scala

Relax RelevantMessage condition to forward unused local warnings.
Fix #1530

Include diagnostics with offset positions

---

build.sbt

The former does not work.
```
[info] dialectsJVM/*:isSnapshot
[info]     true
[info] dialectsJVM/*:version
[info]     4.0.0-M1
[info] dialectsJVM/*:publishTo
[info]     Some(sonatype-staging: https://oss.sonatype.org/service/local/staging/deploy/maven2)
```

Replace isSnapshot.value with version.value.endsWith("SNAPSHOT")

---

build.sbt
project/plugins.sbt
project/project/plugins.sbt
semanticdb/metacp/src/main/scala/scala/meta/metacp/Settings.scala
tests/jvm/src/main/scala/scala/meta/tests/metacp/Jars.scala

To follow Windows and macOS conventions, we are expected to qualify the
project name with a domain name.  Given that "SemanticDB" is also used
in Emacs, there's a valid risk of conflict.
Fixes #1599

Upgrade to directories-jvm 10.

---

build.sbt
scalameta/testkit/src/main/scala/scala/meta/testkit/DiffAssertions.scala
scalameta/testkit/src/main/scala/scala/meta/testkit/StringFS.scala
semanticdb/metacp/src/main/scala/scala/meta/internal/index/Index.scala
semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/SemanticdbPipeline.scala
tests/jvm/src/test/scala-2.12/scala/meta/tests/semanticdb/IncrementalSuite.scala
tests/jvm/src/test/scala-2.12/scala/meta/tests/semanticdb/ZincProject.scala
tests/jvm/src/test/scala/scala/meta/tests/api/SurfaceSuite.scala
tests/jvm/src/test/scala/scala/meta/tests/semanticdb/ExpectSuite.scala

This commit fixes a bug in metac so that it plays nicely with
incremental compilation under zinc. We use bloop in the tests to
simplify the integration with zinc and reproduce the bug. This
setup provides a modestly rapid edit/test/debug workflow.
Notes:
- To make semanticdb.semanticidx incremental, we merge an existing index
file if it exists with the index metadata that we are about to
persist. Along the way, we prune outdated data that references
non-existing URIs.
- Zinc depends on an outdated version of ScalaPB (v0.6), which we
exclude in build.sbt in favor of the latest version of ScalaPB (v0.7).
Fortunately, Zinc uses only ScalaPB APIs that are available in v0.7
- Zinc is only compiled against 2.12 so the incremental tests run only
for 2.12.
- The incremental tests take ~10-15s to …

Make metac index incremental.

---

semanticdb/metacp/src/main/scala/scala/meta/internal/metacp/Main.scala
semanticdb/metacp/src/main/scala/scala/meta/internal/metacp/MetacpGlobalCache.scala
semanticdb/semanticdb/guide.md

I've encountered several difficult-to-reproduce bugs related to the global metacp cache while testing scalafix on larger project. This PR should hopefully improve the situation, but unfortunately I don't know how to best test it so there are no accompanying tests.

Improve metacp global cache handling

---

semanticdb/metacp/src/main/scala/scala/meta/internal/javacp/Javacp.scala
semanticdb/semanticdb3/semanticdb3.md
tests/jvm/src/test/scala/scala/meta/tests/semanticdb/JavacpSuite.scala

Fixes https://github.com/scalameta/scalameta/issues/1460.
Note that we can't preserve interleaved order of fields/methods since
ASM separates them in different lists. If we write a custom ASM
ClassNodeVisitor we could probably retrieve it but that can be left for
another PR.

Preserve declaration order of methods in javacp.

---

build.sbt
project/build.properties
scalameta/testkit/src/main/scala/scala/meta/testkit/Corpus.scala

since there is a source-incompatible change in 0.1.2, this upgrade helps
the Scala community build, where we are normally on the latest versions of
things
sbt version bump is just for good measure

use latest geny version (& bump sbt version)

---

build.sbt

this is needed for the Scala community build. we at least need every
build definition to be loadable on JDK 9+ (even if the project doesn't
actually build, tests pass, etc)

add escape hatch allow building on JDK 9+

---

scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/CharArrayReader.scala
scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala
tests/jvm/src/test/resources/unicode.txt

See https://github.com/scalameta/scalameta/issues/1574 https://github.com/scalacenter/scalafix/issues/619
In addition to the case specified in the issue (vanishing unicode literals in pattern position), I found some other cases (see `tests/jvm/src/test/resources/unicode.txt`)
Now we have some kind of cases that occur the bug,
It maybe reasonable to do that for any call of `potentialUnicode` which may be called by `nextChar` as [@avdv says in the original issue](https://github.com/scalameta/scalameta/issues/819#issuecomment-363248268).
Tested in sbt console.
```
$ cat target/foo.scala
case (r, \u03c6) =>
$ sbt console
...
scala> import scala.meta._
import scala.meta._
scala> Input.File(AbsolutePath("target/foo.scala")).text.parse[Case].get.tokens.map(_.syntax)
res0: …
```

Fix vanishing unicode literals in pattern position or other cases

---

semanticdb/integration/src/main/java/com/javacp/annot/ClassAnnotation.java
semanticdb/integration/src/main/java/com/javacp/annot/ConstructorAnnotation.java
semanticdb/integration/src/main/java/com/javacp/annot/FieldAnnotation.java
semanticdb/integration/src/main/java/com/javacp/annot/InterfaceAnnotation.java
semanticdb/integration/src/main/java/com/javacp/annot/LocalAnnotation.java
semanticdb/integration/src/main/java/com/javacp/annot/MacroAnnotation.java
semanticdb/integration/src/main/java/com/javacp/annot/MethodAnnotation.java
semanticdb/integration/src/main/java/com/javacp/annot/ObjectAnnotation.java
semanticdb/integration/src/main/java/com/javacp/annot/PackageAnnotation.java
semanticdb/integration/src/main/java/com/javacp/annot/PackageObjectAnnotation.java
semanticdb/integration/src/main/java/com/javacp/annot/ParameterAnnotation.java
semanticdb/integration/src/main/java/com/javacp/annot/SelfParameterAnnotation.java
semanticdb/integration/src/main/java/com/javacp/annot/TraitAnnotation.java
semanticdb/integration/src/main/java/com/javacp/annot/TypeAnnotation.java
semanticdb/integration/src/main/java/com/javacp/annot/TypeParameterAnnotation.java
semanticdb/integration/src/main/java/com/javacp/annot/usage/AnnotatedInterface.java
semanticdb/integration/src/main/java/com/javacp/annot/usage/AnnotatedPackage.java
semanticdb/integration/src/main/scala/example/Annotations.scala
semanticdb/metacp/src/main/scala/scala/meta/internal/scalacp/SymbolInformationOps.scala
tests/jvm/src/test/resources/metac-metacp.diff
tests/jvm/src/test/resources/metac.expect
tests/jvm/src/test/resources/metac.index
tests/jvm/src/test/resources/metacp.expect
tests/jvm/src/test/resources/metacp.index

It was pretty easy after all. There is two limitations:
* scalap does not keep annotations parameter
* scalap does not tell me if the annotation is synthetic (ex: macro)

Support SymbolInformation.annotations in metacp (fix #1315)

---

scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala

Resolves #1661 
Motivation: There are many rules to govern whether or not a sequence of characters is legal for a term or type name in scalac, as defined by [scala/scala's spec/01-lexical-syntax.md](https://github.com/scala/scala/blob/2.13.x/spec/01-lexical-syntax.md#lexical-syntax).
This PR is an attempt at bringing `cantBeWrittenWithoutBackquotes` in line with scalac's expectations.
With this change, I can remove a workaround in [twilio/guardrail](https://github.com/twilio/guardrail/blob/cbf9acd9e8ff226cc0f4bbf2f278669071126d5e/modules/codegen/src/main/scala/com/twilio/guardrail/SwaggerUtil.scala#L269-L333)
```
// 100k iterations
scala> benchmark(100000) { assert(cantBeWrittenWithoutBackquotes(Term.Name("this is a very long test"))) }
Average: 0.01088
// 1M iterations
scala> …
```

Transcribing scalac parsing logic into cantBeWrittenWithoutBackquotes

---

scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/CharArrayReader.scala
tests/shared/src/test/scala/scala/meta/tests/tokenizers/TokenizerSuite.scala

Fixes #1177 & #1597 (duplicate)
Seemed to be an off-by-one error from the exception message to me. With the offset being set wrong somewhere, and Scalameta crashing on that somewhere later on.
Would love to hear from someone with more experience in the codebase to see what further steps can be

Fix crlf after quasiquotes throwing InvariantFailedException

---

README.md
build.sbt

Max made a strategically important contribution to the Scalameta
vision by implementing a Javac compiler plugin that produces SemanticDB
payloads.
This is a critical advance of our vision to make SemanticDB a polyglot
format for semantic information, and we'd like to officially recognize
that by making Max part of the Scalameta team.

Welcome Max Ovsiankin to the team!

---

semanticdb/metap/src/main/scala/scala/meta/internal/metap/SyntheticPrinter.scala
tests/jvm/src/test/resources/metac.expect

Continuing discussion from #1712, this changes the metap printout to be a backticked identifier. The goal is to have a printout that explains what is happening, is syntactically valid and can parse, but shouldn't compile.

Change metap macro synthetic printout to explain the expandee

---

semanticdb/metap/src/main/scala/scala/meta/internal/metap/SymbolInformationPrinter.scala
semanticdb/metap/src/main/scala/scala/meta/internal/metap/SyntheticPrinter.scala
semanticdb/metap/src/main/scala/scala/meta/internal/semanticdb/Print.scala
tests/jvm/src/test/scala/scala/meta/tests/semanticdb/PrintSuite.scala

These avoid the need for scalafix to poke further into internals.

Add pretty-printers for synthetic/signature/tree/constant

---

notes/quasiquotes.md

This commit formats the quasiquote markdown document with Prettier
(https://prettier.io/) to make it compatible with commonmark so that it
renders normally in Docusaurus. To make the tables render correctly, we
alsoy escape pipe characters `|` for `Pat.Alternative` and `Type.Or`

Reformat quasiquote spec according to commonmark

---

notes/quasiquotes.md
semanticdb/semanticdb3/semanticdb3.md

These dead links were detected by mdoc while I was working on the new scalameta docs
```
warning: quasiquotes.md:63:53: warning: Unknown link '/scalameta/dialects/src/main/scala/scala/meta/dialects/package.scala'. To fix this problem, either make the link relative or turn it into complete URL such as http://example.com/scalameta/dialects/src/main/scala/scala/meta/dialects/package.scala.
| With              | `t"$tpe with $tpe"` (only for [supported dialects](/scalameta/dialects/src/main/scala/scala/meta/dialects/package.scala))              |
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
warning: quasiquotes.md:64:50: warning: Unknown link '/scalameta/dialects/src/main/scala/scala/meta/dialects/package.scala'. To fix this problem, either make …
```

Fix or remove dead links

---

semanticdb/metacp/src/main/scala/scala/meta/internal/metacp/ClassfileInfos.scala
semanticdb/metacp/src/main/scala/scala/meta/internal/metacp/Main.scala
semanticdb/metacp/src/main/scala/scala/meta/internal/scalacp/Scalacp.scala
semanticdb/metacp/src/main/scala/scala/meta/internal/scalacp/SymbolInformationOps.scala
semanticdb/metacp/src/main/scala/scala/meta/metacp/Settings.scala
semanticdb/semanticdb3/guide.md
semanticdb/symtab/src/main/scala/scala/meta/internal/symtab/GlobalSymbolTable.scala
tests/jvm/src/test/scala/scala/meta/tests/metacp/MetacpErrorSuite.scala

Many JVM-related tools like Javac, Scalac (and the Hotspot JVM itself)
perform lazy linking, which means that missing dependencies aren't
a problem unless they are explicitly used.
At the moment, Metacp is uncharacteristically strict about this.
Since it performs eager conversion to SemanticDB, any missing dependencies
result in an immediate error.
While GlobalSymbolTable solves this problem by being lazy, there are
still some use cases (one of them being Rsc) that rely on eager
conversion. That doesn't work too well in a number of scenarios
including shading and `<dependency><optional>true</optional></dependency>`.
This commit provides a workaround for this problem by introducing the
ability to silence missing symbol errors and emit empty signatures instead.

Introduce --stub-broken-signatures for Metacp

---

semanticdb/semanticdb3/guide.md
semanticdb/semanticdb3/semanticdb3.md

This makes them appear nicely in the new website.

Lower header size for "semanticdb-based tools" in guide

---

scalameta/dialects/shared/src/main/scala/scala/meta/dialects/package.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/DottySuite.scala

Trailing commas have been added to Dotty in https://github.com/lampepfl/dotty/pull/3463

Enable trailing commas in dotty

---

scalameta/contrib/shared/src/main/scala/scala/meta/contrib/TreeOps.scala
scalameta/testkit/src/test/scala/scala/meta/tests/transversers/TraverserOrder.scala
scalameta/transversers/shared/src/main/scala/scala/meta/transversers/Api.scala
scalameta/transversers/shared/src/main/scala/scala/meta/transversers/SimpleTraverser.scala
tests/shared/src/test/scala/scala/meta/tests/contrib/TreeOpsSuite.scala
tests/shared/src/test/scala/scala/meta/tests/transversers/SimpleTraverserSuite.scala
tests/shared/src/test/scala/scala/meta/tests/transversers/TransformerSuite.scala
tests/shared/src/test/scala/scala/meta/tests/transversers/TraverserSuite.scala

While profiling Scalafix I found out that the main hotspot is `scala.meta.Traverser`. It accounts for ~60% of the running time (see details here: https://github.com/scalacenter/scalafix/issues/894). It turns out that the code generated by the `scala.meta.internal.transversers.TraverserMacros` macro annotation contains a large amount of pattern matching making traversal terribly slow.
This PR introduces a new traverser which relies on `Tree.children`. JMH benchmarks show that it makes tree traversal ~20-70 times faster than the existing one:
>As input for the benchmark, I picked some random *.scala files with 3 (XS), 50 (S), 500 (M), 1000 (L) and 5800 (XL) lines of code and measured the cost of traversing the entire tree. FYR, the source code can be found here …

Faster tree traversal

---

build.sbt

This slims the fatjar from 20mb down to 12mb. I don't know why these
artifacts started being included in the fatjar but I suspect it's caused
by the custom javaHome settings.
Before:
```
$ du -h semanticdb-scalac.jar
20M
```
After
```
$ du -h semanticdb-scalac.jar
12M
```

Exclude `sun._` and `com.sun._` from semanticdb-scalac jar

---

semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/Hex.scala
semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/InputOps.scala

This package has been deprecated in Java 9 and was removed in Java 11.
This change lays ground for Java 11 support by not using the `DatatypeConverter`
of this package anymore and uses an internal function instead.
Fixes #1796.

Remove `javax.xml.bind` usage

---

scalameta/transversers/shared/src/main/scala/scala/meta/transversers/SimpleTraverser.scala
tests/jvm/src/test/scala/scala/meta/tests/api/SurfaceSuite.scala
tests/shared/src/test/scala/scala/meta/tests/prettyprinters/PublicSuite.scala

There is no reasons users shouldn't be able to extend SimpleTraverser
to implement custom traversal strategies as we document here:
https://scalameta.org/docs/trees/guide.html#custom-traversals
cc/ @marcelocenerine

Make SimpleTraverser public

---

build.sbt
scalameta/contrib/shared/src/main/scala/scala/meta/contrib/DocToken.scala
scalameta/contrib/shared/src/main/scala/scala/meta/contrib/ScaladocParser.scala
scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala
scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/XmlParser.scala

To avoid binary conflicts with fastparse v2. This commit doesn't fully
solve our problem since scalapb still brings in fastparse, we may have
to shade scalapb in a separate PR.
Fix #1800

Shade fastparse v1 under scala.meta.internal.fastparse

---

README.md

I'm very proud of what we've achieved in Scalameta.
What started as a research macro system for Scala, ended up as a foundation
for a family of new-style developer tools, with more than 10000 commits
and 200 contributors. Even more, one of our technologies - SemanticDB -
has become a metadata format for Rsc, a brand new Scala compiler.
I couldn't have wished for more!!
Olaf, the stage is yours.

Goodbye, Scalameta!

---

scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala

Fixes #1826 syntax printer bugs.
~One case still fails: `list map (_ diff foo)`. It adds an extra set of parentheses around the argument. I am unsure why that fails but another case `list map (_ -> foo)` does work, as they seem to have the same AST.~

Fix for #1826 ApplyInfix parentheses syntax

---

build.sbt
scalameta/io/js/src/main/scala/java/io/File.scala
scalameta/io/js/src/main/scala/scala/meta/internal/io/JSIO.scala
scalameta/io/js/src/main/scala/scala/meta/internal/io/NodeNIOPath.scala
scalameta/io/js/src/main/scala/scala/meta/internal/io/PlatformFileIO.scala

This effectively reverts https://github.com/scalameta/scalameta/commit/032dc56318bc81d3ecd4aa39040a15a74bf4fd8c#diff-e392e6315fa9beedb70580bda57714c0
According to [a discussion with Sébastien on Gitter](https://gitter.im/scala-js/scala-js?at=5c7fc7f1f895944c084d730b), accessing `require` from the Global scope is invalid. The reason it works is that tests are run into a sort-of node REPL, where the global scope has a `require` function. However, when running Scalameta as a script, `require` is `undefined`, causing a runtime failure.
It seems we have to use `@JSImport` to reference the native `path` and `fs` modules.
It used to be that way, but it was changed by @jonas at some point in 2017 (see the commit below), but I couldn't find any further context for that change.

Use @JSImport to load native "fs" and "path" modules

---

semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/LanguageOps.scala

This allows to use Typelevel-specific features like literal types.

LanguageOps: Detect Typelevel compiler

---

semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/DiagnosticOps.scala

`withStart()` may result in an invalid range:
```
java.lang.AssertionError: assertion failed: bad position: [291:282]
at scala.Predef$.assert(Predef.scala:235)
at scala.reflect.internal.util.Position$.validate(Position.scala:34)
at scala.reflect.internal.util.Position$.range(Position.scala:51)
at scala.reflect.internal.util.InternalPositionImpl.copyRange(Position.scala:205)
at scala.reflect.internal.util.InternalPositionImpl.withStart(Position.scala:124)
at scala.reflect.internal.util.InternalPositionImpl.withStart$(Position.scala:124)
at scala.reflect.internal.util.Position.withStart(Position.scala:12)
at scala.meta.internal.semanticdb.scalac.DiagnosticOps$XtensionCompilationUnitDiagnostics.$anonfun$reportedDiagnostics$1(DiagnosticOps.scala:22)
[...]
```
This happens whenever the new …

DiagnosticOps: Fix invalid range when `-Yrangepos` is disabled

---

scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala

`Term.Select` placeholders would only be checked one level deep instead of recursively (`_.foo.bar.baz`). This PR fixes that and simplifies the needsParens function a little bit

Fix multiple Term.Select parentheses (prettyprinting syntax)

---

semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/SyntheticOps.scala
tests/jvm/src/test/resources/metac.expect
tests/jvm/src/test/scala/scala/meta/tests/semanticdb/InteractiveSuite.scala
tests/jvm/src/test/scala/scala/meta/tests/semanticdb/PrintSuite.scala
tests/jvm/src/test/scala/scala/meta/tests/semanticdb/SemanticdbSuite.scala

Previously, synthetic implicit conversions only contained a symbol
reference to the conversion method but not from which qualifier that
method came. For example, we only knew that the `asJava` symbol
`scala/collection/convert/DecorateAsJava#seqAsJavaListConverter().` was
referenced but not that it came from the object
`scala/collection/JavaConverters.`.

Include qualifier of implicit conversions.

---

scalameta/dialects/shared/src/main/scala/scala/meta/dialects/package.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/Scala213Suite.scala

Resubmitting this PR (originally #1879) as requested by the CLA error message in CI. I'm sure I've signed these CLAs before but I did them both again.
I've just copied the relevant tests from the Dotty dialect test suite—I'm happy to expand them if people want.

Scala 2.13 supports by-name implicits

---

scalameta/dialects/shared/src/main/scala/scala/meta/dialects/package.scala
scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala
scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyTokenData.scala
tests/shared/src/test/scala-2.12/meta/tests/dialects/DialectSuite.scala
tests/shared/src/test/scala/scala/meta/tests/prettyprinters/PublicSuite.scala
tests/shared/src/test/scala/scala/meta/tests/tokenizers/TokenizerSuite.scala

This PR adds a new `allowNumericLiteralSeparators` option to
`Dialect`, which is only true in the `Scala213` dialect.
This is mostly a direct port of the respective scalac commit
(https://github.com/scala/scala/commit/c3591880d809985fd3de96462bf2742823b66234?w=1),
including the positive and negative tests.
--
(but tests gave me the confidence to open this PR)

Add support for Scala 2.13 numeric literal separators

---

build.sbt
scalameta/parsers/js/npm/package.json

Somewhere along the way this broke, so `parseStat` and `parseSource` were being exported as global functions instead of as a module.
Unfortunately I botched the 4.2.0 release on npm, so I republished the correct version as 4.2.1 (Scalameta will have to catch up :P )
4.2.1 is working 🎉 https://runkit.com/embed/l27a3qm5mggp

Scalameta parsers fix

---

.gitignore
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala

Also I added some extra stuff to the gitignore as I was using Metals and it generated lots of untracked files. 
No one responded to confirm the original issue yet as it was only an hour or so ago, but the fix looked simple so thought I'd have a go - if I'm missing something or if this is part of a more general check that can be included let me know, happy to have a go at that too (but I think the `guessIsBackquoted` method in there covers most bases except this one)
Fixes #1895

Adding a check to needsBraces method for interpolators arg names that begin with '_'

---

scalameta/io/shared/src/main/scala/scala/meta/io/AbsolutePath.scala
semanticdb/integration/src/main/scala/example/filename with spaces.scala
semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/InputOps.scala
semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/SemanticdbPaths.scala
semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/SemanticdbPipeline.scala
tests/jvm/src/test/resources/example/filename with spaces.scala
tests/jvm/src/test/resources/metac.expect
tests/jvm/src/test/resources/metacp.expect
tests/jvm/src/test/scala-2.12/scala/meta/tests/cli/CliSuite.scala
tests/jvm/src/test/scala/scala/meta/tests/semanticdb/MD5Suite.scala

Previously this caused an input file "filename with spaces.scala" to briefly generate
"filename%20%with%20spaces.scala.semanticdb" only to have it subsequently deleted by
RemoveOrphanSemanticdbFiles (which attempts to remove stale semanticdb outputs).
Fixes #1888

Fixes mishandling of URI -> nio.file.Path conversions and splicing.

---

scalameta/io/shared/src/main/scala/scala/meta/io/AbsolutePath.scala
tests/shared/src/test/scala/scala/meta/tests/io/NIOPathTest.scala

Previously, calling `AbsolutePath.toURI` could throw a null pointer
exception for directories inside jars. Now, we guard against null
so calling `.toURI` succeeds.
This fixes a regression from #1890. Could you take a look @jameskoch?

Guard against null in `URI.getPath`.

---

scalameta/tokens/shared/src/main/scala/scala/meta/tokens/Tokens.scala
tests/shared/src/test/scala/scala/meta/tests/tokens/TokensSuite.scala

If the predicate passed to `span` is true for all of the elements in a collection, the first element of the result should be the original collection and the second should be empty (and the reverse for `spanRight`).
The current implementation is broken because it doesn't handle the case where `indexWhere` returns -1. I've included some failing tests that show the issue, and a fix. I took a quick look around for similar bugs but didn't see anything.

Fix span methods on Tokens

---

scalameta/inputs/shared/src/main/scala/scala/meta/internal/inputs/InternalInput.scala
scalameta/tokenizers/js/src/main/scala/scala/meta/internal/tokenizers/Compat.scala
scalameta/tokenizers/js/src/main/scala/scala/meta/internal/tokenizers/PlatformTokenizerCache.scala
scalameta/tokenizers/jvm/src/main/scala/scala/meta/internal/tokenizers/Compat.scala
scalameta/tokenizers/jvm/src/main/scala/scala/meta/internal/tokenizers/PlatformTokenizerCache.scala
scalameta/tokenizers/native/src/main/scala/scala/meta/internal/tokenizers/Compat.scala
scalameta/tokenizers/native/src/main/scala/scala/meta/internal/tokenizers/PlatformTokenizerCache.scala
scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/ScalametaTokenizer.scala

Previously, Scalameta kept a global cache for the tokens of all inputs.
Now, the global cache has been replaced with a cache that's local to the
input itself.
The new solution was not possible before #1863 since the `Input` type
was kept in a separate module from `Tokens`. Now the two types live in
the same module so it's possible to make the token cache local to
inputs.
I verified that this change does not regress the performance of
Scalafmt.

Get rid of global token cache, fixes #1068

---

semanticdb/integration/src/main/scala/example/InstrumentTyper.scala
semanticdb/integration/src/main/scala/example/Types.scala
semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/TextDocumentOps.scala
tests/jvm/src/test/resources/example/InstrumentTyper.scala
tests/jvm/src/test/resources/example/Types.scala
tests/jvm/src/test/resources/metac.expect
tests/jvm/src/test/resources/metacp.expect

Before, classOf didn't generate occurrences, both for `classOf` method.
Now, it generates them as `scala.Predef.classOf()`. Tests were adjusted to reflect the changes.
Related to https://github.com/scalameta/scalameta/issues/1909

Add occurrences for classOf

---

build.sbt
project/plugins.sbt

By default, source maps generated by Scala.js compiler point to local files.
This PR changes this so that for non-snapshot versions, source maps point to github raw content.

Scala.js source maps are now pointing to github

---

semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/InputOps.scala

This is my naive approach to fixing #1966 
It looks like there has been a regression since [this commit](https://github.com/scalameta/scalameta/pull/1890/files#diff-278ea33c862c6577981ab8da76b8a81fR59). The problem is this check:
```scala
gfile.file.toPath.startsWith(config.sourceroot.toNIO)
````
When check to make sure this is true, however let's take the following URI as an example:
```text
file:///Users/ckipp/Documents/scala-workspace/test-project/example/src/Main.scala
````
If I used `metac` in the `test-project` directory and considered that to be root, then targeted `Main.scala` like this `metac example/src/Main.scala` I would get the following to values for the above check.
`gfile.file.toPath`                --> `example/src/Main.scala`
`config.sourceroot.toNIO` --> …

change the way we check for being in the source root

---

build.sbt
semanticdb/scalac/library/src/main/scala-2.13.0-/scala/meta/internal/semanticdb/scalac/SemanticdbReporter.scala
semanticdb/scalac/library/src/main/scala-2.13.1+/scala/meta/internal/semanticdb/scalac/SemanticdbReporter.scala

This commit fixes #1505 and also updates Scala 2.13.1+ implementation to
new reporters API introduced in Scala 2.13.1.
A simple test would be nice but I'm not sure where to put it (`scala-compiler` is required on classpath).

properly forward error/warning count to and from wrapped scalac reporter

---

CONTRIBUTING.md

[changelog](https://github.com/scalameta/scalameta/tree/master/changelog) not updated for three years. And I don't know is signed CLA really **necessary** but red CI scares me :)

CONTRIBUTING actualized

---

.gitignore
docs/semanticdb/guide.md
semanticdb/semanticdb3/guide.md

This is a code parsing params, it is expected to provide them with single '-' but in website documentation there is '--' which throws unknown parameters error
```scala
case "-compact" +: rest if allowOptions =>
loop(settings.copy(format = Format.Compact), allowOptions = true, rest)
case ("-detailed" | "-pretty") +: rest if allowOptions =>
loop(settings.copy(format = Format.Detailed), allowOptions = true, rest)
case "-proto" +: rest if allowOptions =>
loop(settings.copy(format = Format.Proto), allowOptions = true, rest)
```
Also added to .gitignore 'metals.sbt' (it should not be commited similary to as it is in metals, right?)

Fix documentation for arguments for metap

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala

Hello!
This is my first contribution here and I might be wrong with suite for tests, naming convention and other stuff.
Fixes #492 
And this is a source of https://github.com/scalameta/scalafmt/issues/1245

Fixed NoSuchElementException when parse Unit with infix operations

---

semanticdb/scalac/library/src/main/scala-2.13.0-/scala/meta/internal/semanticdb/scalac/SemanticdbReporter.scala

The version before caused this issue in case of any errors:
```
ERROR Unexpected error when compiling root: 'assertion failed: 
name
while compiling: /home/tgodzik/Documents/workspaces/metals-sample/src/main/scala/Main.scala
during phase: globalPhase=erasure, enteringPhase=posterasure
library version: version 2.12.11
compiler version: version 2.12.11
reconstructed args: ...
last tree to typer: TypeTree(class String)
tree position: line 12 of /home/tgodzik/Documents/workspaces/metals-sample/src/main/scala/Main.scala
tree tpe: String
symbol: final class String in package lang
symbol definition: final class String extends Serializable with Comparable with CharSequence (a ClassSymbol)
symbol package: java.lang
symbol owners: class String
call site: method main in object Main in package …
```

Fix compile error reporting when using smenaticdb plugin

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/PackageSuite.scala

Fixes issue `sbt/A.scala#L2`
Fixes issue `breeze/package.scala#L43`
(they are both the same issues)
https://github.com/scalameta/scalameta/issues/312#issuecomment-267081928

Fix parsing package with leftbrace in newline

---

semanticdb/integration/src/main/scala/example/EtaExpansion.scala
semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/TextDocumentOps.scala
tests/jvm/src/test/resources/example/EtaExpansion.scala
tests/jvm/src/test/resources/metac.expect
tests/jvm/src/test/resources/metacp.expect

When the Scala parser encounters an underscore while parsing expressions it
discards that token's position and creates a `MethodValue` of the target
method:
case USCORE =>
atPos(t.pos.start, in.skipToken()) { MethodValue(stripParens(t)) }
Then the Scala typechecker creates a `Function0` out of that, defining its
position as the position of the underlying method value:
val pos = methodValue.pos
// must create it here to change owner (normally done by typed's typedFunction)
val funSym = context.owner.newAnonymousFunctionValue(pos)
new ChangeOwnerTraverser(context.owner, funSym) traverse methodValue
val result = typed(Function(List(), methodValue) setSymbol funSym setPos pos, mode, pt)
The result is that `XtensionCompilationUnitDocument#toTextDocument`, which
uses positions, incorrectly …

Fix symbols of nullary method eta-expansions

---

build.sbt
docs/semanticdb/guide.md

Fixes #2023 and removes some outdated docs.

Use coursier install for metac and metap

---

scalameta/tokens/shared/src/main/scala/scala/meta/tokens/Tokens.scala

The issues were caused by https://github.com/scala/scala/commit/b20dd00b11f06c14c823d277cdfb58043a2586fc
The headOption and head would absent from IndexedSeqOps and cause 2.13.2 compiled scalameta parser fail for 2.13.1

Fix scala library incompatibility between 2.13.2 and 2.13.1 

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/package.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/StarParameterSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/VarargParameterSuite.scala

Fixes #2006
One check is added in `trees` hierarchy to ensure structure is consistent and if anyone uses trees somewhere else this bad state will throw exception.
Let's say "duplicated check" is done in ScalametaParser to provide proper feedback for the user(same as compiler would generate).
(that's why 2 similar checks, I don't know have vision how to have only one check)
Also I added 1 test that should throw error for scala 2 but should be valid for scala 3, do we have a way to determine in test specific scala version?

Fix *-parameter check for method definition

---

.github/workflows/ci.yml
build.sbt
project/plugins.sbt
scalameta/parsers/js/src/main/scala/scala/meta/parsers/JSFacade.scala
semanticdb/semanticdb/semanticdb.proto
semanticdb/semanticdb/semanticidx.proto

Closes #2047
[Scala.js 0.6 support is dropped to avoid complexity of build and release process](https://github.com/scalameta/scalameta/pull/2021#discussion_r408742736).
Scala.js 0.6 users can still use existing versions of scalameta.

Add Scala.js 1.0 support (and Drop Scala.js 0.6 support)

---

README.md
build.sbt

Krzysztof already did some great work on the Scalameta parser and is currently leading the effort to add support for Dotty syntax.
It's my pleasure to welcome him to the team.

Welcome Krzysztof to the team!

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScaladocParser.scala
scalameta/testkit/src/test/scala/scala/meta/tests/contrib/ScaladocParserPropsSuite.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/Scaladoc.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/ScaladocParserSuite.scala

The existing `DocToken`/`ScaladocParser` pair is missing support for list blocks and has incomplete support for tags.
To avoid breaking any existing usage, propose creating a new pair of classes, to add the missing support. Also, as the code is already using a sophisticated parsing library, let's add more structure into the tokens.
Needed in order to address:
https://github.com/scalameta/scalafmt/issues/891
https://github.com/scalameta/scalafmt/issues/1387

internal.Scaladoc: another way to parse a scaladoc

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScaladocParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/ScaladocParserSuite.scala

To avoid potentially valid structure being parsed as `Unknown`.

Scaladoc: relax restrictions on text matching

---

scalameta/parsers/js/npm/package.json

Currently, the npm page of `scalameta-parsers` has no links to repository/homepage.
This PR adds them, so users can reach to repo/homepage.
Example:

Add repository/homepage so users can reach scalameta pages

---

project/plugins.sbt
tests/shared/src/test/scala/scala/meta/tests/parsers/VarargParameterSuite.scala

in newest munit `assertEquals` requires objects to be equal by '=='. This is not the case for tree structures. 
Assertion changed to only assert `.structure` and `.syntax`
Also update munit which superseedes this PR by scala-steward: https://github.com/scalameta/scalameta/pull/2055

Fix asserting trees equality and update sbt-munit 0.7.7

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScaladocParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/ScaladocParserSuite.scala

Otherwise, we get false positives.

Scaladoc: require space after list prefix

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScaladocParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/ScaladocParserSuite.scala

If one element is incorrectly parsed, the entire passage is returned as
rather than having it partially valid.

Scaladoc: relax parsing, to avoid unknown

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScaladocParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/Scaladoc.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/ScaladocParserSuite.scala

https://www.scala-lang.org/blog/2018/10/04/scaladoc-tables.html

Scaladoc: implement parsing of tables

---

semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/HijackReporter.scala
semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/ReporterOps.scala
semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/SemanticdbPlugin.scala

Keep a reference to the reporter we're overriding. Other compiler plugins (silencer compiler plugin) can change the reporter and we're not guaranteed that it will be a StoreReporter. We can end up in a situation where the reporter is replaced and the messages aren't passed to the underlying reporter or ignored.
---
We (@laughedelic and myself) discovered this issue when I tried to use the silencer plugin in combination with scalafix. Both compiler plugins swap out the reporter with there own but pass the messages to the underlying reporter.

keep a reference to the semanticdb reporter

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala

Found the issue while testing inside Metals. The code is a bit convoluted around the separate regions part, but in essence  the condition was wrong.
`sepRegions1.head != '}' || sepRegions1.head != '$'` will always be true, which was the issue.

Fix issue with a match expression in an if statement

---

scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/Scala213Suite.scala

Given and TypeLambdaArrow were interpreted as KW.
Enum was handled already ok. Applied the same rules to Given and TypeLambdaArrow as they were for enum.
Only Given and TypeLambdaArrow were introduced as new dotty KW in my dotty PR.
Fixes #2083

Fix given and TypeLambdaArrow being identifier in scala2

---

scalameta/dialects/shared/src/main/scala/scala/meta/Dialect.scala
scalameta/dialects/shared/src/main/scala/scala/meta/dialects/package.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala-2.12/scala/meta/tests/tokenizers/BaseTokenizerCoverageSuite.scala
tests/shared/src/test/scala-2.12/scala/meta/tests/tokenizers/TokenizerCoverageSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/Scala213Suite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala

Previously, if try was followed by `{` or `(`, the code assumed the
entire body is enclosed. This is an attempt to fix this.
Fixes #2031. Fixes #2009.

ScalametaParser: fix try of partial enclosed expr

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/LitSuite.scala

Fixes #2095
When we encounter token looking like 'unary operator' we always parse it this way.
But as in example in #2095 it can be also an ident(name of object/class etc). 
Instead of throwing exception when we cannot parse it as unary operator we can try and assume '-' is ident and parse it this way.

Fix object names as unary operators

---

scalameta/common/shared/src/main/scala/scala/meta/internal/prettyprinters/Enquote.scala
tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala

Previously, the pretty printer incorrectly escaped characters in
string literals like `Lit.String("xy\u001az")`. Now, we format
these characters with the correct unicode escapes.

Fix #2106 - properly escape non-letter non-ascii characters

---

semanticdb/integration/src/main/scala/example/Issue2116.scala
semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/TextDocumentOps.scala
tests/jvm/src/test/resources/example/Classes.scala
tests/jvm/src/test/resources/example/Issue2116.scala
tests/jvm/src/test/resources/metac-metacp.diff
tests/jvm/src/test/resources/metac.expect
tests/jvm/src/test/resources/metacp.expect

Fixes https://github.com/scalameta/scalameta/issues/2116
Looks like we are getting ThisType sometimes on class members, but I am no 100% sure where is that coming from or sure about the solution. IS it possible to better check if ThisType is not actually synthetic and actually exits in the code?

ThisType should only occur when actually in the code

---

project/plugins.sbt

Supersedes #2076
```
From gitter:
Nadav Samet @thesamet 17:08
@kpbochenek The shaded version should no longer be necessary.
Please update ScalaPB to 0.10.8 and sbt-protoc to 1.0.0-RC2
```
/cc @thesamet

ScalaPB compilerplugin 0.10.8

---

community-test/src/test/scala/CommunityDottySuite.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ControlSyntaxSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ExtensionMethodsSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/GivenUsingSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala

- bumping dotty hash in community tests
- handle `val fn = (using x: Int) => 1 + x`
- handle looking like old while yet with do block
- add tests for ? type `val x: List[?]` (implementation was already done)
-  add test for extension + using, this will require changing `Extension` as I did not include this initially, test ignored, will fix in next PR.

Anonymous method with using

---

community-test/src/test/scala/CommunityDottySuite.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/jvm/src/test/scala-2.12/scala/meta/tests/api/SurfaceSuite.scala
tests/jvm/src/test/scala-2.12/scala/meta/tests/trees/ReflectionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ControlSyntaxSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ExtensionMethodsSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/GivenUsingSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala

~~- add mdoc to community tests~~
- fix ExtensionGroup with 'using' parameters
- better handling new for expression control syntax
- support type '@unchecked'

Support Extension Group using parameters

---

community-test/src/test/scala/CommunityDottySuite.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/ScalametaTokenizer.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ControlSyntaxSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala

- fix handling comment after ColonEOL
- bump community-dotty to include 2 fixes
- handle `=>` in match/catch { } should not trigger Indentation.

Fix indent after arrow in braces

---

community-test/src/test/scala/CommunityDottySuite.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala
scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyToken.scala
scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/ScalametaTokenizer.scala
scalameta/tokens/shared/src/main/scala/scala/meta/tokens/Token.scala
scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/package.scala
tests/jvm/src/test/scala-2.12/scala/meta/tests/api/SurfaceSuite.scala
tests/jvm/src/test/scala-2.12/scala/meta/tests/trees/ReflectionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ControlSyntaxSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/EndMarkerSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/GivenUsingSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala

- try catch as parameter of method :)
- context functions (they are syntactic sugar for given/using that's why hidden under this flag)
ContextFunctions:
https://github.com/lampepfl/dotty/commit/576e535ac5314da253d2a0abb7887b1a02fd4ef9
https://dotty.epfl.ch/docs/reference/contextual/context-functions.html
Sooo unrewarding to implement this and only improve parsing dotty codebase with 1 more file ech

fix-new-catch-case-as-parameter

---

community-test/src/test/scala/CommunityDottySuite.scala
project/Mima.scala
scalameta/common/shared/src/main/scala/org/scalameta/adt/Reflection.scala
scalameta/common/shared/src/main/scala/scala/meta/internal/transversers/transformer.scala
scalameta/common/shared/src/main/scala/scala/meta/internal/trees/NamerMacros.scala
scalameta/common/shared/src/main/scala/scala/meta/internal/trees/ast.scala
scalameta/common/shared/src/main/scala/scala/meta/internal/trees/branch.scala
scalameta/common/shared/src/main/scala/scala/meta/internal/trees/metadata.scala
scalameta/common/shared/src/main/scala/scala/meta/internal/trees/root.scala
scalameta/dialects/shared/src/main/scala/scala/meta/Dialect.scala
scalameta/dialects/shared/src/main/scala/scala/meta/dialects/package.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala
tests/shared/src/test/scala/scala/meta/tests/transversers/TransformerSuite.scala

This adds an additional option to define new fields in existing ast classes, but still make them binary compatible with previous versions.

Add option for additional binary compatible fields and add derives

---

community-test/src/test/scala/CommunityDottySuite.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ControlSyntaxSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/GivenUsingSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala

- Fix condition checking in if for "." to continue `if (cond).rest then ...`
- Fix lambda with unnamed using `val lbda = (using _: Context) => ...`
- Fix catch case, new-style catch-case supports only expr: `catch case ex => singleExprOnly()`

Fix if continuation as dot and using lambda

---

community-test/src/test/scala/CommunityDottySuite.scala
project/Mima.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/ScalametaTokenizer.scala
scalameta/tokens/shared/src/main/scala/scala/meta/tokens/Token.scala
tests/jvm/src/test/scala-2.12/scala/meta/tests/api/SurfaceSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/SignificantIndentationSuite.scala

This removes colonEol token, since we can better determine it later while preparing tokens for parsing.
This might cause Mima errors, but will be neccessary for now.

Add additional logic to only add indent on correct colons

---

community-test/src/test/scala/CommunityDottySuite.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/GivenUsingSuite.scala

Based on https://github.com/lampepfl/dotty/pull/10089

Disallow `given as <ident>` syntax

---

.github/workflows/release.yml

@gabro It seems the release in Metals also failed. Let's see if this helps.

Update setup-gpg to v3

---

project/Mima.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/jvm/src/test/scala-2.12/scala/meta/tests/trees/ReflectionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/GivenUsingSuite.scala

Just updating this, since Type.Param is better used to statements like  `[A,B]` and I overdid it with Type.Param.

Use type in givens, which makes working on the tree easier

---

community-test/src/test/scala/CommunityDottySuite.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/EndMarkerSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/SignificantIndentationSuite.scala

This includes:
- issues after `end extension`
- nested possible colonEol
- new outdentation rule based on https://github.com/lampepfl/dotty/pull/10331
I also found a new issue with indentation here: https://github.com/lampepfl/dotty/issues/10372

Fix remaining issues with parsing Dotty

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ControlSyntaxSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/InlineSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/SignificantIndentationSuite.scala

After working a bit on scalafmt it seems that most problematic is the case with a single statement, which now is sometimes be treated as an indented block. So reformatting could sometimes cause a new block to be created even if there was none before.

Don't create block on indentation with a single statement

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/NewFunctionsSuite.scala

Not sure if this `type F0 = [T] => List[T] ?=> Option[T]` will be valid in Scala 3.0.0 but it compiles in 3.0.0-M1.
So here is the fix for that.

Fix PolyFunction with context param

---

.jvmopts
project/Mima.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/trees/ReflectionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ExportSuite.scala
tests/shared/src/test/scala/scala/meta/tests/prettyprinters/PublicSuite.scala

Previously, the `scala.meta.Export` tree had a `given: Boolean` field.
This goes against a design principle in the Scalameta AST, which tries
to represent as much as possible with syntax. There's no other AST node that
has a boolean field to distinguish between two cases. This commit
introduces a new `ExportGiven` class to represent `export given a.b`
syntax.
This is a binary breaking change so the next release should strictly
speaking be Scalameta v5. However, I think it's fair to change the
compatibility policy to state that Dotty-specific tree nodes are
experimental for time being and subject to breaking changes. This policy
buys us time to refine the Scala 3 AST nodes so that they are well
designed and consistent with the rest of the Scalameta AST nodes.
Normal Scalameta users should …

Introduce `ExportGiven`, remove `Export.given: Boolean`.

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/SoftKeywords.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/ParseSuite.scala

Based on https://github.com/scalameta/scalafmt/pull/2284#discussion_r538886558
This way they can be reused inside scalafmt.

Move soft keyword definitions outside the parser

---

project/Mima.scala
scalameta/dialects/shared/src/main/scala/scala/meta/Dialect.scala
scalameta/dialects/shared/src/main/scala/scala/meta/dialects/package.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala
scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyToken.scala
scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/ScalametaTokenizer.scala
scalameta/tokens/shared/src/main/scala/scala/meta/tokens/Token.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala
tests/jvm/src/test/scala/scala/meta/tests/tokens/ReflectionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MacroSuite.scala

In order to figure out if something is a spliced or quoted variable we need to know what is the current context. I haven't found a better way to actually figure out if something is an identifier or spliced/quoted identifier. Anything else would require us to add an additional parameter to all of the methods and I figured that since we are already in a mutable context this is a much easier solution.
We could possibly remove `MacroSplicedIdent`, since we can just check if identifier starts with $ inside the context, but it does work together with `MacroQuotedIdent` - kind of looks symetrical. But it does mean we have to handle `MacroSplicedIdent` specially.
Fix #2191

Add variable to track if we are inside quotes/splices 

---

scalameta/common/shared/src/main/scala-2.11/org/scalameta/internal/MacroCompat.scala
scalameta/common/shared/src/main/scala-2.12/org/scalameta/internal/MacroCompat.scala
scalameta/common/shared/src/main/scala-2.13/org/scalameta/internal/MacroCompat.scala
scalameta/common/shared/src/main/scala/scala/meta/internal/trees/ast.scala

`productElementName` was introduced in 2.13 and some libraries might use it to print names for field. When for example using pprint, previously we would get:
```scala
Source(
= List(
Defn.Def( = List(),  = Term.Name( = "b"),  = List(),  = List(),  = None,  = Lit.Int( = 1))
)
)
```
now we get
```
Source(
stats = List(
Defn.Def(
mods = List(),
name = Term.Name(value = "b"),
tparams = List(),
paramss = List(),
decltpe = None,
body = Lit.Int(value = 1)
)
)
)
```

Fix product names in macros for 2.13

---

scalameta/dialects/shared/src/main/scala/scala/meta/Dialect.scala
scalameta/dialects/shared/src/main/scala/scala/meta/dialects/package.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/trees/ReflectionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/NewFunctionsSuite.scala
tests/shared/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala

Dependent function types are a new features in Scala 3, which is explained [here](https://dotty.epfl.ch/docs/reference/new-types/dependent-function-types.html). While working on this I noticed that MethodType is something that is no longer in any dialect and is not really used at all. Because of that and the fact that it caused some issues parsing dependent function types I decided to get rid of it and deprecate all dialect methods.

Add support for dependent function types

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/ParentChecks.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/EnumSuite.scala

Previously, parser would allow enum cases to be created anywhere, which is not allowed in the language itself. Now, we make sure that enums are the only ones that can own enum cases. 
This has added a number of parameters to a bunch of methods, but I think it's the cleanest solution that we can have.

Make sure enum cases can only be created within an enum

---

scalameta/dialects/shared/src/main/scala/scala/meta/Dialect.scala
scalameta/dialects/shared/src/main/scala/scala/meta/dialects/package.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/SoftKeywords.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/GivenUsingSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala

Scala 3 no longer uses `as` in given declartions and instead uses a colon. Because of that and the limited need for
`as` it was also removed from patterns where it was a replacements for `@`
This still doesn't fix the givens with indentation that use the `with` keyword. The syntax is still fluctuating there, so we might need to work on it later.

Remove `as` soft keyword in patterns and givens

---

project/Mima.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/SoftKeywords.scala
scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala
scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyToken.scala
scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/ScalametaTokenizer.scala
scalameta/tokens/shared/src/main/scala/scala/meta/tokens/Api.scala
scalameta/tokens/shared/src/main/scala/scala/meta/tokens/Token.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/EndMarkerSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ExtensionMethodsSuite.scala

Previously, when discussing https://github.com/lampepfl/dotty/issues/10076 it was mentioned that `extension` would become
a keyword, but turns out it will not be. I kind of jumped the gun here and we should not have chanegd it until it was in
the compiler code.

Change extension to be a soft keyword again

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala

Previously, type case would include the opening `{` due to the code being copied from `caseClause` method. Now it only included the exact position.
I also added more tests to see if the positions are incorrect anywhere else.

Fix TypeCase positions to not include a previous character

---

project/Mima.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/InlineSuite.scala
tests/shared/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala

Scala 3 introduces the concept of inline match that can be created within an inline method:
```scala
inline def g(x: Any): Any = inline x match {
case x: String => (x, x) // Tuple2[String, String](x, x)
case x: Double => x
}
```
This needs to be parse accordingly and also makes it imporrisble to use `inline` as identifiers in Apply trees.

Add inline match available in Scala 3

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MatchTypeSuite.scala

```
An indentation region can start after one of the following tokens:
=  =>  ?=>  <-  catch  do  else  finally  for
if  match  return  then  throw  try  while  yield
```
Previously, we forgot about types when checking this rule.

Type aliases and function types should take into account indentation

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ExtensionMethodsSuite.scala

This is done the same way when working with templates and method definitions.

Allow extension to declare using and braces in another line

---

scalameta/common/shared/src/main/scala/scala/meta/internal/trees/NamerMacros.scala
scalameta/common/shared/src/main/scala/scala/meta/internal/trees/ast.scala
scalameta/common/shared/src/main/scala/scala/meta/internal/trees/branch.scala

Currently, the code hardcodes exactly three methods (`value`, `name` and `tpe`) which can be declared in a `@branch` trait.
This is an attempt to support other methods as well, although it still is not flexible enough to support methods in a branch which is a parent of another branch.
Required for #2207 to work.

Trees: Support branch methods

---

project/Mima.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/GivenUsingSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/SignificantIndentationSuite.scala

In the previous PR that touched the changes in givens I forgot to include `with`, which I am fixing in this PR. I also removed any test cases that were ignored, but don't have an easy way for the parser to show an error (also Dotty parser mostly works in those case also).

Fix givens to accept `with` keyword for refinements

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/trees/ReflectionSuite.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/GivenUsingSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/SignificantIndentationSuite.scala

All other tree nodes like val, var or def have a separate Tree node when they are declared abstract. To keep in line with that I added Decl.Given to handle abstract given declarations
Abstract givens cannot be annonymous or have multiple types declared using `with`, so I added checks for that.

Add Decl.Given for abstract givens

---

project/Mima.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/trees/ReflectionSuite.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ExportSuite.scala

Previously, given exports would be written like this:
```scala
export given A
```
now it got changed to be similar to imports:
```scala
export A.given
```

Fix given exports to adhere to current spec

---

semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/ParseOps.scala
semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/TextDocumentOps.scala

Required for metals in order to get semantic documents for sbt files and worksheets

semanticdb: `toTextDocument` add Dialect parameter

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala

It seems that positions are sometimes different depending on whether we are in a top level tree or not. I adjusted the test for givens and also added one for exports.

[Scala 3] Fix givens to actually contain the given keyword 

---

scalameta/common/shared/src/main/scala/org/scalameta/adt/Reflection.scala
scalameta/common/shared/src/main/scala/scala/meta/internal/transversers/transformer.scala
scalameta/common/shared/src/main/scala/scala/meta/internal/trees/TyperMacros.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/ParseSuite.scala
tests/shared/src/test/scala/scala/meta/tests/trees/ChildrenSuite.scala

Binary compat fields were added to allow for the older AST nodes to be forward binary compatible.
Previously, when invoking `children` method on trees that contained binaryCompat fields, those fields would not exist in the resulting list. Now, they are contained and can be used to traverse the tree.
It's important to note that traverse will still not working with those additional fields, but in most places (for example scalafmt) the `children` method is being used. We can try to fix it in the future if need arises.
This came up when working on `derives` in scalafmt. @kitbellew could you take a look? You are probably the only other person that recently dealt with thise macros :sweat_smile:

Make sure children contains binary compat fields

---

scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/LitSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/UnclosedTokenSuite.scala

I believe this fixes issue #2228 where `'\u005c'` would cause an unclosed character literal error.

Fix for \u005c causing an unclosed quote error

---

scalameta/dialects/shared/src/main/scala/scala/meta/Dialect.scala
scalameta/dialects/shared/src/main/scala/scala/meta/dialects/package.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/TypeSuite.scala

Fixes two issues:
- `case case` statement that cause InvariantException now shows a nice error
- `()` literal type is no longer supported in any dialect (checked with 2.13.4) and added a ncie message instead of unreachable.

Fix syntax errors

---

scalameta/dialects/shared/src/main/scala/scala/meta/Dialect.scala
scalameta/dialects/shared/src/main/scala/scala/meta/dialects/package.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/trees/ReflectionSuite.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala

Starting with Scala 3 RC1 it's now possible to use a single * for vararg splices:
https://dotty.epfl.ch/docs/reference/changed-features/vararg-splices.html
To support this I added a new Pat.Repeated, since the prevoius Pat.Wildcard did not fit with how it's currently represented.

[Scala 3] Add support for single start vararg splices

---

community-test/src/test/scala/CommunityDottySuite.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/jvm/src/test/scala/scala/meta/tests/parsers/BootstrapSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ControlSyntaxSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/EnumSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ExtensionMethodsSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/SignificantIndentationSuite.scala

This PR is mostly about rework. In addition, it fixes `multiline-extension` parsing.
The logic from `loop` method that removes whitespaces and produces `Intent`/`Outdent` is moved on `TokenIterator` level.
It observes tokens on demand that adds an ability to put indentation on the parser level using `observeIndented` method.
Dotty parser uses a similar approach.
So, instead of trying to predict __if this `LF` that comes after `:` should add Indent or not__ now it's handled at the moment of parsing template. The same for extension methods.

Parser: rework significant indentation processing.

---

.github/workflows/ci.yml
community-test/src/test/scala/CommunityDottySuite.scala
scalameta/dialects/shared/src/main/scala/scala/meta/Dialect.scala
scalameta/dialects/shared/src/main/scala/scala/meta/dialects/package.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/package.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ControlSyntaxSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/GivenUsingSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/SignificantIndentationSuite.scala

This also fixes issues:
- `type T` being the only thing in an indented block
- given patterns work properly with functions
- typed pattern is not always allowed at the end, which is a change from Scala 2
- no longer allow for `if cond <indentation>`

[Scala 3] Fix minor issues and make dotty community test run on CI

---

build.sbt
project/plugins.sbt

Succeeds https://github.com/scalameta/scalameta/pull/2227 and https://github.com/scalameta/scalameta/pull/2223

Update ScalaJS to `1.4.0` along with some of the libraries

---

community-test/src/test/scala/CommunityDottySuite.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/CharArrayReader.scala
tests/jvm/src/test/resources/unicode.txt
tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/SignificantIndentationSuite.scala

This PR also fixes any related issues that were still not working in case dotty source code, which includes:
- indentation start in `{ a => ` block
- unicode escapes like `f"\u$oct%04x"`

[Scala 3] Allow to have some of the keywords on the same indentation level as the preceeding block

---

tests/jvm/src/test/scala/scala/meta/tests/semanticdb/Issue2024Suite.scala

Close https://github.com/scalameta/scalameta/issues/2024
Since the fix for the issue https://github.com/scala/scala/pull/9426 had been released in scala 2.13.5 (and going to release in 2.12.15), I'd like to close the issue by adding a test that ensures the symbol occurrences are correctly emitted. :tada:

Add test for #2024

---

scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala

Originally reported as https://github.com/scalacenter/scalafix/issues/1337.
Fix regression introduced in https://github.com/scalameta/scalameta/pull/2239.

pretty printer: backquote importees when needed

---

build.sbt
scalameta/contrib/shared/src/main/scala/scala/meta/contrib/DocToken.scala
scalameta/contrib/shared/src/main/scala/scala/meta/contrib/ScaladocParser.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScaladocParser.scala
scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala
scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/XmlParser.scala

This PR updates the fork of fastparse to use the newest 2.3.1 version, which we also backpublished for 2.11. This way we will be able to support:
- JVM 2.11, 2.12, 2.13
- JS 2.12, 2.13
- Native 2.12, 2.13 (in the next PR)

Update fastparse to 2.3.1

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/GivenUsingSuite.scala

Complex types such as `A & B` need to be wrapped in parenthesis when used as a type for given alias. Previously, we would try to parse parens as using parameters, which is not always the case. Now we also check for the `using` keyword, which allows us to parse complex types in given aliases type declarations.

[Scala 3] Fix given alias with complex types

---

build.sbt

Starting back with 0.6.7, geny is again being published for 2.11 Scala version.
Succeeds https://github.com/scalameta/scalameta/pull/2268

Update geny to 0.6.7

---

community-test/src/test/scala/CommunityDottySuite.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/SignificantIndentationSuite.scala

Previously, return could not start an indentation, but starting with https://github.com/lampepfl/dotty/pull/11752 it can. This fixes scalameta to parse accordingly.
Additionally, this change also created some issues with empty `return` statements in pattern matches. We would incorrectly think that the next statement is indented, because we never saved case block indentation. I added a new CaseRegion in this PR, so that we can remember the indentation. This is only added in `match` with braces as indented match clauses work correctly here.

[Scala 3] Allow return statement to contain indented block

---

docs/semanticdb/specification.md
semanticdb/semanticdb3/semanticdb3.md

Sync specification docs with actual [definition](https://github.com/scalameta/scalameta/blob/master/semanticdb/semanticdb/semanticdb.proto#L215-L216).

ClassSignature specification had swapped self and declaration fields

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/EndMarkerSuite.scala

There is some logic around optional braces that relies on the match keyword, however it should not take into account `end match`. This is now fixed.

Fix issues with end match

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala

#2279  was caused by the wrong `Indent`/`Outdent` tokens positions.
They have to point at `LF` that triggered their creation.
To cleanup tree syntax from whitespaces now `atPos` performs a kind of `trim` operation.

[Scala3] Fix issues with wrong `Indent`/`Outdent` positions.

---

scalameta/contrib/shared/src/main/scala/scala/meta/contrib/ScaladocParser.scala
tests/shared/src/test/scala/scala/meta/tests/contrib/ScaladocParserSuite.scala

Fixes https://github.com/scalameta/scalameta/issues/2283
This was working in the other `internal.parser.ScaladocParser`. I guess we can drop this one if we ever do a 5.0 release.

Fix parsing Param tags

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala

I forgot about this method in #2282.

[Scala3] Fix wrong position produced by `Outdent` in `observeOutdented`

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/SignificantIndentationSuite.scala

Fixes https://github.com/scalameta/scalameta/issues/2289

Allow indented partial function values

---

scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala

Dotty allows type to almost always be defined
More info about the syntax is here https://dotty.epfl.ch/docs/internals/syntax.html#expressions
Connected to https://github.com/scalameta/scalafmt/issues/2424

Remove most checks for Pat.Type

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/SignificantIndentationSuite.scala

We missed it previously and that seems to be the case according to https://dotty.epfl.ch/docs/reference/other-new-features/indentation.html#optional-braces

Allow indented block after `<-` and `?=>`

---

community-test/src/test/scala/CommunityDottySuite.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/GivenUsingSuite.scala

The issue popped up when parsing https://github.com/kubukoz/slang/tree/165fc48c1a3bfff4a0349378855ca89c6d90873f
Connected to https://github.com/scalameta/scalafmt/issues/2216#issuecomment-823910262
We are first trying to parse non-anonymous given, which
- requires `:` for type, if none is found it means it's anonymous
- might fail in cases that anonymous type looks like type param
`given Conversion[AppliedName, Expr.Apply[Id]] = ???`
This will fail because type params cannot have `.`

Fix issues with complex types in anonymous given

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/EnumSuite.scala

In the following example: `enum A { self => ...`  right arrow should start `RegionIndentedEnum`  instead of `RegionIndented` to not to break `cases` parsing.

[Scala3] Fix selftype parsing for enum.

---

docs/trees/guide.md

Ammonite itself is using scalameta, which causes issue when users want to use it to experiment with the parser.
I propose we remove that section altogether as it seem we will never be able to make it work properly.
Fixes https://github.com/scalameta/scalameta/issues/2294

Update reference to Ammonite in guide.md

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala

It addresses this problem - https://github.com/scalameta/scalafmt/pull/2447#issuecomment-824851176.
In previous similar fixes about position and indentation tokens, I forgot about these cases :disappointed: 
I double-checked all places where these artificial tokens are created and hope there will be no more such bugs.

[Scala3] Fix Oudent position before `}`, `)`, `,`

---

scalameta/common/shared/src/main/scala/org/scalameta/explore/Macros.scala
scalameta/common/shared/src/main/scala/org/scalameta/explore/package.scala
scalameta/dialects/shared/src/main/scala/scala/meta/Dialect.scala
scalameta/dialects/shared/src/main/scala/scala/meta/dialects/package.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala

It was also needed to fix the macro used in tests, since it started generating method that was too large, but we haven't actually used most of that, so no test was harmed. This should also be covered by MiMa.

Drop procedure syntax for the Scala 3 dialect

---

scalameta/dialects/shared/src/main/scala/scala/meta/Dialect.scala
scalameta/dialects/shared/src/main/scala/scala/meta/dialects/package.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala

This already no longer works with Scala 3: https://dotty.epfl.ch/docs/reference/dropped-features/do-while.html

[Scala 3] Deprecate do while syntax

---

project/build.properties
project/plugins.sbt

Mima needed to be updated due to a migration from 2.12.12 to 2.12.13 in sbt.
Succeeds https://github.com/scalameta/scalameta/pull/2309

Update sbt to 1.5.1 and Mima plugin to 0.8.1

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala

Connected to https://github.com/scalameta/scalafmt/issues/2480

[Scala 3] Fix indented partial functions after `=>`

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/tokenizers/TokensPositionSuite.scala

Addresses [@kitbellew comment](https://github.com/scalameta/scalameta/pull/2319#discussion_r623135604).
There were more occurrences of improper `Name.Anonymous` creation.

Fix position for Name.Anonymous. 

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/quasiquotes/shared/src/main/scala/scala/meta/internal/quasiquotes/ConversionMacros.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/tokenizers/TokensPositionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/quasiquotes/ErrorSuite.scala
tests/shared/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala

We already include derive and it makes sense to keep it there.
Fixes https://github.com/scalameta/scalameta/issues/2326

Include `extends` keyword in Template

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/StructureSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala

Previously, we would always remove the outer most {} and not report a Block even in:
```
List("").map{
s => {
s + s
}
}
```

Use Term.Block in functions when {} are added explicitely.

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/tokenizers/TokensPositionSuite.scala

In case if there is an underlying token `this` or `_` it should point on it.
Also fixed `using` mod position in lambdas

Fix Name.Anonymous positions once again. 

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScaladocParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/Scaladoc.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/ScaladocParserSuite.scala

Implements https://spec.commonmark.org/0.29/#fenced-code-blocks. Supersedes #2332.

ScaladocParser: add support for fenced code blocks

---

scalameta/parsers/js/npm/package.json
scalameta/parsers/js/src/main/scala/scala/meta/parsers/JSFacade.scala
tests/js/src/test/scala/scala/meta/tests/parsers/JSFacadeSuite.scala

Minor tweaks to publish a new version of Scalameta parsers to npm (it's already published: https://www.npmjs.com/package/scalameta-parsers)

Update  parsers's JSFacade and publishing script

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/SignificantIndentationSuite.scala
tests/shared/src/test/scala/scala/meta/tests/trees/InvariantSuite.scala

It turns out we are still missing some syntax changes for optional braces. We can now also define packages with body using `:`, which is similar to previously available:
```
package a {
object A
}
```
This commit fixes that.

Allow braceless package definitions

---

scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MacroSuite.scala

Connected to https://github.com/scalameta/scalafmt/issues/2512

Allow QuotedMacroType to be used in pattern matches

---

.github/workflows/ci.yml
bin/test-release.sh
project/Versions.scala
project/plugins.sbt
scalameta/dialects/shared/src/main/scala/scala/meta/Dialect.scala
scalameta/dialects/shared/src/main/scala/scala/meta/dialects/package.scala
semanticdb/scalac/library/src/main/scala-2.13.6/scala/meta/internal/semanticdb/scalac/SemanticdbReporter.scala
semanticdb/scalac/library/src/main/scala-2.13.6/scala/meta/internal/semanticdb/scalac/VersionCompilerOps.scala
semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/LanguageOps.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala
tests/jvm/src/test/scala/scala/meta/tests/semanticdb/InteractiveSuite.scala
tests/jvm/src/test/scala/scala/meta/tests/semanticdb/Issue2024Suite.scala
tests/jvm/src/test/scala/scala/meta/tests/semanticdb/ScalaVersion.scala
tests/jvm/src/test/scala/scala/meta/tests/semanticdb/Source3Suite.scala
tests/shared/src/test/scala/scala/meta/tests/prettyprinters/PublicSuite.scala

Also fixes https://github.com/scalameta/scalameta/issues/2323 by adding an additional dialect for use with source:3 option.
I don't think we can do much more on Scalameta side, since when parsing we don't have access to scalac options.

Add support for Scala 2.13.6

---

community-test/src/test/scala/CommunityDottySuite.scala
scalameta/dialects/shared/src/main/scala/scala/meta/dialects/package.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MacroSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala

- xml literals can be parsed by Scala 3 when scala-xml is on the
classpath, just like in Scala 2.
- Symbol literals can still be used with
`import scala.language.deprecated.symbolLiterals`

Enable xml and symbol literals in the Scala3 dialect

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScaladocParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/Scaladoc.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/ScaladocParserSuite.scala

Scaladoc: fix syntax for links with anchor text

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala

Discovered in https://github.com/twitter/finagle/blob/5a926d0a486d65d6571731de22932029a9a91e38/finagle-thrift/src/test/scala/com/twitter/finagle/thrift/exp/partitioning/PartitionAwareClientEndtoEndTest.scala#L367

Allow type acription on partial functions

---

scalameta/dialects/shared/src/main/scala/scala/meta/Dialect.scala
scalameta/dialects/shared/src/main/scala/scala/meta/dialects/package.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/TypeSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala

Allow `-_` and `+_` as type names for `-Xsource3` flag

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/SignificantIndentationSuite.scala

Related to https://github.com/lampepfl/dotty/issues/12554 and https://github.com/scalameta/scalafmt/issues/2522
It is now possible to have the next apply in curried functions to start in the next line if there is an indentation:
```scala
def f(s: String)(t: String) = s"$t: $s"
def g =
f("Foo")
("Bar")
```

Allow next apply after newline and indentation

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/DefnSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/ParseSuite.scala

Previosly, we would not parser correctly when braces would appear after function arrow and were not actually the function body. Now, we make sure to treat that situation differently so that the braces are not accepted greedily.

Fix issue with braces after function arrow

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/SignificantIndentationSuite.scala

Fixes https://github.com/scalameta/scalameta/issues/2376

Add support for indented contructor parameter lists

---

build.sbt
scalameta/testkit/src/main/scala/scala/meta/testkit/Corpus.scala
tests/jvm/src/test/scala-2.12/scala/meta/tests/semanticdb/ExpectSuite.scala

I started looking into this in order to start running Scalafmt tests on Native, but it seems I can instead just copy the small class that is needed for the tests. However, I think it's an improvement to remove two libraries here.

Remove not needed libraries

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala

Originally was reported here - https://github.com/scalameta/metals/issues/2874

[Scala3] Allow context bounds in trait type parameters

---

build.sbt

This fixes the release, since scalameta is not released for Native or JS on 2.11.

Don't publish testkit JS and Native for 2.11

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/EndMarkerSuite.scala

[Scala3] Allow empty template with `:` + end marker for object/class/trait

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/InlineSuite.scala

In the previous PR, I haven't added all possible cases, which inline can be followed by with a match. I went through all ExprIntro tokens and checked each one, so we should be good now. We could use `ExprIntro` classifier in theory, but it seems around half of the tokens defined there would be invalid after inline.
This issue came up when I was looking through the Dotty test cases and it seems we should try to parse as many as possible there, however it seems we do have some bugs still and I don't want to fix it all in one PR.

[Scala 3] Add the rest of possible inline matched expressions

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/SignificantIndentationSuite.scala

It's another one that popped up within the dotty tests.

[Scala 3] Fix issues with mixed indented and braceless packages

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/GivenUsingSuite.scala

Found this case by running community tests against [shapeless-3](https://github.com/typelevel/shapeless-3/blob/main/modules/deriving/src/test/scala/shapeless3/deriving/type-classes.scala#L225)

[Scala3] Fix `given ... with` + `Indent` + `import`/`export`

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MacroSuite.scala

Previously they were recognized as template blocks, which is not correct and breaks for example in case of lambdas.

[Scala 3] Recognize macro stats as block stats

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ControlSyntaxSuite.scala

The same as with match expressions

[Scala 3] Allow catch-case expressions without indentation

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ControlSyntaxSuite.scala

This follows:
```
An <outdent> is finally inserted in front of a comma that follows a statement sequence starting with an <indent> if the indented region is itself enclosed in parentheses
```
from https://dotty.epfl.ch/docs/reference/other-new-features/indentation.html

[Scala 3] Emit outdent before commas in arg position

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/InlineSuite.scala

Previously, we would only check for Ident, which is not enough for Scala 3.
Causes https://github.com/scalameta/scalafmt/issues/2640

[Scala 3] Recognize implicit closures only if next token is not a SoftModifier

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/SignificantIndentationSuite.scala

Indentation calculation rules:
- for single-line comment, spaces between newline and the start of comment
```scala
object Foo:
/* comment */ def foo: Int = ??? // <- indent = 3
- for multiline, spaces between newline and firts non-whitespace character
```scala
object Foo: /* multi
line
comment */ def foo: Int = ??? // <- indent = 3
```
Fixes #2424

[Scala3] Significant indentation - handle comments properly

---

README.md

I don't think that there is need for a replacement as Github anyway shows checks status for the last commit

README - fix build status badge

---

docs/semanticdb/specification.md
semanticdb/metap/src/main/scala/scala/meta/internal/metap/SymbolInformationPrinter.scala
semanticdb/semanticdb/semanticdb.proto
semanticdb/semanticdb/src/main/scala/scala/meta/internal/semanticdb/package.scala

This PR adds the following new modifiers for Scala3 to SemanticDB specification.
- Given
- https://docs.scala-lang.org/scala3/reference/contextual/givens.html
- for `given x: Int`, `given Int`, `using ctx: Context` and `using Context`
- Inline
- https://docs.scala-lang.org/scala3/reference/metaprogramming/inline.html
- Open
- https://docs.scala-lang.org/scala3/reference/other-new-features/open-classes.html
- Transparent
- https://docs.scala-lang.org/scala3/reference/other-new-features/transparent-traits.html
- Infix
- https://docs.scala-lang.org/scala3/reference/changed-features/operators.html
- Opaque
- https://docs.scala-lang.org/scala3/reference/other-new-features/opaques.html
FYI here's the generated code from this new SemanticDB schema …

Support new Scala3 modifiers

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScaladocParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/ScaladocParserSuite.scala

Don't consume other elements (tags, code blocks, etc.) if description is expected but in reality missing.
Fixes #2444.

Scaladoc: treat tag description as optional

---

scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala

Fixes #2447
Please take a good look at if this is not breaking anything 🙏.
`{ case x => Y => () }` parses differently than `{ case x @ y => () }`. I'm assuming this is on purpose and for a very good reason.
This PR changes the `thisLocationAlsoAcceptsPatVars` to return true for a `Pat.Bind`. I'm _assuming_ this is correct, as in a pattern match a `Pat.Var` can also take the place of a `Pat.Bind` (like in `{ case x => () }`).
EDIT: I just noticed that the [documentation](https://scalameta.org/docs/trees/quasiquotes.html#patterns-metapat-and-cases-metacase) mentions a `Pat.Bind` always consisting of two `Pat`'s. Is this correct, and does it mean that `x @ Y` should be parsed differently? (now it is `Pat.Bind(Pat.Var(Term.Name("x")), Term.Name("Y")))`)

Fix UnreachableError when printing a pattern match bind to a case object

---

CONTRIBUTING.md
docs/semanticdb/specification.md

- Document how to run the website locally
- https://github.com/scalameta/scalameta/commit/426c3dcf33cf445a2ce2c5183f7dbb2eecfb4fc0
- Realized there's no documentation on how to run the website locally, and I added the docs for it (basically copied from https://scalameta.org/metals/docs/contributors/updating-website)
- Remove redundant column from properties table
- Sorry, I introduced a redundant column to the doc before 😅

Document how to run website locally and refine document

---

scalameta/parsers/js/src/main/scala/scala/meta/parsers/JSFacade.scala

This causes linking errors in a Scala 3 / Scala.js 1 project
> Invalid top level export for name 'default' in class scala.meta.parsers.JSFacade$ when emitting a Script (NoModule) because it is not a valid JavaScript identifier (did you want to emit a module instead?)
The default export was also never used in practice, and it's better to access the single exported elements instead.

Remove invalid "default" JSExportTopLevel

---

scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala
tests/shared/src/test/scala/scala/meta/tests/tokenizers/TokenizerSuite.scala

Fixes #2467.
Aligned with [implementation in compiler](https://github.com/lampepfl/dotty/blob/adefa482667f8a3bfed9951c522677b2418d9610/compiler/src/dotty/tools/dotc/parsing/Scanners.scala#L1141-L1148)

Do not escape symbols in multiline string interpolation

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScaladocParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/ScaladocParserSuite.scala

Link might have some symbols at the end and we need to consume in as punc.
Otherwise it parses as separate `Word` and scalafmt writes is with an
additional space.
Example:
```scala
// before
"[Link]'s" -> Seq(Link("Link"), Word("'s"))
//after
"[Link]'s" -> Seq("Link", Seq.empty, "'s")
```
Should fix [this sample](https://github.com/scalameta/scalameta/pull/2468#discussion_r703208311)

ScaladocParser - minor fix for linkParser

---

.jvmopts

- It breaks metals quietly on startup
- Breaks SBT loudly

Remove option that breaks Metals&SBT on JDK 17

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/EnumSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/SignificantIndentationSuite.scala

Fixes https://github.com/scalameta/scalameta/issues/2505
PReviously, we would try to undo the indentation, but isntead we can just not introduce indentation on `=>` inside enums.

Don't allow indentation on `=>` in enums

---

scalameta/testkit/jvm/src/main/scala/scala/meta/testkit/Corpus.scala

I think it would be a challenge to fix #2509  so it's easier to ignore this file in test.

Testkit - ignore KafkaConfig file as it can't be transformed in EqualProps test

---

semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/RemoveOrphanSemanticdbFiles.scala

We had a failing test case in mdoc with this stack trace
```
java.nio.file.NoSuchFileException: /home/runner/work/mdoc/mdoc/tests/unit/target/scala-2.12/meta/META-INF/semanticdb/hello.sc.semanticdb
at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:249)
at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
at java.base/java.nio.file.Files.delete(Files.java:1152)
at scala.meta.internal.semanticdb.scalac.RemoveOrphanSemanticdbFiles$$anon$1.visitFile(RemoveOrphanSemanticdb …
```

Use Files.deleteIfExists

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/SignificantIndentationSuite.scala

Fixes https://github.com/scalameta/scalameta/issues/2529
Ideally, we would make the invariant messages have an additional message parameter so that this never happens again, but this is more involved.

Show a clear message when using secondary constructors in a wrong place

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScaladocParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/ScaladocParserSuite.scala

Test borrowed from #2489, but the parser behaviour is intentionally unchanged.

ScaladocParser: in listBlockParser, explain indent

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScaladocParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/ScaladocParserSuite.scala

Since we have removed all trailing space in the scaladoc, remove all references to `hspaces0` before `nl`. Also, remove redundant parsers.

ScaladocParser: simplify, remove unnecessary parts

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScaladocParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/Scaladoc.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/ScaladocParserSuite.scala

For now, that does not include markdown as that requires extra indent. Minor modification based on #2489, @dos65 did the bulk of the word.

ScaladocParser: allow other list-embedded elements

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScaladocParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/Scaladoc.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/ScaladocParserSuite.scala

Let's handle cases where label is expected but description is not, by reading in the entire tag line as label. This adds required handling to @usecase which must be formatted all on one line.

ScaladocParser: handle `@usecase` as special case

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScaladocParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/ScaladocParserSuite.scala

The existing one was getting confused by a "-" list following the table.

ScaladocParser: fix check for table delim line

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala

Fixes https://github.com/scalameta/scalameta/issues/2531

Show correct error when secondary constructor has no parenthesis

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/SignificantIndentationSuite.scala

Fixes https://github.com/scalameta/scalameta/issues/2546
I don't think there is a way to make it simpler yet :thinking:

Allow first statement inside for to be on the same line as the keyword

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/trees/ReflectionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MacroSuite.scala

Discussion [here](https://contributors.scala-lang.org/t/bind-in-splices-in-quoted-patterns/5533) and Dotty PR [here](https://github.com/lampepfl/dotty/pull/14277). Previously, splices inside quoted patterns (like the `...` in `case '{foo(${...})`) were parsed as blocks instead of patterns, even though the typer treats such splices as patterns. This means that arbitrary blocks were syntactically permitted, even though they would never compile, and some patterns (like those containing bindings like `${y@...}` were not syntactically permitted, even though the typer would accept them. 
This requires a change in the API to add a Term than can wrap a spliced pattern. Let me know if there's anything better I can do here.

Properly parse patterns in splices inside quoted patterns

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala

Unindented tests were failing parsing before this fix.

ScalametaParser: fix bug, `match` allows 0 indent

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/tokenizers/TokensPositionSuite.scala

Previously, we would outdent immediately after a non-trivial token while ignoring any trailing comments which followed.
Fixes #2516.

ScalametaParser: outdent after indented comments

---

bin/test-release.sh
community-test/src/test/scala/CommunityDottySuite.scala
scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala
scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/ScalametaTokenizer.scala
tests/shared/src/test/scala/scala/meta/tests/tokenizers/TokenizerSuite.scala

This doesn't work in the Scala 2 parser, but it feels like a bug, so should be safe to fix in the Scalameta parser

Allow _IDENT in string interpolation

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/ParseSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/ToplevelTermSuite.scala

Addresses https://github.com/scalameta/scalameta/issues/1940. A little more complicated than I thought. Comments welcome. I'm not sure if I put the test in the right place.

ScalametaParser: Make `allowToplevelTerms` accept package declarations

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/ModSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala

Before this PR, parsing ```implicit @foo def foo(): Int``` would stack overflow. This is because `tmplDef` is happy to accept modifiers, even though in all cases it's been used, modifiers have already been parsed. This seems to only be a problem for dotty, but I added a test for both anyways.

ScalametaParser: Avoid stack overflow when annotation comes after modifier

---

tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala

@KacperFKorban  This seems to work correctly in the current Scalameta version, maybe it's just using an older version? Or this is actually a scastie issue.
closes https://github.com/scalameta/scalameta/issues/2567

Add test case for #2567

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala

`Tree.pos` gives us the position in the file, while `atPos` needs to figure out the token index, so we can't just use start and end from Position. Instead we can jsut copy the origin of the original Tree.
The implicit conversions from Int are a bit at fault here, but when I tried to touch them everything blew up, so I'd rather escape with my life.
Fixes https://github.com/scalameta/scalameta/issues/2567

Fix issues with using atPos with tree position

---

.github/workflows/release.yml

This change is needed to allow Metals automatically catch new
scala2-compiler releases avoiding the full release process.
More details: scalameta/metals#3281

[Actions] Release semanticdb-plugin for new Scala2 version

---

scalameta/inputs/shared/src/main/scala/scala/meta/inputs/Api.scala
scalameta/inputs/shared/src/main/scala/scala/meta/inputs/Input.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/parsers/shared/src/main/scala/scala/meta/parsers/Parse.scala
scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/ScalametaTokenizer.scala
scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/trees/ReflectionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/ParseSuite.scala
tests/shared/src/test/scala/scala/meta/tests/prettyprinters/PublicSuite.scala
tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala

Adds a new MultiSource tree, and a new Input.Ammonite wrapper which is used as an indication that multi-source tokenization is needed.
Fixes #2155.

ScalametaParser: implement ammonite script parser

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala

No need to use recursion, no need to rebuild the list of arguments as they are simply checked for existence of Term.Repeated.

ScalametaParser: simplify argumentExprOrPrefixExpr

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala

If we are calling a partial function on an argument, it will throw an exception unless it is defined for that argument.
Therefore, there's no need for the Ellipsis check as it will result in a failure anyway; let's issue a proper syntax error instead.

ScalametaParser: remove broken branch in statSeq

---

scalameta/common/shared/src/main/scala/org/scalameta/adt/Adt.scala
scalameta/common/shared/src/main/scala/scala/meta/internal/tokens/TokenNamerMacroHelpers.scala
scalameta/common/shared/src/main/scala/scala/meta/internal/tokens/branch.scala
scalameta/common/shared/src/main/scala/scala/meta/internal/tokens/metadata.scala
scalameta/common/shared/src/main/scala/scala/meta/internal/tokens/root.scala
scalameta/common/shared/src/main/scala/scala/meta/internal/tokens/token.scala

Also:
- simplify the root macro, matching only the needed fields
- define the branch macro, by copying root, removing custom parents and
replacing root annotations with branch annotations.

Token macros: create common abstract base class

---

tests/shared/src/test/scala/scala/meta/tests/inputs/FormatMessageSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/BaseDottySuite.scala

The output of println is not co-located with the test title which makes these somewhat hard to use to track down the issue. On the other hand, the assert clue is printed in the right location.

Tests: don't use println, pass clue to asserts

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala

LegacyScanner does not include backquotes in the `value` field of an Ident token, hence we don't need to do that.

ScalametaParser: don't need to strip backquotes

---

scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala
scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyToken.scala
scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyTokenData.scala
scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/ScalametaTokenizer.scala

Its handling is identical to IDENTIFIER; use a simple boolean in the one place where there's a difference.

LegacyScanner: don't use BACKQUOTED_IDENT

---

scalameta/dialects/shared/src/main/scala/scala/meta/Dialect.scala
scalameta/dialects/shared/src/main/scala/scala/meta/dialects/package.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/trees/ReflectionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/AndOrTypesSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/GivenUsingSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/SignificantIndentationSuite.scala

Otherwise we can't apply the complex infix formatting to them as the `|` and `&` tokens are not represented as separate children within the tree.
Needed by scalameta/scalafmt#3153.

Trees: turn Type.{And, Or} into infix-like trees

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/ParseSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/PatSuite.scala

It was duplicating code and inadvertently parsing the `op` after the `rhs`. Helps with #2315.

ScalametaParser: fix pattern infix type logic

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala

Scala contains a valid `scala.Tuple1` type. This will also allow us to differentiate `(a, b, c)` and `((a, b, c))`, the second being a nested tuple.

Trees: remove multiple-field constraint for Tuple

---

semanticdb/semanticdb/semanticdb.proto

Extract match_type part from https://github.com/scalameta/scalameta/pull/2414
Now it's time to merge at least for `MatchType` as https://github.com/lampepfl/dotty/pull/14608 is ready to merge :)
Let me work on metap implementation for `MatchType` in separate PR.

Support MatchType for Scala3

---

semanticdb/metap/src/main/scala/scala/meta/internal/metap/SymbolInformationPrinter.scala

Follow up for https://github.com/scalameta/scalameta/pull/2681
Confirmed locally, and looks good :+1:
```
Symbols:
example/MatchType$package.Concat# => type Concat[Xs <: Tuple, +Ys <: Tuple] = Xs match { EmptyTuple => Ys, *:[x, xs] => *:[x, Concat[xs, Ys]] }
...
example/MatchType$package.Elem# => type Elem[X] = X match { String => Char, Array[t] => t, Iterable[t] => t }
...
```
Here's how I confirmed the behavior
- `sbt publishLocal` (in scalameta/scalameta)
- published, for example, 2.13, 4.5.0-SNAPSHOT
- Go `lampepfl/dotty` with the branch https://github.com/lampepfl/dotty/pull/14608
- `sbt scalac -Xsemanticdb tests/semanticdb/expect/MatchType.scala`
- `coursier launch --main-class scala.meta.cli.Metap org.scalameta:scalameta_2.13:4.5.0-SNAPSHOT -- …

Support MatchType in `metap`

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/tokenizers/TokensPositionSuite.scala

Uses for `Term.ApplyInfix` the approach we took for `Pat.ExtractInfix`. Simplifies the code and sets positions for the RHS correctly.

ScalametaParser: use tuple for interim infix rhs

---

tests/jvm/src/test/scala/scala/meta/tests/metacp/MetacpOps.scala

Follow-up for https://github.com/scalameta/scalameta/pull/2681
This commit changes anything, as there are no MatchType included test files, and we don't invoke compilation using scala3 in the scalameta test at this moment :)

Support MatchType in metacp

---

scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala

Fixes #1917. Follow on to #2325.

TreeSyntax: handle Init argss explicitly

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala

ScalametaParser: keep `(())` as `Lit.Unit`

---

scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala

Fixes #2725 
This innocent-looking one-line change fixes my issue (by allowing literals to be treated as types by the printer), but I'm a little worried it might have some other impact I'm not aware of.

Support printing of literal types as type parameters

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/ParentChecks.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala

But only as the last argument. This is for ApplyInfix to work. Fixes #2720.

ParentChecks: allow Repeated to be part of Tuple

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/tokenizers/TokensPositionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala

This is not allowed in pattern matches but in generators backquoted identifiers are always treated as pattern variables, even with a `case` keyword
Fixes https://github.com/scalameta/scalameta/issues/2719

Allow using backquoted pattern vars in generators

---

scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala
tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala

TreeSyntax: use input Lit.{Char,String} if present

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/InlineSuite.scala

Previously, we would not remove newliens between sof keyword and the next token, which would lead to issues with double newlines after transparent. Now, we properly check if an indent is a soft identifier and in that case remove the newlines in the scanner.

Remove LF when soft keywords are used

---

scalameta/dialects/shared/src/main/scala/scala/meta/dialects/package.scala

Fixes https://github.com/scalameta/scalameta/issues/2733

Allow `?` as placeholder as default in Scala213 and Scala212 dialects

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
semanticdb/integration/src/main/scala/example/Infix.scala
tests/jvm/src/test/resources/example/Infix.scala
tests/jvm/src/test/resources/metac.expect
tests/jvm/src/test/resources/metacp.expect
tests/shared/src/test/scala-2.13/scala/meta/tests/tokenizers/TokensPositionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/BasicPositionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/tokenizers/TokenizerSuite.scala

fix: https://github.com/scalacenter/scalafix/issues/1594
related: https://github.com/scalameta/scalameta/pull/1489
Previously, for the following code
```scala
trait SymbolTest {
def shouldBe(right: Any): Unit
def arg = 1
this shouldBe (arg)
}
```
Scala2 (semanticdb-scalac) generates:
```scala
trait SymbolTest/*<=_empty_.SymbolTest#*/ { 
...
this shouldBe/*=>_empty_.SymbolTest#shouldBe().*/ (arg)/*=>_empty_.SymbolTest#arg().*/ 
} 
```
`[3:16..3:21): (arg) => _empty_/SymbolTest#arg().`
parens tokens are included in the `Term.ApplyInfix.args`.
This PR exclude the parens tokens from `args` and now scalameta generates:
```scala
trait SymbolTest/*<=_empty_.SymbolTest#*/ { 
...
this shouldBe/*=>_empty_.SymbolTest#shouldBe().*/ (arg/*=>_empty_.SymbolTest#arg().*/)
} 
```
`[3:17..3:20): arg -> …

fix: exclude parens tokens in Term.ApplyInfix.args

---

scalameta/dialects/shared/src/main/scala/scala/meta/Dialect.scala
scalameta/dialects/shared/src/main/scala/scala/meta/dialects/package.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/LazyTokenIterator.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/Scala213Suite.scala

Original PR in compiler - https://github.com/scala/scala/pull/8419
Fixes #2739.

scala213Source3 - allow infix op after NL

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/tokenizers/TokensPositionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/BasicPositionSuite.scala

- do not include parens in rhs args
- do include them in full infix when parens are part of lhs.
Supersedes #2744.

ScalametaParser: fix paren positions in infix expr

---

semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/TypeOps.scala

fix https://github.com/scalameta/scalameta/issues/2750
Confirmed it fixes the issue in https://github.com/tanishiking/scalameta-2750
As commented by https://github.com/scala/scala/blob/a3e918a10d2ed1fad78457377244106e22685277/src/reflect/scala/reflect/api/Types.scala#L996-L1014 those types shouldn't be accessible after type inference, and it might be a bug of scalac.

fix: Do not crash when scalameta hit BoundedWildcardType

---

scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/jvm/src/test/scala/scala/meta/tests/prettyprinters/RegressionSyntaxSuite.scala

Previously, we would always print `?` for the placeholder even if the Scala version wouldn't allow it. Now, we only print `?` if it was explicitely used in the code.
Fixes https://github.com/scalameta/scalameta/issues/2751
The other solution would be introducing another dialect, but that would require a lot of people having to also change that, so it would require a lot more effort in the long run.

Only print `?` for Scala 2 dialect if explicitly used

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MacroSuite.scala

Previously, if user started to write the macro spliced identifier the parser would throw an invariant exception. Now we check that we can construct proper name out of the Ident.
Fixes https://github.com/scalameta/scalameta/issues/2777

bugfix: Make sure that the macro ident is not just $

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MacroSuite.scala

Remove syntax error because it cannot currently occur. Follow up to #2779.

ScalametaParser: refactor macro ident matching

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala

Previously, we would always skip newlines between `open` identifier and the next token if that could start a statement. This led to lossing info about newlines even if the open modifier was not used. Now, we skip newlines after we know a soft keyword is used.
Fixes https://github.com/scalameta/scalameta/issues/2786

bugfix: Manually skip newlines after soft keywords

---

build.sbt

Currently, there is some memory consuming issue - https://github.com/scalameta/scalameta/actions/runs/2721177103
@keynmol suggested to enable batchMode for scala js linker.

try to fix release workflow

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala

ScalametaParser: allow `using` even in scala 2

---

scalameta/dialects/shared/src/main/scala/scala/meta/Dialect.scala

Originally, Dialect was a case class and we needed them to preserve the reference equality semantics. However, they are default with ordinary classes, and the overrides are no longer necessary.

Dialect: remove equals/hashCode overrides

---

semanticdb/metacp/src/main/scala/scala/meta/internal/classpath/ClasspathIndex.scala
tests/jvm/src/test/scala-2.12/scala/meta/tests/metacp/ClasspathIndexSuite.scala

The default classpath behavior should load directories,
or file that are archives (jar or zip), or wildcards should
be ignored.
I'd like to implement this behaviour here: ignoring invalid files
But there are multiple ways at it:
* manual check of the file, it's existence, it's extension
* catching the ZipException and swallow it
Do you have a suggestion on which on I should take? The first one
is more brittle, and we could possibly ignore jar/zip if they don't
have the right extension. Where as the second one could swallow error
that are not related.
I'm coming from https://github.com/scalacenter/scalafix/pull/1646
Current exception
```
java.util.zip.ZipException: zip END header not found
at java.util.zip.ZipFile$Source.findEND(ZipFile.java:1469)
at …
```

Avoid ZipException when loading classpath

---

scalameta/dialects/shared/src/main/scala/scala/meta/Dialect.scala
scalameta/dialects/shared/src/main/scala/scala/meta/dialects/package.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala

It replaces allowPlusMinusUnderscoreAsPlaceholder. Helps with #2807.

Dialect: add allowUnderscoreAsTypePlaceholder

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/ParseSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/BaseDottySuite.scala

Related to https://github.com/scalacenter/scastie/issues/636

bugfix: Show better error when no `{` is before case

---

scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/ParentChecks.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ExtensionMethodsSuite.scala

Reported in Discord: https://discord.com/channels/632642981228314653/632652693013528589/1016780987658682398
Syntax added in 3.2.0: https://scala-lang.org/blog/2022/09/05/scala-3.2.0-released.html#exports-in-extension-clauses

fix: allow export in extesion block

---

scalameta/common/shared/src/main/scala/org/scalameta/internal/MacroHelpers.scala
scalameta/common/shared/src/main/scala/scala/meta/internal/transversers/transverser.scala
scalameta/common/shared/src/main/scala/scala/meta/internal/trees/NamerMacros.scala
scalameta/common/shared/src/main/scala/scala/meta/internal/trees/ast.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/AstInfo.scala

Since it's now guaranteed that the returned type is a Quasi, it allows us to simplify the code a bit and remove some unnecessary checks and associated failure conditions.

ScalametaParser: quasi() returns T with Quasi

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala

Currently, we indicate whether we saw a `using` or `implicit` token in parameter parsing, and generate a new Mod tree that doesn't necessarily point to that keyword but to the current position.
Instead, let's generate the Mod tree over the keyword and pass it along.

ScalametaParser: in param, pass Mod tree, not flag

---

scalameta/common/shared/src/main/scala/org/scalameta/adt/Adt.scala
scalameta/common/shared/src/main/scala/org/scalameta/adt/Reflection.scala
scalameta/common/shared/src/main/scala/scala/meta/internal/trees/NamerMacros.scala
scalameta/common/shared/src/main/scala/scala/meta/internal/trees/TyperMacros.scala

Removes code duplication and maintenance overhead.

adt/Reflection: extract checking hierarchy method

---

tests/shared/src/test/scala/scala/meta/tests/quasiquotes/RoundtripSuite.scala

This follows the recent documentation updates and reflects the parsing which has been in place since last year.

RoundtripSuite: match templates without extends

---

scalameta/common/shared/src/main/scala/scala/meta/internal/trees/Liftables.scala

Subsequently, will allow us to implement other special cases, if that becomes necessary, in addition to Term.Apply handling.

Liftables: extract nested defs into class scope

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/TreeSuiteBase.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ExtensionMethodsSuite.scala

Currently, quasiquote ellipses are not supported when parsing parameters of extension groups.
Instead, let's move the rank-1 ellipsis parsing into the param() method and add the rank-2 parsing into the extension group invocation.

ScalametaParser: param ellipses in extension group

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/LazyTokenIterator.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/TokenIterator.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/TypeSuite.scala

Fixes https://github.com/scalameta/scalameta/issues/2853
Previously, we would not accept `type T = AnyRef with<Indentation>`. Now, we accept the statements in after indentation as refinements.

bugfix: Allow refinement after with in type

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/ParseSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/EnumSuite.scala

Follow up from https://github.com/lampepfl/dotty/pull/15961

bugfix: Don't allow open for enum cases

---

scalameta/common/shared/src/main/scala/scala/meta/internal/trees/NamerMacros.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/trees/ReflectionSuite.scala
tests/jvm/src/test/scala/scala/meta/tests/prettyprinters/RegressionSyntaxSuite.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/PatSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/TypeSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/GivenUsingSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MatchTypeSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/NewFunctionsSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/PatSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/TypeSuite.scala
tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala
tests/shared/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala

The `Placeholder` type (with bounds) we used earlier will be replaced with:
- `AnonymousParam`, with invariant/covariant/contravariant prefix indicator (for `"_"`, `"+_"` and `"-_"`)
- `Wildcard`, with bounds
Helps with #2807.

Trees: split off Type.Wildcard from Placeholder

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/trees/ReflectionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MatchTypeSuite.scala

Currently, unlike pattern matching for Terms which follows a different parsing logic and produces Pat trees, pattern matching for Types uses exactly the same logic as regular Types.
This occasionally leads to incorrect parsing, and here we try to address the specific problem of parsing a wildcards and anonymous params which is different in a type pattern match context.
Helps with #2807.

ScalametaParser: constrain match type pattern

---

scalameta/common/shared/src/main/scala/scala/meta/internal/transversers/transformer.scala
scalameta/common/shared/src/main/scala/scala/meta/internal/transversers/transverser.scala
scalameta/common/shared/src/main/scala/scala/meta/internal/transversers/traverser.scala

Access the fields directly via the owner instance. Helps with #2881.

Transverser: don't extract/bind fields via unapply

---

scalameta/dialects/shared/src/main/scala/scala/meta/Dialect.scala
scalameta/dialects/shared/src/main/scala/scala/meta/dialects/package.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala
tests/jvm/src/test/scala/scala/meta/tests/prettyprinters/RegressionSyntaxSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MatchTypeSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/PatSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/TypeSuite.scala
tests/shared/src/test/scala/scala/meta/tests/prettyprinters/PublicSuite.scala
tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala

This corresponds to the flag used by Scala 3

refactor: Rename Scala3x to Scala3Future

---

project/Mima.scala
scalameta/common/shared/src/main/scala/org/scalameta/adt/Liftables.scala
scalameta/common/shared/src/main/scala/org/scalameta/adt/Reflection.scala
scalameta/common/shared/src/main/scala/scala/meta/internal/transversers/transformer.scala
scalameta/common/shared/src/main/scala/scala/meta/internal/trees/TyperMacros.scala
scalameta/common/shared/src/main/scala/scala/meta/internal/trees/ast.scala
scalameta/common/shared/src/main/scala/scala/meta/internal/trees/metadata.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/trees/ReflectionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala

Fixes #2881, by making private vars into "official" fields akin to other ones, and by introducing a full unapply (with all fields) and changing `Liftables` to use that instead.

replace binaryCompatVar with a field annotation and full unapply

---

scalameta/common/shared/src/main/scala/scala/meta/internal/trees/ast.scala

Annotations could be applied on the left, to the entire ValDef (which is already stripped), or on the right thus annotating the type.

ast: deannotate definition types

---

scalameta/common/shared/src/main/scala/scala/meta/internal/trees/NamerMacros.scala
scalameta/common/shared/src/main/scala/scala/meta/internal/trees/ast.scala

We do not use them for our Trees, and no Tree types can be defined outside of `scala.meta` since they must define some package-private methods.
And removing handling of these multiple parameter lists simplifies the code substantially.

ast: disallow multiple parameter lists

---

scalameta/common/shared/src/main/scala/scala/meta/internal/trees/ast.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala

This method doesn't need to be binary-compatible and hence supports all current fields, unlike the primary copy method (the one with default parameter values) which, for backwards compatibility, must refer to the original order and types of parameters.

ast: add a private `fullCopy` method

---

scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/package.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala

Previously, AnonymousLambda could be used as a parent. Now, it can.

bugfix: Make AnonymousLambda contructable

---

scalameta/common/shared/src/main/scala/scala/meta/internal/trees/ast.scala
scalameta/common/shared/src/main/scala/scala/meta/internal/trees/metadata.scala

As an alternative to existing `newFields` which are appended at the end of the list of existing params, let's have the ability to remove a field as long as it's replaced with another.
Current implementation supports cases when the new field value can be determined from the old one via an implicit conversion, similar to how quasiquotes define implicit Lift/Unlift conversions.
This change is backwards-binary-compatible and hence will not trigger MIMA-verification alerts.

ast: allow replacing old fields with new ones

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
scalameta/trees/shared/src/main/scala/scala/meta/trees/Api.scala
tests/js/src/test/scala/scala/meta/tests/parsers/JSFacadeSuite.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/trees/ReflectionSuite.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/tokenizers/TokensPositionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/BasicPositionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/CommonTrees.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/DeclSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/DefnSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/ModSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/PackageSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/TemplateSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/TypeSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MacroSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MatchTypeSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/TypeSuite.scala
tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala
tests/shared/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala
tests/shared/src/test/scala/scala/meta/tests/transversers/SimpleTraverserSuite.scala
tests/shared/src/test/scala/scala/meta/tests/transversers/TraverserSuite.scala
tests/shared/src/test/scala/scala/meta/tests/trees/ChildrenSuite.scala
tests/shared/src/test/scala/scala/meta/tests/trees/InvariantSuite.scala
tests/shared/src/test/scala/scala/meta/tests/trees/TokensSuite.scala

Trees: use Type.Params, not List[Param]

---

tests/jvm/src/test/scala-2.13/scala/meta/tests/testkit/transversers/TraverserOrder.scala

fixes https://github.com/scalameta/scalameta/issues/2247

chore: Unignore TraversalOrder test after recent fixes

---

scalameta/common/shared/src/main/scala/scala/meta/prettyprinters/Show.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/shared/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala
tests/shared/src/test/scala/scala/meta/tests/transversers/SimpleTraverserSuite.scala
tests/shared/src/test/scala/scala/meta/tests/transversers/TraverserSuite.scala

Name.Anonymous was designed to be used when the name is not actually present; let's handle the few outlier cases when it stands for `_`.

TreeSyntax: don't print Name.Anonymous

---

tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala

Currently, `using` is not captured in that case.

MinorDottySuite: add tests with `using` in Init

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/ParentChecks.scala
semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/TextDocumentOps.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/trees/ReflectionSuite.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/tokenizers/TokensPositionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/DeclSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/StructureSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/BaseDottySuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/GivenUsingSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/NewFunctionsSuite.scala

Name.Anonymous was designed to be used when the name is not actually present; thus, using it for `_` is inconsistent and leads to complex handling.

Trees: add Name.Placeholder, use as appropriate

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/BasicPositionSuite.scala

ScalametaParser: bug fix, restore `(` pos in infix

---

scalameta/common/shared/src/main/scala/scala/meta/internal/trees/Liftables.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/ParentChecks.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/PlaceholderChecks.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/SyntacticTrees.scala
scalameta/trees/shared/src/main/scala/scala/meta/trees/Api.scala
semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/TextDocumentOps.scala
tests/js/src/test/scala/scala/meta/tests/parsers/JSFacadeSuite.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/trees/ReflectionSuite.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/tokenizers/TokensPositionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/contrib/TreeOpsSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/BasePositionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/BasicPositionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/SbtSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/XmlSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/GivenUsingSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/InlineSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala
tests/shared/src/test/scala/scala/meta/tests/quasiquotes/ErrorSuite.scala
tests/shared/src/test/scala/scala/meta/tests/quasiquotes/RoundtripSuite.scala
tests/shared/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala
tests/shared/src/test/scala/scala/meta/tests/transversers/SimpleTraverserSuite.scala
tests/shared/src/test/scala/scala/meta/tests/transversers/TraverserSuite.scala

Trees: use Term.ArgClause, not List[Term]

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala

In many cases, single arguments to makeTuple are handled differently.

ScalametaParser: add makeTuple handling of single

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/tokenizers/TokensPositionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala

ScalametaParser: use expr in implicit closure

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala

Follow-on to #2965 which introduced a bug.

ScalametaParser: shared mtd for Term.Function body

---

scalameta/common/shared/src/main/scala/scala/meta/internal/trees/ast.scala

For interleaved param clause groups, we will use rank 3. Needed by #2929.

ast: support ellipses past rank 2

---

scalameta/common/shared/src/main/scala/scala/meta/internal/trees/ast.scala
scalameta/common/shared/src/main/scala/scala/meta/internal/trees/metadata.scala
scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala

ast: allow replacing multiple fields with a single

---

scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/package.scala

Includes the check for repeated and a new one for implicit being only in the last clause.

Trees: check Def/Macro for valid param clauses

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ControlSyntaxSuite.scala

Specifically, do not use `isLeadingInfixOperator` anymore as that is not appropriate (no requirement for it to be leading, or for this feature to be enabled to parse `if/while` conditions in scala3).
Also, make sure that condExprInParens also consumes the terminating `do/then` keyword if found.

ScalametaParser: refactor condExprInParens

---

tests/jvm/src/test/resources/metac.expect_2.13

The number of diagnostics are overriden in the recently updated SemanticdbReporter, which is why we have more of them here.

bugfix: Fix expect test suite

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala

Also, move `isBackquoted` to ScannerTokens and use `token.text`, to get actual source backquoting. For #2880.

ScalametaParser: refactor token checks

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/SoftKeywords.scala

Use the right dialect flag, reuse soft keyword KwEnd properly handling `end` identifiers in backquotes.

Fix end marker handling

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/LazyTokenIterator.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ControlSyntaxSuite.scala

ScalametaParser: fix handling of `match` postfix

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/LazyTokenIterator.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala

Previously, there were positioned around the next non-trivial token.

LazyTokenIterator: move indent/outdent to NL

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/LazyTokenIterator.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala

That way, we will not look up the index when we already have it, or look it up multiple times for each successive or iterative invocation.

ScannerTokens: expose token index operations

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/LazyTokenIterator.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/Scala213Suite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/InfixSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala

https://docs.scala-lang.org/scala3/reference/changed-features/operators.html#syntax-change
Fixes #2880. Supersedes #2888.

ScalametaParser: handle leading infix correctly

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/NewFunctionsSuite.scala

Possibly a more compliant fix for #3020.

ScalametaParser: skip NL before func type arrows

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/LazyTokenIterator.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala

Remove the logic which caches token indices and tries to find the index for a given token.

ScannerTokens: require token index as param

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/LazyTokenIterator.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala

These methods do not require any of the instance variables provided by the LazyTokenIterator class, except tokens from ScannerTokens. For #3031.

LazyTokenIterator: move methods to ScannerTokens

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala

Instead, try parsing the function and back out if that fails. For #3031.

ScalametaParser: for fewer braces, avoid lookahead

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/LazyTokenIterator.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/TokenRef.scala

Later on, it will allow us to buffer subsequent tokens for lookahead.
Also, move TokenRef out as a toplevel class.
For #3031.

LazyTokenIterator: move regions into TokenRef

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/LazyTokenIterator.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/TokenRef.scala

Thus, regardless of forking, we should only compute each subsequent token once, with the exception of `observeIndented` cases which adjust the sequence during parsing. For #3031.

LazyTokenIterator: turn TokenRef into linked list

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala

Allow annotations before class constructor, meaning annotation could have its arg clauses but has to stop before ctor param clauses. For #2405.

ScalametaParser: parse annot args before params

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/LazyTokenIterator.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/TokenIterator.scala

That way, we substantially reduce overhead of looking ahead. This also allows avoiding forking in ScalametaParser in many cases. For #3031.

TokenIterator: add peekToken

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/TypeSuite.scala

Also, consistently check indentation of braces to stop in time. For #3045.

ScalametaParser: refactor refined types

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ControlSyntaxSuite.scala

Since an indent cannot follow another indent or outdent, make sure to add that check -- and fix a test along the way. For #3045.

ScannerTokens: refactor indent, avoid consecutive

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/BaseDottySuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/TypeSuite.scala

ScalametaParser: support coloneol in refined types

---

scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeStructure.scala
tests/shared/src/test/scala/scala/meta/tests/prettyprinters/TreeStructureSuite.scala

Its constructor doesn't take parameters.

TreeStructure: describe Lit.Null correctly

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/InfixSuite.scala

ScannerTokens: leading infix ops start with `@`

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/NewFunctionsSuite.scala

ScalametaParser: require indent for fewer braces

---

scalameta/common/shared/src/main/scala/scala/meta/internal/trees/ast.scala

Trees: avoid named/default args in annotations

---

.github/workflows/ci.yml

Extracts structured tests into additional groups. Increases the number of tests by 5, by adding jdk11 tests for the two latest scala versions and jvm/js/native.

YML: regroup CI tests

---

scalameta/dialects/shared/src/main/scala/scala/meta/Dialect.scala
scalameta/dialects/shared/src/main/scala/scala/meta/dialects/package.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/js/src/test/scala/scala/meta/tests/parsers/JSFacadeSuite.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/trees/ReflectionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/InterleavedDeclSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/InterleavedDefnSuite.scala

Also, add `Dialect.allowParamClauseInterleaving`. Based on #2820.

Trees: add interleaved param groups to Def/Macro for parameter clause interleaving

---

scalameta/common/shared/src/main/scala/scala/meta/internal/prettyprinters/Enquote.scala
tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala

TreeSyntax: enquote embedded '"""' if needed

---

scalameta/common/shared/src/main/scala/scala/meta/internal/trees/Version.scala
scalameta/common/shared/src/main/scala/scala/meta/internal/trees/ast.scala

Also, make sure the version annotations don't refer to future versions.

ast: parse current build version

---

docs/trees/guide.md
scalameta/common/shared/src/main/scala/org/scalameta/adt/Liftables.scala
scalameta/common/shared/src/main/scala/scala/meta/internal/trees/ast.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala

ast: preserve `apply/unapply` from older versions

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala

This will later allow us to make sure that it must follow other param modifiers.

ScalametaParser: keep Mod.ValParam in param parser

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/ModSuite.scala

It was introduced in #3084 by mistake.

ScalametaParser: fix parameter by-name logic

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala

1. make `anonymousUsing` into a val.
2. for consistency, escape the `lazy` modifier in the error message.

ScalametaParser: cosmetic in parameter parsing

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/ModSuite.scala
tests/shared/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala

1. check that val must follow explicit param modifiers
2. check there's no repeated implicit modifier on the first parameter; the existing code already checks for repeated modifiers except for the implicit/using modifier on the first parameter because the clause modifier is parsed outside of the `termParam` method.

ScalametaParser: validate parameter modifiers

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/SignificantIndentationSuite.scala

fix https://github.com/scalameta/scalameta/issues/3093
It seems like we should accept the optional braces around template body when we accept `:`, even inside the block with braces.
I'm trying to confirm this is valid change from syntax specification https://docs.scala-lang.org/scala3/reference/other-new-features/indentation.html (that's why it's still draft)...

Allow Optional Braces Around Template Bodies anyway

---

scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/CharArrayReader.scala
scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala
tests/shared/src/test/scala/scala/meta/tests/tokenizers/TokenizerSuite.scala

Specifically, do not interpret unicode escapes, double quotes etc. Fixes #3095.

LegacyScanner: treat comment chars differently

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/InfixSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala

ScalametaParser: fix detection of leading infix op

---

semanticdb/scalac/library/src/main/scala-2.12.13/scala/meta/internal/semanticdb/scalac/SemanticdbReporter.scala
semanticdb/scalac/library/src/main/scala-2.12.14/scala/meta/internal/semanticdb/scalac/SemanticdbReporter.scala
semanticdb/scalac/library/src/main/scala-2.12.15/scala/meta/internal/semanticdb/scalac/SemanticdbReporter.scala
semanticdb/scalac/library/src/main/scala-2.12.16/scala/meta/internal/semanticdb/scalac/SemanticdbReporter.scala
semanticdb/scalac/library/src/main/scala-2.12.17/scala/meta/internal/semanticdb/scalac/SemanticdbReporter.scala

Fix for issue https://github.com/scalameta/scalameta/issues/3099. The same reporter change that was made in Scala 2.13.1 was also made in Scala 2.12.13. Apply the same fix to Scala 2.12.13+.
Copied the reporter from:
https://github.com/bmarker/scalameta/blob/v4.7.6/semanticdb/scalac/library/src/main/scala-2.13/scala/meta/internal/semanticdb/scalac/SemanticdbReporter.scala
To:
https://github.com/bmarker/scalameta/blob/v4.7.6/semanticdb/scalac/library/src/main/scala-2.12.13/scala/meta/internal/semanticdb/scalac/SemanticdbReporter.scala
https://github.com/bmarker/scalameta/blob/v4.7.6/semanticdb/scalac/library/src/main/scala-2.12.14/scala/meta/internal/semanticdb/scalac/SemanticdbReporter.scala
https://github.com/bmarker/scalameta/blob/v4.7.6/semanticdb/scalac/library/src/main/scala-2.12.15/s …

bugfix: properly forward error/warning count to and from wrapped scalac reporter

---

semanticdb/integration/src/main/scala/example/ForComprehension.scala
semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/TextDocumentOps.scala
tests/jvm/src/test/resources/example/ForComprehension.scala
tests/jvm/src/test/resources/metac.expect_2.12
tests/jvm/src/test/resources/metac.expect_2.13
tests/jvm/src/test/resources/metacp.expect_2.12
tests/jvm/src/test/resources/metacp.expect_2.13
tests/jvm/src/test/scala/scala/meta/tests/semanticdb/TargetedSuite.scala

Fixes https://github.com/scalameta/metals/issues/4548

Correct occurences in for comprehensions containing `withFilter`

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/LazyTokenIterator.scala

Follow-up to #3123 fixing #3113.

LazyTokenIterator: further simplify undoIndent()

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/SoftKeywords.scala

The first method shows how token was constructed while the second one includes some sanity checks which are not appropriate in this context.

SoftKeywords: use token.text, not .toString

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/LazyTokenIterator.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/SepRegion.scala

Let's rename Region{Arrow,Case} for clarity
- RegionArrow was inserted on `case` (before arrow), whereas
- RegionCase was inserted on arrow, leading to a bit of confusion.
For #3045.

SepRegion: rename regions for case expressions

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala

ScalametaParser: allow brace after NL in infix arg

---

scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/shared/src/test/scala/scala/meta/tests/prettyprinters/TreeSyntaxSuite.scala

TreeSyntaxSuite: add tests with trailing blocks

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/ParseSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/TemplateSuite.scala
tests/shared/src/test/scala/scala/meta/tests/prettyprinters/TreeSyntaxSuite.scala

TreeSyntax: fix half-empty Self

---

scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala
tests/shared/src/test/scala/scala/meta/tests/prettyprinters/TreeSyntaxSuite.scala

Fixes #2046 
I tried to create a complete solution that works in all cases, not just the ones reported in the issue.
I added tests for all `Stat` combinations that I could find in https://scalameta.org/docs/trees/quasiquotes.html. Let me know if there is any relevant one that I missed.
---
In `guessNeedsLineSep` function I "expanded" the pattern matching of the stats (e.g. `Defn.Val(_, _, _, rhs) =>`), but maybe you would prefer a more concise solution.
Maybe something like this instead?
```scala
...
case t: Decl.Type => false
case t: Defn.Val => guessNeedsLineSep(t.rhs)
case t: Defn.Var => guessNeedsLineSep(t.body)
case t: Defn.Def => guessNeedsLineSep(t.body)
...
```
---
Note:
I think it would be better to not merge until the bugs I found while working on this (#3136 and #3138) are …

PrettyPrinter bug fix on Term.Block

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/LazyTokenIterator.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/SepRegion.scala

ScannerTokens: handle outdent before `then`, `do`

---

scalameta/common/shared/src/main/scala/scala/meta/internal/trees/Version.scala
scalameta/common/shared/src/main/scala/scala/meta/prettyprinters/Show.scala
scalameta/dialects/shared/src/main/scala/scala/meta/dialects/package.scala

To avoid warnings about inferred types.

Add explicit types to implicit definitions

---

project/plugins.sbt

https://mvnrepository.com/artifact/com.thesamet.scalapb/scalapb-runtime_2.13/0.11.11
CVEs:
- https://nvd.nist.gov/vuln/detail/CVE-2022-3510 (High: 7.5 CVSS)
- https://nvd.nist.gov/vuln/detail/CVE-2022-3509 (High: 7.5 CVSS)
- https://nvd.nist.gov/vuln/detail/CVE-2022-3171 (High: 7.5 CVSS)

scalapb: 0.11.11 → 0.11.13, scalajs: 1.8.0 → 1.12.0

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/FewerBracesSuite.scala

Fixes #3164. By making it explicitly invalid...

ScalametaParser: fail if no fewer-braces body

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/DerivesSuite.scala

ScalametaParser: allow newline after `derives`

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/LazyTokenIterator.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/TokenIterator.scala

That way, we can correctly process template with self-type and remove the `undoIndent` work-around. For #3045.

ScalametaParser: allow indent after self-type

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/SepRegion.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/EndMarkerSuite.scala

To do that, generalize enum mark to cover all elements using coloneol. For #3045.

ScannerTokens: infer coloneol indent automatically

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/LazyTokenIterator.scala

Since we are substituting `curr` token, we should work on `prev`.

LazyTokenIterator: fix observeIndented once again

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ErasedDefsSuite.scala

ScalametaParser: allow `erased` keyword in lambda

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ErasedDefsSuite.scala

ScalametaParser: allow `erased` keyword in types

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/PatSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala

ScannerTokens: allow top-level `case`

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScaladocParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/ScaladocParserSuite.scala

ScaladocParser: require space after list prefix

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/Messages.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/ModSuite.scala

ScalametaParser: don't fail on `override` in class

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ExtensionMethodsSuite.scala

ScannerTokens: `extension` can also start block

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/DefnSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/SignificantIndentationSuite.scala

ScannerTokens: `case class` can be in `case` body

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ControlSyntaxSuite.scala

Unlike other control regions, where the primary goal is to detect purely scala3 constructs (conditions without parens, instead using significant indentation and a terminating token), RegionFor is also used to handle `case` that is not for `catch/match` -- nor a partial function.
Fixes #3220.

ScannerTokens: use RegionFor for scala2 also

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/tokenizers/TokensPositionSuite.scala

ScalametaParser: include infix start in first lhs

---

community-test/src/test/scala/CommunityDottySuite.scala

For very large repositories, cloning the entire repo takes too long.

CommunityDottySuite: clone/fetch to depth=1

---

community-test/src/test/scala/CommunityDottySuite.scala

If we test multiple versions of a repo, the tests will by default be labelled as "-1", "-2" etc. Instead, let's include the actual commit.

CommunityDottySuite: include commit in test label

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ControlSyntaxSuite.scala

Also remove scala3 check for `do` and `then` as these keywords naturally imply scala3. Fixes #3224. Follow-up to #3221.

ScannerTokens: handle `yield` in scala2

---

community-test/src/test/scala/CommunityDottySuite.scala

Existing recursive implementation would result in `too many open files` on sufficiently large repositories.

CommunityDottySuite: lazily traverse repository

---

scalameta/tokens/shared/src/main/scala/scala/meta/tokens/Tokens.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/TemplateSuite.scala

Tokens: check index out of bounds in `apply`

---

project/build.properties

Currently, `+publish` doesn't apply any of the workarounds mentioned in https://github.com/sbt/sbt/issues/7327#issuecomment-1627805403. Reverts #3243.

SBT: downgrade back to 1.6.2

---

build.sbt
project/Mima.scala
scalameta/testkit/jvm/src/main/scala/scala/meta/testkit/Corpus.scala
scalameta/testkit/shared/src/main/scala/scala/meta/testkit/FileOps.scala

Apparently, geny.Generator is the result type of a public method within this library, and since it's used only for testing, and only in `scalafmt` benchmarks, changing that result type should be ok.

SBT: remove geny dependency in testkit

---

project/Versions.scala

Let's include, for each minor version, up to 4 patch versions.

SBT: build only for the last 4 versions of scala

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/NestedContext.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala

Fixes scalameta/metals#5437. Supersedes #3253.

bugfix: Fix nested types with underscore

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/SepRegion.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/SignificantIndentationSuite.scala

Follow-up to #3254. Fixes #3257.

ScannerTokens: expand comma rule

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/SignificantIndentationSuite.scala

An expression which starts with an indent doesn't have to be indented but instead could start with an indented part and continue past it. Fixes #3261.

ScalametaParser: don't use exprMaybeIndented()

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/SignificantIndentationSuite.scala

The syntax is still incorrect but will be fixed in a separate commit.

ScannerTokens: force LF if multiple newlines

---

scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/TemplateSuite.scala

TreeSyntax: separate block in all stat sequences

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/NestedContext.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala

The current implementation was mistakenly sharing context with any other instantiated parsers, which would cause problems in a multi-threaded use such as within scalafmt. Fixes #3063.

NestedContext: move all contexts to parser

---

docs/semanticdb/guide.md
semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/ConfigOps.scala

That is, one could specify `-P:semanticdb:sourceroot:targetroot:../xyz`. Fixes #2515.

ConfigOps: sourceroot as relative to targetroot

---

scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/SignificantIndentationSuite.scala

TreeSyntax: separate block in scala3 stats

---

build.sbt

Until sbt-shading plugin is released with the cross-platform fixes, let's limit shading to JVM only. Helps with #3259.

SBT: shade only for JVM

---

build.sbt

The previous attempt would incorrectly enable the ShadingPlugin even if no shading was expected to occur, which led to it being run with default parameters and erroring out. Follow-on to #3277.

SBT: shade only for JVM (fix)

---

scalameta/io/js/src/main/scala/java/nio/file/Path.scala
scalameta/io/js/src/main/scala/scala/meta/internal/io/NodeNIOPath.scala
scalameta/io/shared/src/main/scala/scala/meta/io/RelativePath.scala
semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/ConfigOps.scala
semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/InputOps.scala

semanticdb: use canonical path for sourceroot

---

scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/CharArrayReader.scala

scalameta/metals uses the class, too. fixes scalameta/metals#5492.

CharArrayReader: relax the class/field visibility

---

build.sbt

Perhaps it should depends on that project.

SBT: integration uses jar from SemanticDB plugin

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/FewerBracesSuite.scala

ScannerTokens: fix `case` clause in fewer braces

---

build.sbt

Looks like there are some issues with shading for Scala 2.11.12, so since this is a barely supported version I don't think we need to shade it. It's currently only used in Metals I think.
Related to https://github.com/scalameta/metals-vscode/issues/1420

bugfix: Don't shade for 2.11.12

---

build.sbt
project/plugins.sbt

For now, use a snapshot version of the sbt-shading plugin as formal releases aren't available yet. Fixes #3259.

SBT: shade platform-specific dependencies

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/TypeSuite.scala

ScalametaParser: parse path-like types explicitly

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala

Follow-on to #3322. Helps with scalameta/scalafmt#3623.

ScalametaParser: fewer-braces colon must start rhs

---

scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/Chars.scala

tokenizers.Chars: remove unused methods

---

scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/CharArrayReader.scala
tests/shared/src/test/scala/scala/meta/tests/tokenizers/TokenizerSuite.scala

Also add an explicit test for this case. Helps with #3328.

tokenizers.CharArrayReader: inline unicode CRLF

---

scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala

Remove unused methods, inline some calls, make private etc. Helps with #3328.

tokenizers.LegacyScanner: clean up

---

tests/shared/src/test/scala/scala/meta/tests/tokenizers/TokenizerSuite.scala

Add test with a unicode surrogate pair

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScaladocParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/Scaladoc.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/ScaladocParserSuite.scala

ScaladocParser: add EnclosedJavaTag as a text part

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala

Most recently, compiler started displaying warnings about invocations of a few methods that they are defined both in an outer class as well as a parent class and that such ambiguity will not be allowed in scala3.

ScalametaParser: fix warnings, inherited vs outer

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/AstInfo.scala

It's unnecessary and used only in one place.

AstInfo: remove ClassTag derivation

---

tests/shared/src/test/scala/scala/meta/tests/TreeSuiteBase.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/TemplateSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/TypeSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/DerivesSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/EnumSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ErasedDefsSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ExtensionMethodsSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/GivenUsingSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/InfixSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/InlineSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/NewFunctionsSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/SignificantIndentationSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/TypeSuite.scala
tests/shared/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala
tests/shared/src/test/scala/scala/meta/tests/trees/InvariantSuite.scala

For Scala 3 the tests started failing here since both apply and the constructor could be applied there, because the new keyword is no longer required.
There is a bunch of other classes with that problem, but I will do it one by one.

improvement: Explicitely use empty Term.ArgClause

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/EndMarkerSuite.scala

ScannerTokens: end marker must be preceded by NL

---

build.sbt
scalameta/testkit/jvm/src/main/scala/scala/meta/testkit/Corpus.scala

https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/net/URL.html#%3Cinit%3E(java.lang.String)

avoid deprecated `java.net.URL` constructor

---

scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala

Before:
```scala
q"def f: (B => B) => A".syntax
// "def f: B => B => A"
```
After:
```scala
q"def f: (B => B) => A".syntax
// "def f: (B => B) => A"
```
See the added test for more examples. Other cases are welcome as I might have missed something

Fix FuncParamClause not adding parentheses for Type.Function

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/TreeSuiteBase.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/CommonTrees.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/LitSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/ModSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/TemplateSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ControlSyntaxSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/EndMarkerSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/EnumSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/FewerBracesSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/InfixSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/InlineSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/NewFunctionsSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/SignificantIndentationSuite.scala
tests/shared/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala
tests/shared/src/test/scala/scala/meta/tests/trees/InvariantSuite.scala

For compatibility with Scala 3 where the new keyword is not needed.

refactor: Use Ctor.Primary primary apply by default

---

tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/Scala3SyntaxSuite.scala
tests/shared/src/test/scala/scala/meta/tests/tokenizers/BaseTokenizerSuite.scala
tests/shared/src/test/scala/scala/meta/tests/tokenizers/TokenizerSuite.scala

This shows a lot of warning when compiling with Scala 3 (I am down to like 80!) and also don't use quasiquotes in Scala3SyntaxSuite as it's not needed and not supported in Scala 3

refactor: Don't use pattern match on val in TokenSuite

---

scalameta/trees/shared/src/main/scala/scala/meta/internal/Scaladoc.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/ScaladocParserSuite.scala

Scaladoc: fix syntax of EnclosedJavaTag

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/LazyTokenIterator.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/TokenIterator.scala

Instead, add the `indenting` method which specifically validates whether there's an increase in significant indentation at given newline. Helps with scalameta/scalafmt#3720.

TokenIterator: replace {current,peek}Indentation

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/LazyTokenIterator.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/ScalametaTokenizer.scala

Use EOL/AtEOL instead of LF or LFLF in matching

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
scalameta/tokens/shared/src/main/scala/scala/meta/tokens/Token.scala
tests/jvm/src/test/scala/scala/meta/tests/tokens/ReflectionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/ParseSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/PatSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/FewerBracesSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/InfixSuite.scala

The implementation was incorrect, didn't check the case when the infix op was on a line by itself.
However, the fix is incomplete as it doesn't handle the very rare case when the infix expression is at the file level and not nested within a block of any kind. This will be fixed in the next commit.
Also, add a correlated fix in `getOutdentIfNeeded`.

ScannerTokens: make `isLeadingInfix` compliant

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala

Since we had already obtained the current indent position, which points to the final newline (either token or multiline comment), we no longer need to traverse all trivia tokens between prevPos and nextPos and just backtrack from the indent position, to find the EOL token and then again to check whether we have a blank line.

ScannerTokens: improve obtaining lastNewlinePos

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/LazyTokenIterator.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/SepRegion.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/FewerBracesSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/InfixSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/SignificantIndentationSuite.scala

Use it when an LF token is emitted, to preserve the indent. It is useful in order to identify when to outdent a fewer-braces region, especially when leading-infix operators are used with smaller indentation than the significant-indentation region they belong to but larger than the outer.

ScannerTokens: introduce a line-indent region

---

scalameta/common/shared/src/main/scala/scala/meta/internal/trees/ast.scala

That way, when we eventually create additional apply methods which take these private field values, they will put these values first and will align with the underlying class constructor. Liftable macros will need to construct apply parameters using the order of fields in the class. Helps with #3425.

ast: move private fields to before other fields

---

scalameta/quasiquotes/shared/src/main/scala/scala/meta/internal/quasiquotes/ReificationMacros.scala

Make use explicit, especially since some of these values conflict with identically named fields in `MacroHelpers`.
Helps with #3425.

ReificationMacros: don't import `definitions._`

---

tests/shared/src/test/scala/scala/meta/tests/TreeSuiteBase.scala
tests/shared/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala

Add a quasiquotes test showing `origin` is missing

---

scalameta/common/shared/src/main/scala/org/scalameta/adt/Reflection.scala

Documentation for `.decls` indicates the declarations could be returned in arbitrary order, which goes against the assumption around this method that the fields can be used to pass to companion `apply()` and hence are expected to be in the order that apply uses them. Helps with #3425.

adt.Reflection: retrieve fields in sorted order

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/Pos.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/Origin.scala
tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala

When we implement lifting of origin in quasiquotes, it would make the resulting code more compact if the common part (input and dialect) are lifted only once, rather than for every subtree, thus leaving only the position field to change.
Helps with #3425.

Origin: extract input/dialect into separate class

---

scalameta/common/shared/src/main/scala/org/scalameta/adt/Liftables.scala
scalameta/common/shared/src/main/scala/scala/meta/internal/trees/Liftables.scala
scalameta/quasiquotes/shared/src/main/scala/scala/meta/internal/quasiquotes/ReificationMacros.scala

In ReificationMacros, request them for term quasiquotes only, so that possibly private state is saved by the compiler, but not for pattern.
This is one of key changes enabling storing of origin for quasiquotes. Helps with #3425.

adt.Liftables: include private fields if requested

---

scalameta/dialects/shared/src/main/scala/scala/meta/Dialect.scala
scalameta/quasiquotes/shared/src/main/scala/scala/meta/internal/quasiquotes/ReificationMacros.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/Origin.scala
tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala

Perhaps this solution was rather masking the problem with TreeSyntax.
Reverts scalameta/scalameta#3460

Revert "Origin: add flag enabling unquotes to ParsedSource"

---

project/ShadedDependency.scala

Notice it in some error reprots we were sent:
java.lang.NoClassDefFoundError: sourcecode/Name
```
scala.meta.internal.tokenizers.XmlParser$Xml$.UnpStart(XmlParser.scala:48)
scala.meta.internal.tokenizers.XmlParser$Xml$.Unparsed(XmlParser.scala:47)
scala.meta.internal.tokenizers.XmlParser$Xml$.XmlContent(XmlParser.scala:43)
scala.meta.internal.tokenizers.XmlParser.$anonfun$XmlExpr$1(XmlParser.scala:24)
scala.meta.shaded.internal.fastparse.internal.RepImpls$.rec$4(RepImpls.scala:226)
scala.meta.shaded.internal.fastparse.internal.RepImpls$.rep$extension(RepImpls.scala:266)
scala.meta.shaded.internal.fastparse.package$ByNameOps$.rep$extension(package.scala:202)
scala.meta.internal.tokenizers.XmlParser.XmlExpr(XmlParser.scala:24)
scala.meta.internal.tokenizers.LegacyScanner.$anonfun$getXml$2(Le …
```

bugfix: Shade sourcecode as it's a dependency of fastparse

---

scalameta/common/shared/src/main/scala/scala/meta/internal/trees/ast.scala

Type annotations are in some cases used to trigger invariant checks which would otherwise be skipped.

ast: do not remove type and definition annotations

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/tokens/shared/src/main/scala/scala/meta/internal/prettyprinters/TokensToString.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeStructure.scala
tests/jvm/src/test/scala/scala/meta/tests/tokenizers/UnicodeEscapeSuite.scala
tests/shared/src/test/scala/scala/meta/tests/tokens/TokensSuite.scala

`.toString` ultimately calls `.text` but first checks whether the token is consistent with its dialect.

Tokens: use Token.text, not .toString

---

scalameta/common/shared/src/main/scala/scala/meta/internal/trees/NamerMacros.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/Pos.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/quasiquotes/shared/src/main/scala/scala/meta/internal/quasiquotes/ReificationMacros.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeToString.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/InternalTrees.scala
scalameta/trees/shared/src/main/scala/scala/meta/trees/Origin.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/testkit/prettyprinters/PrettyPrinterSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/ParseSuite.scala
tests/shared/src/test/scala/scala/meta/tests/prettyprinters/PublicSuite.scala
tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala
tests/shared/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala

As origin is now saved as part of quasiquotes, let's make sure it abides by MIMA standards (which are not currently applied to `internal` code).
Similarly, remove TokenStreamPosition and inline in Origin.Parsed. Helps with #3425.

Origin: move out of `internal`

---

scalameta/common/shared/src/main/scala/scala/meta/internal/trees/NamerMacros.scala
scalameta/common/shared/src/main/scala/scala/meta/internal/trees/ast.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/trees/ReflectionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/SbtSuite.scala
tests/shared/src/test/scala/scala/meta/tests/prettyprinters/PublicSuite.scala
tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala
tests/shared/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala
tests/shared/src/test/scala/scala/meta/tests/transversers/SimpleTraverserSuite.scala
tests/shared/src/test/scala/scala/meta/tests/transversers/TraverserSuite.scala

This is one of key changes enabling storing of origin for quasiquotes. Helps with #3425.

ast: save origin as a private field, add `apply()`

---

scalameta/quasiquotes/shared/src/main/scala/scala/meta/internal/quasiquotes/ReificationMacros.scala
tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala

Helps with #3425. Fixes bug introduced in #3457.

ReificationMacros: fix handling of embedded `$`

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/quasiquotes/shared/src/main/scala/scala/meta/internal/quasiquotes/ReificationMacros.scala
scalameta/trees/shared/src/main/scala/scala/meta/trees/Origin.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala
tests/shared/src/test/scala/scala/meta/tests/prettyprinters/PublicSuite.scala
tests/shared/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala

This way, we won't get tokens and positions but `toString` will work.
We can use this origin for quasiquotes which have interpolated values (that we couldn't meaningfully use with Origin.Parsed as its Input would contain interpolation references rather than the values that these references would expand to).
Helps with #3425.

Origin: add a DialectOnly version

---

scalameta/common/shared/src/main/scala/scala/meta/internal/trees/NamerMacros.scala
scalameta/common/shared/src/main/scala/scala/meta/internal/trees/ast.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/InternalTrees.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/trees/ReflectionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala

We could do this now as origin is now a persisted field and could be declared public.

Tree: remove privateOrigin, ensure origin is valid

---

build.sbt
project/ShadedDependency.scala

It was earlier set up to rename symbols from the sourcecode library but not included in the jar. Let's fix it. Follow-on to #3468.

SBT: add shading to the common package

---

build.sbt
project/ShadedDependency.scala

SBT: undo shading of the `sourcecode` dependency

---

scalameta/inputs/shared/src/main/scala/scala/meta/inputs/Position.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/InternalTrees.scala
scalameta/trees/shared/src/main/scala/scala/meta/trees/Origin.scala

Need to make Parsed.position lazy as well, otherwise its own lazy vals would not persist.

Trees: save tokens and positions as lazy

---

scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/InternalTrees.scala
tests/shared/src/test/scala/scala/meta/tests/tokenizers/TokenizerSuite.scala
tests/shared/src/test/scala/scala/meta/tests/trees/InfrastructureSuite.scala
tests/shared/src/test/scala/scala/meta/tests/trees/TokensSuite.scala

Make both methods take explicit dialect parameter, and make their names reflect that they are doing non-trivial work potentially.

InternalTrees: rename dialectText, add tokenizeFor

---

scalameta/scalameta/shared/src/main/scala/scala/meta/package.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala
tests/shared/src/test/scala/scala/meta/tests/prettyprinters/PublicSuite.scala
tests/shared/src/test/scala/scala/meta/tests/trees/TokensSuite.scala

If we convert a tree to a parsed tree, the latter will contain proper origin, with input, and will not require regenerating tokens, syntax etc. on every access.

Tree: add `maybeParse` extension, for a parsed tree

---

build.sbt

mdoc currently depends on scalameta and is used here to build scalameta docs. Let's rely on that version of the library which is used by mdoc, rather than trying to substitute the current one (which might not work with mdoc anymore, if binary compat is broken).

SBT: remove circular dependency with mdoc

---

scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/InternalTrees.scala
tests/shared/src/test/scala/scala/meta/tests/tokenizers/TokenizerSuite.scala
tests/shared/src/test/scala/scala/meta/tests/trees/TokensSuite.scala

That way, we will not incur hidden syntax-generation and tokenization costs implicitly; for that, we have the `tokenizeFor` method.

InternalTrees: require origin dialect in `tokens`

---

project/Mima.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/InternalTrees.scala

Deprecate the older method, with the dialect parameter.

InternalTrees: add tokens overload without dialect

---

scalameta/common/shared/src/main/scala/scala/meta/internal/trees/NamerMacros.scala
scalameta/common/shared/src/main/scala/scala/meta/internal/trees/ast.scala
scalameta/quasiquotes/shared/src/main/scala/scala/meta/internal/quasiquotes/ReificationMacros.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/SyntacticTrees.scala
scalameta/trees/shared/src/main/scala/scala/meta/trees/Api.scala
scalameta/trees/shared/src/main/scala/scala/meta/trees/Origin.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala
tests/jvm/src/test/scala/scala/meta/tests/dialects/ReflectionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/TreeSuiteBase.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/TypeSuite.scala
tests/shared/src/test/scala/scala/meta/tests/tokenizers/TokenizerSuite.scala
tests/shared/src/test/scala/scala/meta/tests/trees/TokensSuite.scala

That way, all our trees will have a proper origin containing a dialect.
Move previous versions of apply, those without dialect, to a new trait, and extend companion object from that trait. That way, MIMA is satisfied and compiler doesn't complain of similar methods matching invocation.
One complexity arises for trees which are defined at the package level rather than within an object. In that case, we can't use that new trait as the macro is not allowed to emit extraneous types at top level.
In that case, we will not pass the implicit dialect but will determine it from one of the trees which were passed as arguments to apply().

ast: implicit dialect in apply(), store in origin

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/FewerBracesSuite.scala

Helps with scalameta/scalafmt#3763.

ScalametaParser: keep block around func with mods

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala

Since it returns a function, it is expecting a `=>` which would be "swallowed" by any infix type.

ScalametaParser: in implicitClosure, no full type

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala

Instead of taking an arbitrary lambda, simply expect a closing delimiter like Outdent or RBrace.

ScalametaParser: make `blockExprPartial` specific

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala

ScalametaParser: no anonymous func around postfix

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/GivenUsingSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala

ScalametaParser: allow `lazy` with `given`

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/FewerBracesSuite.scala

Previously, we would simply parse it as a regular expression and then, if we encounter a `=>`, convert it to a `Term.Function`.
However, that approach fails when modifiers are used (such as `erased`), so we need to implement a custom parser.
Helps with scalameta/scalafmt#3763.

ScalametaParser: parse colon-space arg as lambda

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/FewerBracesSuite.scala

Now that we have taken care of the case with space after colon, let's consider the newline case as well.

ScalametaParser: parse coloneol arg as lambda

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/LazyTokenIterator.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/SignificantIndentationSuite.scala

ScannerTokens: move comma past outdents in parens

---

CONTRIBUTING.md
scalameta/dialects/shared/src/main/scala/scala/meta/Dialect.scala
scalameta/dialects/shared/src/main/scala/scala/meta/dialects/package.scala
scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala
scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyTokenData.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/LitSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/ParseSuite.scala
tests/shared/src/test/scala/scala/meta/tests/tokenizers/TokenizerSuite.scala

SIP: https://docs.scala-lang.org/sips/binary-integer-literals.html
Scala 2: https://github.com/scala/scala/pull/10656
Scala 3: https://github.com/lampepfl/dotty/pull/19551

add binary literals support

---

scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ControlSyntaxSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/FewerBracesSuite.scala

It already contains `{}`. Fixes #3544.

TreeSyntax: omit `()` around partial function

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/SepRegion.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ControlSyntaxSuite.scala

Since we allow `finally` to be at the same indent as the `try` body, we could end up with `finally` terminating both the previous `catch` as well as the outer `try`.
Instead, let's introduce a new `RegionTry` and ensure that this region is not removed before the `finally` keyword, so that we won't end up with an exposed outer `RegionTry`.
Fixes #3532.

ScannerTokens: improve handling of `finally`

---

scalameta/common/shared/src/main/scala/scala/meta/internal/transversers/transverser.scala

Since every Quasi tree in reality derives from one of the other types, and the declaration of a Quasi tree follows that of its parent, the case for the parent happens before the case for the quasi, and hence the quasi code is unreachable.
Since the intention was likely to exclude Quasi trees altogether, let's skip them at the beginning rather than the end.

Transversers: skip Quasi before other trees

---

build.sbt

Now that most warnings have been fixed, let's make the build stricter.
Limit these extra checks to scala-2.13 only, as that's sufficient to ensure clean code and avoids running into tooling differences between versions.

SBT: fail build on warnings, treat some as info

---

scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/ParentChecks.scala
tests/shared/src/test/scala/scala/meta/tests/trees/InvariantSuite.scala

The new version of scala 2.13 has finally discovered these issues, so let's fix them before adding support for that version.
First, we were using a parent check whereas we should have used a field check.
Second, the pattern was incorrect and didn't match the case of a single nested single-element tuple.
Finally, the only case that would have matched if it had been used as a field check was unnecessary, since the `@nonEmpty` notation covered it.

Fix invalid check: empty or nested Member.Tuple

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/FewerBracesSuite.scala

Fixes scalameta/scalafmt#3785.

ScalametaParser: in fewer braces, limit type parse

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ControlSyntaxSuite.scala

- Remove wrong LF check for `case`
- Detect `case class` in `case` body
Fixes scalameta/scalafmt#3790. Fixes scalameta/scalafmt#3789.

ScannerTokens: improve handling within `case` body

---

scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala
scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyTokenData.scala

Rather than storing them in the buffer and then removing again, let's simply not store them at all, so the relevant logic is not repeated. Helps with scalameta/sbt-scalafmt#299.

LegacyScanner: skip numeric separators early

---

scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala
scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyTokenData.scala

Since we already established that the next character is a digit, let's remove obsolete code which tries to consider other possibilities after that. Let's also remove the check for failure this logic has ruled out.

LegacyScanner: remove unused float parsing logic

---

scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala
tests/shared/src/test/scala/scala/meta/tests/tokenizers/TokenizerSuite.scala

Octal has been removed since scala 2.11 so `base = 8` is not really a valid option; instead, we should simply convey that the number starts with a leading zero and make further decisions based on that.
Additionally, the newly added binary literals (starting with `0b`) would no longer be allowed to become floating-point literals (as `base <= 10` check has now been explicitly turned into `base == 10`).

LegacyScanner: more explicitly check for octal

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala

These values cannot be specified using the scala numeric literal format and only using predefined constants like `Double.PositiveInfinity` and `Float.NaN`.
However, these constants would not be parsed as `Lit.Float` anyway, and instead as `Term.Select(...)`.

Lit.{Float,Double}: disallow NaN and Infinity

---

scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala
scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyTokenData.scala

A prefix helps set the `base` field, and the suffix the `token` field. Thus, we don't need to store them in the character buffer and hence won't need to strip them when we parse the numeric value.

LegacyScanner: skip numeric prefixes and suffixes

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/LitSuite.scala

That is, allow integer overflow within corresponding unsigned range for binary literals just like for hexadecimals.

Lit.{Int,Long}: handle `0b` exactly like `0x`

---

scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala
tests/shared/src/test/scala/scala/meta/tests/tokenizers/TokenizerSuite.scala

Partial undo of #3593 where this logic was accidentally removed.

LegacyScanner: allow repeated number separators

---

docs/trees/guide.md

Looks like quasiquotes now preserve comments in the source string.
```
>scala-cli repl --scala 2 --dep org.scalameta::scalameta:4.9.0
scala> import scala.meta._
import scala.meta._
scala> println(q"function  (    argument   ) // comment")
function  (    argument   ) // comment
```

doc: quasiquote now preserve comments

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
scalameta/tokens/shared/src/main/scala/scala/meta/tokens/package.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala
tests/shared/src/test/scala/scala/meta/tests/prettyprinters/PublicSuite.scala

This way, this check will be available publically.

ScannerTokens: symbolic infix check to common

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/DefnSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/SignificantIndentationSuite.scala

- first, match HSpace instead of Whitespace, to exclude LFLF
- second, on double EOL, return No instead of InvalidArg (which is used
to indicate incorrectly indented infix arguments).
Fixes #3605.

ScannerTokens: yet another leading infix fix

---

scalameta/dialects/shared/src/main/scala/scala/meta/Dialect.scala
scalameta/dialects/shared/src/main/scala/scala/meta/dialects/package.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/trees/ReflectionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MacroSuite.scala
tests/shared/src/test/scala/scala/meta/tests/prettyprinters/PublicSuite.scala
tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala

Support quoted type variables in Dialect and ScalametaParser

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala

If the first part succeeded, we assume this execution path to be correct and simply proceed with simpleExprRest() without catching errors there.

ScalametaParser.simpleExpr: don't catch in "rest"

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/InfixSuite.scala

Fixes scalameta/scalafmt#3825.

ScannerTokens: add RegionLine if indented further

---

tests/shared/src/test/scala/scala/meta/tests/parsers/ModSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/PatSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/VarargParameterSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/PatSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/TypeSuite.scala

Add tests with syntax-like backquoted identifiers

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/Keywords.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/TypeSuite.scala

Keywords: define generic matcher replacing Ident

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MacroSuite.scala

ScalametaParser: check `$` not backquoted in macro

---

scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/InternalTrees.scala

There's already a token cache per input, so this is excessive and unnecessary. First introduced in #3484. Fixes #3650.

InternalTrees: don't keep token cache per tree

---

scalameta/common/shared/src/main/scala/scala/meta/internal/tokens/token.scala

There's no need to look up the underlying text from position and input when the token is fixed.

token: override definition of `text()` for fixed

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/LazyTokenIterator.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/SignificantIndentationSuite.scala

`nextToken` ignored the `.next` field and tried to recompute the next token; instead, we should not do that if that field is already set.
Fixes #3664. Follow-up to #3542.

ScannerTokens: keep multiple outdents to swap `,`

---

scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/CharArrayReader.scala
tests/shared/src/test/scala/scala/meta/tests/tokenizers/BaseTokenizerSuite.scala
tests/shared/src/test/scala/scala/meta/tests/tokenizers/TokenizerSuite.scala

For some reason, invalid or incomplete unicode surrogates are allowed
by the scala compiler. Also, we were only checking for standalone
high surrogates, not the low surrogates.
Therefore, let's remove this validation. If we assume that the code is
compilable, it's not our job to invalidate it.
Fixes #3690. Follow on to #3402.

CharArrayReader: remove validation of surrogates

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/tokenizers/TokensPositionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ExtensionMethodsSuite.scala

Also, retain a significant-indentation block if it ends in a detached comment, as otherwise the comment's indentation would be lost. Fixes #3689.

ScalametaParser: keep pos if dropping outer block

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala

ScalametaParser: remove trailing comment in endpos

---

scalameta/dialects/shared/src/main/scala/scala/meta/Dialect.scala
scalameta/dialects/shared/src/main/scala/scala/meta/dialects/package.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyTokenData.scala
scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/package.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ControlSyntaxSuite.scala

Previously, this logic was unlocked with `allowSignificantIndentation` implicitly. Use `.allowQuietSyntax` for `if-then`/`while-do`. Helps with scalameta/scalafmt#3941.

Dialects: add explicit `allowQuietSyntax` flag

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
tests/jvm/src/test/resources/metac.expect_2.12
tests/jvm/src/test/resources/metac.expect_2.13

This allows explicit LF before right delims if present.

ScannerTokens: check right delim in CantStartStat

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ControlSyntaxSuite.scala

Fixes #3713. This undoes #3688 as incorrectly reported.

ScannerTokens: do not allow breaks within `for()`

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/LitSuite.scala

Return them as `Term.ApplyUnary` as we used to do until recently. Fixes scalameta/scalafmt#4028.

ScalametaParser: allow custom unary with floats

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/package.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ControlSyntaxSuite.scala

ScalametaParser: allow Enum.Val before generator

---

build.sbt

Otherwise, sbt will show errors that 2.13.14 library is being used and that is no longer valid if we publish for lower Scala version.

bugfix: Try to fix publish after sbt bump

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/jvm/src/test/scala/scala/meta/tests/semanticdb/MetacScalaLibrary.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MacroSuite.scala

Follow-on to #3728. Fixes #3731.

ScalametaParser: add expressions before apply type

---

semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/TextDocumentOps.scala
tests/jvm/src/test/scala/scala/meta/tests/semanticdb/SemanticdbSuite.scala
tests/jvm/src/test/scala/scala/meta/tests/semanticdb/TargetedSuite.scala

For instance, we might substitute a `Type.Name("Unit")` when the type is missing in a method declaration, but its input position is empty as it isn't actually present in the itput, which might lead to errors due to hash collisions with a parameterless-method name.
Prior to v4.9.4, it "worked" since the position of the empty name was actually around the newline token rather than the preceding method-name token.
Fixes #3738.

TextDocumentOps: don't index empty names

---

build.sbt

The issue was that protobuf settings were adding shared settings, which only set the cross versions to latest and not all. I removed it from protobuf settings since it's already contained in the project.

bugfix: Fix publishing

---

build.sbt

Don't rely on sbt inferring the module name from the variable name which defines the project. Follow-on to #3747.

SBT: use explicit names for published modules

---

scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala
scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/ScalametaTokenizer.scala

Rather than adding a special case for two quotes, simply make sure we set the correct token offset, skipping all the leading quotes.

ScalametaTokenizer: refactor emitting interpolatns

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/LazyTokenIterator.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala

That way, we'll include LFLF or any other multi-EOL container.

ScannerTokens: use AtEOL instead of EOL

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/package.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ExportImportSuite.scala

The latter also includes `Term.This`. Fixes #3754.

Trees: remove Ref.isStableId, use isPath instead

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala

Now that CRLF is a dedicated token, we don't need to distinguish AtEOL vs EOL unless in the context of single- vs multi-line cases.

ScannerTokens: use AtEOL instead of remaining EOL

---

semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/DiagnosticOps.scala
semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/SyntheticOps.scala
semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/TextDocumentOps.scala
semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/package.scala
semanticdb/semanticdb/src/main/scala/scala/meta/internal/metap/RangePrinter.scala
semanticdb/semanticdb/src/main/scala/scala/meta/internal/semanticdb/Implicits.scala
tests/jvm/src/test/scala/scala/meta/tests/semanticdb/SemanticdbSuite.scala

That way, we don't need to duplicate this simple code in RangePrinter.

Scalac: move Position/Range implicit to semanticdb

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala

Similarly to NL and indent, let's make sure to be more aggressive with search positions for next iteration.

ScannerTokens: set `prevPos/currPos` for outdent

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
tests/jvm/src/test/resources/example/Classes_2.12.scala
tests/jvm/src/test/resources/example/Classes_2.13.scala
tests/jvm/src/test/resources/metac.expect_2.12
tests/jvm/src/test/resources/metac.expect_2.13

Turns out it improves semanticDB symbol detection and makes it handle names followed by a single newline vs multiple newlines consistently.

ScannerTokens: change LFLF pointPos to first LF

---

scalameta/tokens/shared/src/main/scala/scala/meta/tokens/Token.scala

Since we detect CRLF sequences as a single token, CR will only appear as a standalone token, hence can be treated as EOL.

Token: requalify CR as an EOL token

---

tests/shared/src/test/scala/scala/meta/tests/parsers/ParseSuite.scala

All parse rules defined in ParseSuite use the Input.applyRule extension which calls `requireNonEmptyOrigin` method, so there's no need to do it again.

ParseSuite: don't re-check for empty origins

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/ParseSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/InfixSuite.scala

In ParseSuite, test and compare LF, CR and CRLF code.

ScannerTokens: finish support for CR, expand tests

---

.scalafmt.conf

Otherwise, rewrite rules are too aggressive for 2.12. See comment to #3803.

scalafmt: set dialect to 2.12 to reflect our build

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/jvm/src/test/scala/scala/meta/tests/parsers/dotty/CtrlExprJVMSuite.scala

If a scala3 if/while actually uses scala2 syntax, we might have parsed part of the body while looking for `then` or `do`, which leads to some backtracking.
Specifically, for nested `if` clauses with their `then` part in explicit braces, each will be parsed exactly twice, once as a continuation of the condition expression and second time as the body, thus leading to an exponential time complexity.
Let's instead reduce backtracking by processing what might be both an argument to a condition expression or an initial part of the body, such as a brace expression, and then using it either for condition or for body.
Fixes scalameta/metals#6552. Supersedes #3795.

ScalametaParser: less backtrack on ctrl cond, body

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/EndMarkerSuite.scala

Fixes scalameta/scalafmt#4098.

ScannerTokens: skip RegionLine at indent level

---

scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/CharArrayReader.scala
scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala
tests/shared/src/test/scala/scala/meta/tests/tokenizers/TokenizerSuite.scala

Instead, in CharArrayReader, add stateless char-reading methods.

LegacyScanner: remove, don't use lookaheadReader

---

build.sbt
project/Versions.scala

If we use latest by default then the semanticdb parts will also depend on newer Scala versions, which is breaking for anything that might be using it as dependency.
The other option here is to change their suffix to full and publish separate for each version, but I would rather avoid it as it would mean more artifacts to publish and a change for any dependency.
This showed up in https://github.com/scalameta/metals/pull/6608

bugfix: Use earliest Scala version for scalameta, parsers and trees projects

---

.github/workflows/ci.yml
build.sbt
project/Versions.scala

Turns out, the previous approach didn't work and we still published with the newest Scala version. I changed it to only use the earliest versions, so that it's not even possible to set newer versions. I also changed sharedSettings to not include cross settings by default as they should be defined per project (or with fullCrossSettings).

bugfix: Set earlier versions as only cross versions for scalameta projects

---

tests/shared/src/test/scala/scala/meta/tests/TreeSuiteBase.scala

TreeSuiteBase: `munit._` is imported, don't repeat

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/InfixSuite.scala

indentPos is the last newline whereas eolPos is the first. Also, move empty infix targs after op. Helps with #3856.

ScannerTokens: move InfixLF to indentPos

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala

Don't allow emitting LF after Outdent, so no more extra LF tokens which might have an earlier position than the Outdent itself leading to empty trees such as Lit.Unit occasionally covering tokens between the LF and the Outdent and breaking logic. Fixes #3856.

ScannerTokens: don't produce LF after Outdent

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ControlSyntaxSuite.scala

We already check `match` but these additional keywords went undetected. Helps with scalameta/scalafmt#4133.

ScannerTokens: check end marker for try/for/while

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala

ScannerTokens: check end marker for `if` as well

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala

ScalametaParser: remove EndPosPreOutdent, invalid

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ControlSyntaxSuite.scala

ScalametaParser: terminate generator on outdent

---

tests/shared/src/test/scala/scala/meta/tests/prettyprinters/SyntacticSuite.scala

SyntacticSuite: don't reset origins, use `reprint`

---

tests/shared/src/test/scala/scala/meta/tests/TreeSuiteBase.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/XmlSuite.scala
tests/shared/src/test/scala/scala/meta/tests/tokenizers/BaseTokenizerSuite.scala
tests/shared/src/test/scala/scala/meta/tests/tokenizers/TokenizerSuite.scala
tests/shared/src/test/scala/scala/meta/tests/tokens/TokensSuite.scala

TreeSuiteBase: move `tokenize` method centrally

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ControlSyntaxSuite.scala

ScalametaParser: `for` uses `yield` alongside `do`

---

scalameta/inputs/shared/src/main/scala/scala/meta/inputs/Input.scala
scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/ScalametaTokenizer.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/InternalTrees.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala
tests/shared/src/test/scala/scala/meta/tests/TreeSuiteBase.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/BasePositionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/MoreHelpers.scala
tests/shared/src/test/scala/scala/meta/tests/prettyprinters/PublicSuite.scala
tests/shared/src/test/scala/scala/meta/tests/tokenizers/TokenizerSuite.scala

Since our public code signatures take Input and Dialect, the only way to provide TokenizerOptions without breaking MIMA compatibility is by using either of those types.
Neither of them in reality is perfect for this task, but since Dialect is a final class and adding tokenizer options as a field to it seems a bit illogical, let's implement it as a wrapper of the Input type.
Follow-on to #3786.

Input: add WithTokenizerOptions wrapper

---

scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/ScalametaTokenizer.scala

INVALID legacy tokens are frequently output after the token they intend to invalidate, including whitespace tokens.
This particular issue was masked by the previous whitespace-grouping change which didn't flush whitespace tokens immediately.
Fixes interop between #3835 and #3786.

ScalametaTokenizer: check for INVALID after space

---

scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/InternalTrees.scala
scalameta/trees/shared/src/main/scala/scala/meta/trees/Origin.scala

In InternalTree, use it to tokenize, before resorting to syntax parsing. Also, if that Input contained any TokenizerOptions, they would naturally be used. Follow-on to #3786.

Origin: internally expose possible input

---

scalameta/common/shared/src/main/scala/scala/meta/internal/prettyprinters/ShowMacros.scala
scalameta/common/shared/src/main/scala/scala/meta/prettyprinters/Show.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala

Otherwise, our checks on intermediate results being None are incorrect. For this, turn most Result into regular classes, and add companion apply definitions doing the filtering. Helps with #3913.

Show: carefully filter None values early

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala

That includes colon and `with` before optional-braces body. No change to braces-enclosed template bodies. Helps with #3913.

Trees: include leading keyword in template body

---

scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/ScalametaTokenizer.scala
tests/shared/src/test/scala/scala/meta/tests/tokenizers/TokenizerSuite.scala

Related to https://github.com/scalameta/metals/issues/6699
It seems the code is perfectly reachable after all, so maybe it's better to default to invalid.
The other option I was thinking about (or an additional) is to finish interpolation splice right away with and End, but that might be too complex for a case that might not pop up that often.

bugfix: Don't throw when broken string interpolation

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/tokenizers/TokensPositionSuite.scala

It's pointless when PartialFunction and CasesClause amount to exactly the same tree. Helps with #3913.

Trees: revert change to Term.PartialFunction

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala

ScalametaParser: add `:` in opt braces, not `with`

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala

Helps with #3913. Follow-on to #3944.

ScannerTokens: fix outdent before blank+comment

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/InlineSuite.scala

Fixes https://github.com/scalameta/scalameta/issues/3947
I don't think we need to add a dialect for it, since the error isn't really important for parser

chore: Add transparent modifier as acceptable for class

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala

Helps with #3913. Follow-on to #3946 and #3944.

ScannerTokens: fix outdent logic allowing blanks

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/SepRegion.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/InfixSuite.scala

ScannerTokens: RegionTemplateMark can also have LF

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/DefnSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/ModSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/ParseSuite.scala

Scala defines `Singleton` as a final trait, so this check is aggressive.

ScalametaParser: don't assume `abstract` on trait

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ControlSyntaxSuite.scala

ScannerTokens: don't strip RegionTry if indented

---

scalameta/dialects/shared/src/main/scala/scala/meta/Dialect.scala
scalameta/dialects/shared/src/main/scala/scala/meta/dialects/package.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/SoftKeywords.scala
scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/trees/ReflectionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/LanguageExtensionsSuite.scala

This PR adds basic support for the experimental `tracked` modifier.
Relevant links:
- https://dotty.epfl.ch/docs/reference/experimental/modularity.html
- https://github.com/scala/scala3/blob/e9d48313a2e11685a148e105f038da368485aa66/docs/_docs/internals/syntax.md?plain=1#L382
Any feedback will be appreciated.

Add basic support for `tracked` parameters

---

scalameta/dialects/shared/src/main/scala/scala/meta/Dialect.scala
scalameta/dialects/shared/src/main/scala/scala/meta/dialects/package.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala
tests/shared/src/test/scala/scala/meta/tests/DialectSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/AndOrTypesSuite.scala
tests/shared/src/test/scala/scala/meta/tests/prettyprinters/PublicSuite.scala

It looks like from the parser perspective the only change was binary literals going non experimental in 3.5.0

Add Scala35 dialect

---

.github/workflows/release.yml

This is currently used by metals.

chore: Also release semanticdbMetap when releasing semanticdb

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ControlSyntaxSuite.scala

This change was overlooked in #3883. Fixes #3979.

ScalametaParser: don't apply Eta if canApply=false

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/DefnSuite.scala

ScalametaParser: backquoted pat is var before `:`, `@`

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScaladocParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/Scaladoc.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/ScaladocParserSuite.scala

While this is non-standard, real-world usage is occasionally different. Move the actual list prefix from ListBlock to ListItem, and add the new ListType field to ListBlock instead. Helps with scalameta/scalafmt#4350.

ScaladocParser: recognize list items w/ `2.`, `c.`

---

build.sbt
project/os.scala

JDK 23 adds `java.io.IO` to stdlib, causing an import conflict with `sbt.io.IO`
this came up in the Scala 2 community build: https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-jdk23-integrate-community-build/222/artifact/logs/scalameta-extract.log

fix build on JDK 23

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/NamedTuplesSuite.scala

Fixes #4007. Alternative to #4009.

ScalametaParser: allow named types within `types()`

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ErasedDefsSuite.scala

ScalametaParser: support `erased` w/ class params

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/trees/ReflectionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/TypeSuite.scala

ScalametaParser: support named type arguments

---

scalameta/dialects/shared/src/main/scala/scala/meta/Dialect.scala
scalameta/dialects/shared/src/main/scala/scala/meta/dialects/package.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/SoftKeywords.scala
scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/ParentChecks.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/trees/ReflectionSuite.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/TypeSuite.scala

ScalametaParser: parse `into` param type modifier

---

scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/NewFunctionsSuite.scala

Also, refactor to prepare for supporting pure functions later. Helps with #3996.

TreeSyntax: fix bug w/ context function precedence

---

scalameta/dialects/shared/src/main/scala/scala/meta/Dialect.scala
scalameta/dialects/shared/src/main/scala/scala/meta/dialects/package.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/TypeSuite.scala

The previous one was based on an older version of documentation. Follow-on for #3995.

ScalametaParser: adjust `into` implementation

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/tokens/shared/src/main/scala/scala/meta/tokens/package.scala
scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/trees/ReflectionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/BasicPositionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/CommonTrees.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/QuasiquoteSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/InfixSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala

Just like ApplyInfix, which largely reflects form rather than content, and could have been expressed as a Select followed by an Apply instead, let's introduce SelectPostfix.
This also makes it clear that any Select trees are properly constructed having a dot in their syntax, as recent scala releases started requiring an explicit import to allow `postfixOps`.

Trees: add Term.SelectPostfix

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/trees/ReflectionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/CommonTrees.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ControlSyntaxSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/SignificantIndentationSuite.scala

Similar to #4040, add a separate tree for `match` with a dot.

Trees: add Term.SelectMatch

---

build.sbt

There is not a lot of actual code here for native and JS and we don't need to compile it for BSP. It's easy enable it if needed, but by default it hugely limits the first compilation times.

chore: Disable BSP for Native and JS

---

scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala
tests/shared/src/test/scala/scala/meta/tests/tokenizers/TokenizerSuite.scala

Related to https://github.com/scalameta/metals/issues/7003
Looks like there is at least 6 stack traces formatting error for InvalidToken and this looks like a problem.
We get things like:
```
at java.util.regex.Pattern$BmpCharProperty.match(java.base@11.0.24/Pattern.java:3966)
at java.util.regex.Pattern$GroupHead.match(java.base@11.0.24/Pattern.java:4807)
at java.util.regex.Pattern$Branch.match(java.base@11.0.24/Pattern.java:4752)
at java.util.regex.Pattern$Branch.match(java.base@11.0.24/Pattern.java:4750)
at java.util.regex.Pattern$BranchConn.match(java.base@11.0.24/Pattern.java:4716)
at java.util.regex.Pattern$GroupTail.match(java.base@11.0.24/Pattern.java:4866)
at java.util.regex.Pattern$BmpCharPropertyGreedy.match(java.base@11.0.24/Pattern.java:4347)
at …
```

improvement: Don't use format since it seems to break at some chars

---

build.sbt

-skip-packages doesn't do anything with empty input. The implicit options are no longer relevant for Scala 3.

bugfix: Fix generating scaladoc for Scala 3

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala

Split parsing on left bracket vs on left paren, and observe that only the first group may start on a paren (as otherwise that paren would have been folded into the previous group). Helps with #4047.

ScalametaParser: refactor parsing ParamClauseGroup

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/SignificantIndentationSuite.scala

Use in `givenDecl` as well. Helps with #4047.

ScalametaParser: refactor `templateParents()`

---

build.sbt
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala

Also, in ScalametaParser, fix non-local returns as they are deprecated in scala3.

SBT: treat Scala3 warnings as errors as well

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/ParentChecks.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/CommonTrees.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/GivenSyntax36Suite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/GivenUsingSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/SignificantIndentationSuite.scala

The complexity largely arises from having to deal with both old and new. Fixes #4047.

ScalametaParser: detect new `given` syntax

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/TrailingCommaSuite.scala

Once again, the role of this parser is not to complain about unambiguous contexts, relaxing this constraint will allow interpreting code which is "almost" correct and can be corrected easily by a tool like scalafmt or scalafix.

ScannerTokens: relax trailing comma NL constraint

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/GivenSyntax36Suite.scala

ScalametaParser: new given can use `name[type] =>`

---

scalameta/common/shared/src/main/scala/scala/meta/internal/trees/ast.scala

This includes detecting a simple alias. Helps with #4093.

ast: improve detection of replaced fields

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/BasicPositionSuite.scala

Remove syntax error checks. Helps with #4093.

ScalametaParser: simplify {Decl,Defn}.Type parsing

---

scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/GivenSyntax36Suite.scala

TreeSyntax: print context bounds using new syntax

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests-semanticdb/src/test/scala-2.13/scala/meta/tests/api/SurfaceSuite.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/parsers/dotty/Scala3PositionSuite.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/tokenizers/TokensPositionSuite.scala
tests/shared/src/test/scala-2/scala/meta/tests/quasiquotes/SuccessSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/CommonTrees.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/DefnSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/EnumSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/GivenSyntax36Suite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/InterleavedDefnSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/NewFunctionsSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/TypeSuite.scala

Since SIP-64, every case which uses Type.Bounds in existing trees needs to support context bounds (unlike some of the cases which are currently implemented using Type.Param but might not support context bounds). Fixes #4093.

Trees: move context bounds Type.{Param -> Bounds}

---

semanticdb/scalac/library/src/main/scala-2.11/scala/meta/internal/scalacp/package.scala
semanticdb/scalac/library/src/main/scala-2.12/scala/meta/internal/scalacp/package.scala
semanticdb/scalac/library/src/main/scala-2.13/scala/meta/internal/scalacp/package.scala
semanticdb/scalac/library/src/main/scala/scala/meta/internal/scalacp/SymbolOps.scala
semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/SymbolOps.scala

Specifically, unlike java version, it provides getOrElseUpdate.

SymbolOps: use scala HashMap for caches

---

semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/TextDocumentOps.scala
tests-semanticdb/src/test/resources/example/Synthetic_2.13.scala
tests-semanticdb/src/test/resources/metac.expect_2.13
tests-semanticdb/src/test/scala/scala/meta/tests/semanticdb/OccurrenceSuite.scala

In a recent version of compiler, it uses incorrect position values for anonymous functions which leads to incorrect symbol matching for that function instead of its body.
Hence, make sure we don't allow the function to get to the fallback case in the match and explicitly traverse parameters and body separately.
Fixes #3975.

TextDocumentOps: traverse function properly

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala-2/scala/meta/tests/quasiquotes/SuccessSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/CommonTrees.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/NamedTuplesSuite.scala

This PR adds support for named patterns in extractor patterns (e.g. when matching case classes).

ScalametaParser: support named tuples in extractor patterns

---

scalameta/common/shared/src/main/scala/scala/meta/internal/trees/Reflection.scala
scalameta/common/shared/src/main/scala/scala/meta/internal/trees/metadata.scala
scalameta/common/shared/src/main/scala/scala/meta/internal/trees/registry.scala

We replace the List with varargs, so that we do not have to "unapply" the List apply signature in the quasiquote when reading the registry in a macro.

Refactor: simplify Metadata.registry annotation

---

.github/workflows/release.yml

It's currently not fully cross published and caused https://github.com/scalameta/scalameta/actions/runs/12726385364/job/35474709067

bugfix: Don't publish shared module for specific version

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
scalameta/trees/shared/src/main/scala/scala/meta/Trees.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/tokenizers/TokensPositionSuite.scala
tests/shared/src/test/scala-2/scala/meta/tests/quasiquotes/SuccessSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/CommonTrees.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/DefnSuite.scala

Pretending to have them outside, within Type.Param, was leading to an inconsistency in positions, where Type.Bounds would have viewbounds within its limits but in a parent tree.

Trees: move viewbounds into Type.Bounds as well

---

semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/TextDocumentOps.scala
tests-semanticdb/src/test/scala-2.12/scala/meta/tests/semanticdb/PrintSuite.scala

While the new implementation is still a bit cryptic, it clarifies some cases which looked incomplete (like matching on two very specific cases without a default) and more often avoids recomputing a previously found synthetic.
Possibly easier to modify in the future, such as for #4135.

TextDocumentOps: reimplement generating synthetics

---

semanticdb/metac/src/main/scala/scala/meta/internal/metac/Main.scala
semanticdb/metacp/src/main/scala/scala/meta/internal/metacp/Main.scala
semanticdb/scalac/library/src/main/scala/scala/meta/interactive/InteractiveSemanticdb.scala
semanticdb/scalac/library/src/main/scala/scala/meta/internal/classpath/ClasspathUtils.scala
tests-semanticdb/src/test/scala/scala/meta/tests/semanticdb/MetacScalaLibrary.scala
tests/jvm/src/test/scala-2.13/scala/meta/tests/testkit/ScalacParser.scala

In Java 11, URLClassLoader is no longer used, and the only documented simple solution is to use `java.class.path` system property. Possibly fixes #1985.

Semanticdb: fix direct reliance on URLClassLoader

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/DefnSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/SignificantIndentationSuite.scala

See https://dotty.epfl.ch/docs/reference/syntax.html#expressions-2. Fixes #4147.

ScalametaParser: PolyFunction is not a simple expr

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/SepRegion.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/FewerBracesSuite.scala

Whether within Def, Extension, Given or Class. Fixes #4152.

ScannerTokens: no fewer braces within ParamClause

---

build.sbt
tests-semanticdb/src/test/scala-2.12/scala/meta/tests/package.scala
tests-semanticdb/src/test/scala-2.13/scala/meta/tests/package.scala
tests/shared/src/test/scala-2.12/scala/meta/tests/package.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/package.scala

Use dependencyOverrides to avoid pulling in a conflicting version of scala-library from the munit package.

munit: finish upgrade to v1.1.0, use DiffOptions

---

semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/TextDocumentOps.scala
tests-semanticdb/src/test/scala-2.12/scala/meta/tests/semanticdb/PrintSuite.scala

Previously, we'd cache that TypeApply, which is not handled for `for` comprehensions, would not have a synthetic, vs not used with for-comp.
Helps with scalacenter/scalafix#2175.

TextDocumentOps: handle only for-apply w/ implicit

---

scalameta/trees/shared/src/main/scala/scala/meta/internal/parsers/ScaladocParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/ScaladocParserSuite.scala

Currently, we are always stripping leading space, whether or not it precedes the `*` margin character.

ScaladocParser: fix stripping space around EOL

---

semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/SyntheticOps.scala
semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/TextDocumentOps.scala
tests-semanticdb/src/test/resources/example/ValPattern.scala
tests-semanticdb/src/test/resources/metac.expect_2.12
tests-semanticdb/src/test/resources/metac.expect_2.13

Also, always traverse ValDef rhs first, as it helps with capturing pattern occurrences from LHS since for pattern occurrence conflicts the last one wins. Fixes #4169.

TextDocumentOps: get pattern occurrences in ValDef

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/GivenUsingSuite.scala

Helps with scalameta/scalafmt#4764.

ScannerTokens: handle `given` pattern after `case`

---

project/plugins.sbt

Reverts scalameta/scalameta#4193. It's not needed, sbt-ci-release includes it.

Revert "SBT: add sbt-sonatype plugin for updated config"

---

scalameta/common/shared/src/main/scala/scala/meta/prettyprinters/Show.scala
scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
tests/shared/src/test/scala/scala/meta/tests/prettyprinters/TreeSyntaxSuite.scala

In the logic deciding whether to insert a newline between two stats, checking if the next stat is a block is insufficient, as it could be an expression (select or infix chain) which *starts* with a block.
Instead, let's turn it into a Show.Result and check if it starts with a brace.
Fixes #4202.

TreeSyntax: look for brace, not just Term.Block

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala-2.13/scala/meta/tests/tokenizers/TokensPositionSuite.scala

Since tree fields are changing, and `unapply` always supports only the initial field composition, let's not use `unapply` when constructing a new tree from these fields, as they might lose their parsed positions. Fixes #4208.

ScalametaParser: no `unapply` to copy Type trees

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScannerTokens.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ControlSyntaxSuite.scala

Don't insert two template marks, for both `package` and `object`. Fixes #4214.

ScannerTokens: handle `package object` correctly

---

docs/trees/guide.md

I was fiddling with this, couldnt figure out why in my playground examples the comments are there, but in "real project" (https://github.com/sake92/regenesca/blob/main/example/src/example/Example.scala#L20-L30)
TLDR:
If you do `source""" /**/ val x = 5 """.syntax` that works 
But `source""" /**/ val ${myVarName} = 5 """.syntax` does not

Bold the quasiquotes comments not preserved docs

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/InfixSuite.scala

ScalametaParser: allow indented infix type args

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala

Fix for #4233, follow-up to #4227.

ScalametaParser: allow NL before infix type args

---

semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/TextDocumentOps.scala
semanticdb/semanticdb/shared/src/main/scala/scala/meta/internal/semanticdb/Implicits.scala
tests-semanticdb/src/test/scala/scala/meta/tests/semanticdb/OccurrenceSuite.scala

We are using bazel as a build tool, which relies on compilation being idempotent. Unordered sequences in .semanticdb files result in unnecessary jar files changes and build cache misses. 
Here I've added some order to TextDocument serialization to speed up bazel builds with semanticdb.

Deterministic .semanticdb files

---

tests/shared/src/test/scala/scala/meta/tests/TestHelpers.scala
tests/shared/src/test/scala/scala/meta/tests/TreeSuiteBase.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/BasePositionSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/MoreHelpers.scala

Previously, it was in BasePositionSuite, which also includes parsing.

TreeSuiteBase: move asserting positions

---

docs/semanticdb/specification.md
semanticdb/semanticdb/shared/src/main/proto/semanticdb.proto
semanticdb/semanticdb/shared/src/main/scala/scala/meta/internal/metap/SyntheticPrinter.scala

As a continuation of #2464. Closes #2460. One step towards scala/scala3#22936.

Add ApplyContextTree for context parameter application

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/TermSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/NamedTuplesSuite.scala

The potential for ambiguity only comes for single-value tuples. Helps with scalameta/scalafmt#4948.

ScalametaParser: check named tuples dialect flag

---

scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/FewerBracesSuite.scala
tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/NamedTuplesSuite.scala

ScalametaParser: keep type tuple with named types
